### ISSUE TITLE
Improve handling of complex chimy symbols

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1035]
- Wiktionary page: https://fr.wiktionary.org/wiki/acide_acrylique

Wikicode:
```
{{fchim|CH|2|3==CHCOOH}}
```

Output:
```
CH<sub>2</sub>3==CHCOOH
```

Expected:
```
CH<sub>2</sub>3=CHCOOH
```

---

Model link, if any:

**Comment by BoboTiG** [comment]
Another problematic formula: https://fr.wiktionary.org/wiki/cacox%C3%A9nite
Wikicode:
```
{{fchim|Fe{{e|3+}}|24|Al[(OH)|12|{{!}}(OH)|6|{{!}}(PO|4|)|17|]·17H|2|O}}
```

**Comment by lasconic** [comment]
The https://fr.wiktionary.org/wiki/cacox%C3%A9nite one should be handled correctly if 
https://github.com/BoboTiG/ebook-reader-dict/issues/1053 is fixed.
