### ISSUE TITLE
Improve clean-up of external links with title

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1049]
- Wiktionary page: https://fr.wiktionary.org/wiki/peur_bleue

Wikicode:
```
[[http://www.tv5monde.com/cms/chaine-francophone/lf/Merci-Professeur/p-17081-Une-peur-bleue.htm?episode=10 Voir aussi l’explication de Bernard Cerquiglini en images]]
```

Output:
```
http://www.tv5monde.com/cms/chaine-francophone/lf/Merci-Professeur/p-17081-Une-peur-bleue.htm?episode=10 Voir aussi l’explication de Bernard Cerquiglini en images
```

Expected:
```
Nothing.
```

**Comment by lasconic** [comment]
External links use a single square bracket. Here it's a external link and the title of the link is supposed to be in between square bracket... We mistakenly render it as an external link. If we would render it like the other external links with title, then the result would be 

```
[Voir aussi l’explication de Bernard Cerquiglini en images]
```
