### ISSUE TITLE
[FR] Wrong analysis of ethymology subparts

### ISSUE THREAD

**Issue by pythoulon** [BoboTiG/ebook-reader-dict#1097]
- Wiktionary page: [Succube](https://fr.wiktionary.org/wiki/succube#%C3%89tymologie)

Wikicode:
```
=== {{S|étymologie}} ===
: Du {{étyl|la|fr|mot=succuba|sens=[[concubine]]}}, de ''{{lien|succubus|la}}'', {{composé de|sub-|sens1=[[sous]]|cubare|sens2=[[coucher]]|sens=qui couche sous|lang=la}}.
```

Output:
```
Du latin succuba (« concubine »), de succubus, dérivé de cubare (« sous ») avec le préfixe sub- (« coucher »), littéralement « qui couche sous ».
```

Expected:
```
Du latin succuba (« concubine »), de succubus, dérivé de cubare (« coucher ») avec le préfixe sub- (« sous »), littéralement « qui couche sous ».
```

---

The meanings of "cubare" and "sub" are inverted. The output on the internet version of the Wiktionary is ok. The French version for Kobo has it wrong (used the generated version dated Nov 1st, 2021).

This happens also with the entry [Incube](https://fr.wiktionary.org/wiki/incube#%C3%89tymologie).

**Comment by BoboTiG** [comment]
I just checked and the output is correct. What you expect is actually the current output.

I ran that command to check:

```shell
$ python -m wikidict fr --check-word succube
```

and even adding the full `composé de` template data into a simple test return the correct data.

**Comment by BoboTiG** [comment]
I also checked on my Kobo, using the dictionary version from yesterday. All is alright :)

**Comment by BoboTiG** [comment]
I close the issue for now. Please reopen if needed.
