### ISSUE TITLE
New locale: DE

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1161]
My goal is to have (and share) a good German Wiktionary-based dictionary that displays well on small e-reader screens and is a little more informative (i.e., has word form, gender, hyphenation, IPA pronunciation, meaning, abbreviations, synonyms and examples). My main target format would be _StarDict_, with possible spinoff formats for Kobo _(dicthtml?)_, PocketBook (?) and Tolino _(quickdic)_.

Too bad _pyglossary_ doesn’t support R. Döffinger’s _quickdic_ format, because _Tolino_ devices use that, and we do have a rather large Tolino user base in Germany. Not everybody wants to jailbreak their device…

I currently use DE Wiktionary dumps and a rather brute-force [Rexx script](https://www.e-reader-forum.de/t/wiktionary-fuer-pocketbook.118669/page-6#post-2438607) to generate a Tabfile, which I then convert to StarDict and dicthtml formats. (See attached screenshots for how it looks in _GoldenDict_ on Linux.)

This is of course a flakey way to do it, and I’d prefer to collaborate with a more sound foundation like yours and integrate it there, also because yours gets auto-updated.

Unfortunately, the [HOWTO Add a New Locale](https://github.com/BoboTiG/ebook-reader-dict/wiki/HOWTO-Add-a-New-Locale) section in the wiki here isn’t too detailed, and I’d probably need quite a bit of help to get started. I’m especially unsure about the first two steps and the "Remove all data from the old lang."

So my questions are:

1. Would you be interested in a German dictionary that should look approximately like the screenshots show?
2. Is it possible to do, without investing too much time? (There’s a lot of other things I have to spend my time on, but I’d be willing to invest a substantial amount of time to get it started and polished a little.)
3. Is there any assistance possible in getting me set up to get the first steps done? I reckon that’d be to set up a working environment on my Linux Mint 20.3 machine, do a fork, and start adding a language "de".
4. Since I know almost nothing about Wiktionary’s internal structures, I fear the templates most. But having had a glance at your code, I think there is some expertise here…

**Screenshots:** This is how I envision it to look like. Users on [MobileRead](https://www.mobileread.com/) and the [German E-Reader Forum](https://www.e-reader-forum.de/) have been quite enthusiastic about the first version. Screenshots show the _StarDict_ version used by _GoldenDict_ on a Linux desktop.

![wiktionary - GoldenDict_001](https://user-images.githubusercontent.com/3706922/151312786-a8dff062-5ed1-41c7-8d71-4360cb341200.png)

![Wiktionarys - GoldenDict_001](https://user-images.githubusercontent.com/3706922/151312818-e7cc6803-0505-41fb-a2c1-52048fe13558.png)

![Auswahl_194](https://user-images.githubusercontent.com/3706922/151317275-a11cef77-383c-488d-9f0c-22fa276b99cd.png)

**Links** to what exists already:

- [Rexx script](https://kaufen-ist-toll.de/download/e-reader/wiktionary2txt.rex.zip) to convert wiktionary dump to tab file
- Resulting [StarDict DE dictionary](https://kaufen-ist-toll.de/download/e-reader/MCH%20DE-DE%20Stardict.zip)
- Resulting [dicthtml DE dictionary](https://kaufen-ist-toll.de/download/e-reader/dicthtml-de-de.zip)

**Comment by BoboTiG** [comment]
Hello @Moonbase59,

Thanks for your interest. Of course we can manage to add DE, it would be great!

I could add the locale, and all that is needed to support it. Then, you will have homeworks to add all "templates". By templates, we mean the formatting of Wiktionnary models. Let me start, and we will see later how to handle templates.

The project already create dictionnary files for StarDict, Kobo (dicthtml), and DictFile (.df).

Please note that the output you want is not currently supported, but we aim to improve that with #1149.

**Comment by Moonbase59** [comment]
> I could add the locale, and all that is needed to support it. Then, you will have homeworks to add all "templates". By templates, we mean the formatting of Wiktionnary models. Let me start, and we will see later how to handle templates.
> 
> The project already create dictionnary files for StarDict, Kobo (dicthtml), and DictFile (.df).
> 
Thanks, this sounds like a helpful start, appreciate it!

> Please note that the output you want is not currently supported, but we aim to improve that with #1149.
Well, we have to start _somewhere_. Improving can be done as a second step.

What is the default StarDict format the project generates? 2.4.2 or 3? Using HTML, i.e. `sametypesequence=h`?

**Comment by ilius** [comment]
> What is the default StarDict format the project generates? 2.4.2 or 3? Using HTML, i.e. sametypesequence=h?

StarDict 3.0.0
PyGlossary automatically detects html tags and switches to `sametypesequence=h`.

**Comment by Moonbase59** [comment]
Thanks for the info @ilius. Good to see you here. While we are at it: See any chance _pyglossary_ could support the `.quickdic` format at some point in time?

Reason being, R. Döffinger doesn’t seem to be interested in developing the generation tools much further, and the dicts generated by his tools have a lot of Wiktionary formatting junk now.

Unfortunately, the Tolino alliance decided to use that format for the _Tolino_ e-readers, of which we do have _a rather substantial user base_ here in Germany. Especially since Kobo abandoned the German market and leaves it to Tolino (both Kobo and Tolino hardware now from Rakuten, and they shared markets).

**Comment by ilius** [comment]
> See any chance pyglossary could support the .quickdic format at some point in time?

There is a lot of Java code, and very nested as well, to translate to Python.

And it won't work well for most input glossaries, because QuickDic seems to be a semi-structured format: definitions can be only one line, and no formatting / rich text, (in semantic dictionary terminology, seems like every "sense" is an entry).

While most glossaries have multi-line definitions, most likely HTML, but even in plaintext, all senses (forms of a word) combined in an entry.

So it doesn't seem worth the effort to be honest.

It would be best to write a Java tool (using QuickDict as library) that converts FreeDict or XDXF to QuickDic. But I'm not a Java developer.

We also discussed it in https://github.com/ilius/pyglossary/issues/314

**Comment by Moonbase59** [comment]
Yeah… I do see the problems, having actually looked at the code. It also seems to support from 1…n indexes (ok, good for translation dicts), but since I’m also not a Java dev, I can’t make much of the code.

_pyglossary_ just seemed to be the ideal place to handle it, because it’s widely used and actively developed (thanks for that!). Of course all this came up again, since _this_ project also seems an ideal place for uniform and current e-reader dictionaries.

Too bad all the Tolino users are left out, again, by what was probably a bad design decision.

**Comment by ilius** [comment]
Is this Tolino? https://mytolino.com/tolino-app/
Why would an ebook reader app use QuickDic format?

**Comment by Moonbase59** [comment]
Yes, that’s the app. But their main products are of course the hardware readers (closed Android and Tolino built-in as launcher, reading app and hardware control). I personally have a Tolino Vision 5 and a Tolino Tab 8" tablet (2014, the last one using open Android).

On the tablet, I use Librera and KOReader, both with StarDict. All other Tolino users aren’t that lucky—jailbreaking is quite hard and not everybody wants to do that. You can install your own hypenation library and (only) quickdic dictionaries, though. At least all of their hardware readers use quickdic, their support even directs you to https://github.com/rdoeffinger/Dictionary/releases/tag/v0.3-oldformat to get "new dictionaries". Sigh.

**Comment by ilius** [comment]
> https://de.wikipedia.org/wiki/Tolino
> From 2013 to early 2017, the technical marketing partner was Deutsche Telekom. Since the beginning of 2017, the devices have been further developed by the Japanese company Rakuten.

Interesting!

Does it have a popup dictionary that appears with selecting a phrase in a book?
And it shows several definitions of a word, like in QuickDic?

**Comment by Moonbase59** [comment]
Sorry @BoboTiG, we’re digressing a little… take it as discussing about future expansion. ;-)

@ilius: You can mark a word (_not_ a phrase although some are in the dict), then select "Look up" or "Translate". The actual screenshots from my Tolino Vision 5 (using the current v6 dicts) show that nothing has been updated in the dict generation software for a while—lots of Wiktionary templates go unhandled. It produces 13 pages (!) for the word "Wiktionary", rather unusable. Translations are better, but just so-so.

[Tolino dictionary screenshots.zip](https://github.com/BoboTiG/ebook-reader-dict/files/7952898/Tolino.dictionary.screenshots.zip)

**Comment by ilius** [comment]
@Moonbase59 Thanks for the info and screenshots.

I never saw that site. Still strange though.

BTW, QuickDic's license says it was a Google product between 2010 and 2011.
Google was using another name back then?

Also, you may want to suggest supporting [zim format](https://wiki.openzim.org/wiki/Main_Page) to QuickDic's author. There is a C++ library [libzim](https://github.com/openzim/libzim) that can be used in Java (with little effort I assume).
I think it's the best format for Wiktionary.
They release zim files for Wiktionary, Wikipedia and (I just realized) **a bunch of / every other Wikimedia website**! (monthly for Wiktionary and Wikipedia I think, not sure about the rest).
https://library.kiwix.org/?lang=deu

**Comment by Moonbase59** [comment]
Ah, now I see what you mean. Yes, there is still the [QickDic Android app](https://play.google.com/store/apps/details?id=de.reimardoeffinger.quickdic). They use v7 quickdic, I think. And yes, as far as I know Reimar Döffinger’s version is a fork of an older, discontinued project.

Tolino readers don’t use that app, just the v6 dictionaries (and their own code/API/whatever to read them in the Tolino apps). So we’re stuck with v6 quickdic for Tolino devices. Probably no one will convince the Tolino alliance to invest any efforts in developing new firmware for hundreds of thousands of devices out there. (Guesstimate, they don’t publish sales figures.)

**Comment by BoboTiG** [comment]
Preliminary support is done. A first version will be made available at https://github.com/BoboTiG/ebook-reader-dict/releases/tag/de in a couple of minutes.

**Comment by lasconic** [comment]
I have a couple of questions
* Is there any way to open a QuicDic file v6 without a Tolino device ? Or assuming one would write a V6 output in this project, how can one test it ?
* How does the stardict look for a german user ?   https://github.com/BoboTiG/ebook-reader-dict/releases/tag/de

**Comment by ilius** [comment]
> How does the stardict look for a german user ? https://github.com/BoboTiG/ebook-reader-dict/releases/tag/de

(I'm not German, but)
On GoldenDict it looks like Wiktionary!
Links in the **Contents** (TOC) don't work though.

![GoldenDict-Wiktionary-StarDict-German](https://user-images.githubusercontent.com/197648/151677936-59479e32-ccc8-4c9f-8fa3-46d6331bd144.png)

**Comment by ilius** [comment]
BTW, why don't you compress `.df` files in releases?

	35M	dict-de-de.df
	6.6M	dict-de-de.df.bz2
	9.1M	dict-de-de.df.gz

You can even directly convert from/to `.df.gz` or `.df.bz2` with PyGlossary.

**Comment by Moonbase59** [comment]
@BoboTiG: Thanks for this fast start! I’ll be checking the next days, just rebuilding some crashed machinery here…

**Comment by Moonbase59** [comment]
> I have a couple of questions
> 
>     * Is there any way to open a QuicDic file v6 without a Tolino device ? Or assuming one would write a V6 output in this project, how can one test it ?

Hmm, I never tried the [Tolino Android app](https://play.google.com/store/apps/details?id=com.mytolino.app), maybe that still works with v6 quickdic?

Maybe the original [QuickDic Android app](https://play.google.com/store/apps/details?id=de.reimardoeffinger.quickdic) also still reads v6 dictionaries?

Unfortunately, due to the Java overhead inside, the v6 files are substantially larger than the v7 files (which Tolinos can’t read).

>     * How does the stardict look for a german user ?   https://github.com/BoboTiG/ebook-reader-dict/releases/tag/de

_StarDicts_ I usually test on

- Linux GoldenDict (installed from the distro’s package repositories)
- Android [GoldenDict](https://play.google.com/store/apps/details?id=mobi.goldendict.android) (limit of 5 dicts in the [free version](https://play.google.com/store/apps/details?id=mobi.goldendict.android.free))
- Android [KOReader](https://github.com/koreader/koreader/releases)

**Comment by ilius** [comment]
I have collected [a list of apps for StarDict format here](https://github.com/ilius/pyglossary/blob/master/doc/p/stardict.md#dictionary-applicationstools).

**Comment by lasconic** [comment]
My question regarding the german stardict was more about the content (obvious missing words, obvious missing templates etc...). I ask both questions because I don't speak german and I don't have a tolino device :)

Regarding vertical spacing, I agree. The spacing is not idea even on Kobo. We could revisit our HTML a bit and remove a couple of line breaks maybe. @BoboTiG any thoughts ? worth another issue ?

**Comment by BoboTiG** [comment]
Let's open 2 issues: one for the vertical spacing to experiment new things, and one for the DictFile compression :+1:

**Comment by Moonbase59** [comment]
> My question regarding the german stardict was more about the content (obvious missing words, obvious missing templates etc...). I ask both questions because I don't speak german and I don't have a tolino device :)

I understand. Unfortunately, the dict generation doesn’t work from readable text files, but from chunks of the dumped Wiktionary data (when you run it, from `data/inputs/wikiSplit/de/DE.data.gz` and others. So no way to have a readable input wordlist…

And I don’t speak Java, so I’m unable to understand/change the DictionaryPC code. :-(

**Comment by Moonbase59** [comment]
@BoboTiG: Would this be the right time for me to start working on a fork? In order to prepare for PRs?

Man, I haven’t done all this GitHub stuff for a while now… ;-)

**Comment by BoboTiG** [comment]
@Moonbase59 yep :)

**Comment by Moonbase59** [comment]
@BoboTiG: Okay, forked and first small PR done (https://github.com/BoboTiG/ebook-reader-dict/pull/1176).

Next steps—and questions:

- How to generate working dicts locally, to test them?
- Can I use `git add .`, i.e. is your `.gitgnore` robust enough to exclude everything unwanted?
- Must I/Can I build new releases within my fork? Or is that done centrally on your side?

Thanks for helping me along!

**Comment by lasconic** [comment]
> * How to generate working dicts locally, to test them?

Running 
```
 python -m wikidict de
```
should generate the dictionary for german df, stardict and kobo format. 
It's a 4 steps process, and you can run each step separately if you want (see __main__.py)
```
 python -m wikidict de --download
 python -m wikidict de --parse 
 python -m wikidict de --render 
python -m wikidict de --convert 
```

> * Can I use `git add .`, i.e. is your `.gitgnore` robust enough to exclude everything unwanted?
Most of the time yes, but probably not if you store all sort of files in the root of the project. 

> * Must I/Can I build new releases within my fork? Or is that done centrally on your side?
Releases are done automatically by github workflow.

**Comment by Moonbase59** [comment]
Thanks!

Next question: Gender. In Germany, we have a legal "third gender" since 2018, to be used for transgender persons. It is usually abbreviated "d" (for "divers") but it seems it is not (yet?) used in the German Wiktionary. At least, I couldn’t find any entries.

For nouns, they currently only use variants/combinations of "f" (feminine), "m" (masculine), "n" (neuter) and "u" (utrum=common gender; used in Swedish: nouns are either neuter or utrum).

It follows that we (in general) should support the "u" in gender templates, but currently don’t have anything for Germany’s third "d" gender. Unfortunately I can’t readily find the comments in the PR where we talked about it, but I’d suggest going for a char class of `[fmnu]` in the regex and implement anything more whenever Wiktionary decides what to do about the "d" gender.

Objections?

**Comment by Moonbase59** [comment]
```bash
matthias@e6510:~/Projekte/ebook-reader-dict$ python3 -m wikidict de
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/__main__.py", line 42, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
```

Install `docopt` using `pip3`?

**Comment by BoboTiG** [comment]
> It follows that we (in general) should support the "u" in gender templates, but currently don’t have anything for Germany’s third "d" gender. Unfortunately I can’t readily find the comments in the PR where we talked about it, but I’d suggest going for a char class of `[fmnu]` in the regex and implement anything more whenever Wiktionary decides what to do about the "d" gender.

Have a look here: https://github.com/BoboTiG/ebook-reader-dict/blob/c770a1916a1488f57016837ebbd803358f011df7/wikidict/lang/de/__init__.py#L8

**Comment by BoboTiG** [comment]
@Moonbase59 do you think it is useful to let that issue open?

**Comment by Moonbase59** [comment]
This one? Depends on your workflow, I’ll agree with whatever you suggest. Probably not, since I’d be adding tons of other stuff here instead of opening separate issues…

Then again, it’s kind of documentation on how to add a new locale (although you did all the main work yet).

I would have asked about how to progress from here next, i.e. continue with

```bash
python3 -m wikidict de --find-templates
```
?

**Comment by BoboTiG** [comment]
Yes, and have a look at the `sections.txt` file. It contains all sections from all words (there will be a lot of noise, and you unlikely want to handle all of them). Pick interesting/pertinent ones and fill https://github.com/BoboTiG/ebook-reader-dict/blob/0bd2296e6ba146fbbe3a2af5dba96cdb651c5cec/wikidict/lang/de/__init__.py#L19-L22.

Then, run the same command again, and look at `templates.txt`. There, you will see all templates not handled (lot of noise too, lot of false positives).

It is a good habit to add a test when adding support for a new section or template.

**Comment by lasconic** [comment]
I don't speak german at all. But here is a list of templates that probably need to be handled https://de.wiktionary.org/wiki/Kategorie:Wiktionary:Markierung

**Comment by Moonbase59** [comment]
Thanks for that! I don’t really get started, because we find & fix so many other things… ;-)

I’m still also hoping I can start with some things I already seem to handle ok in my Rexx script. Just did a new run today, and its output still looks pretty decent.

For verification/comparison (d/l links stay the same):
[Kobo](https://kaufen-ist-toll.de/download/e-reader/dicthtml-de-de.zip) and [StarDict](https://kaufen-ist-toll.de/download/e-reader/MCH%20DE-DE%20Stardict.zip) version.

**Comment by lasconic** [comment]
The german wiktionary has a lot stuff like
![Capture 2022-02-04 à 21 15 44](https://user-images.githubusercontent.com/234271/152597328-b456ed65-dfde-4ea7-a8e2-6f8f694cf905.png)
what would be the expected result in a ebook reader dictionary (since we don't support links)

**Comment by Moonbase59** [comment]
You mean like in the entry for "[hämat-](https://de.wiktionary.org/wiki/h%C3%A4mat-)"?
Well, depends on how much we are into etymology. In this case, it says a word stems from Greek αἷμα (blood) and the romanisation/pronunciation of that, "haima".

I’d probably either ignore it, or put it in the etymology section (without the `→grc` pointer) and leave "Blut" in, so users could long-press "Blut" in the description and jump to the entry for it.

**Comment by BoboTiG** [comment]
English has consequent etymologies too.

Actually I thought about moving the etymology below definitions. Maybe we even talked about it with @lasconic, but I did not find any discussion.

I do not have a strong opinion, and it could be easy to change that for the Kobo.

**Comment by lasconic** [comment]
I don't remember this discussion but we might want to see if https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details is supported on Kobo. Kind of related to https://github.com/BoboTiG/ebook-reader-dict/issues/1172 ?

**Comment by Moonbase59** [comment]
Using `<details>` has been discussed a lot on e-reader forums, because it could be rather nice to have but support for it in e-reader rendering software seems flakey at best.

Maybe best to (currently) _not_ use it and just really put etymology after the definitions for now? (I will eventually nag you to include more stuff anyway, hee hee. But one step after the other.)

**Comment by lasconic** [comment]
I implemented a few german templates and file issues for the ones I can't implement even with Google Translate. You can find them with the locale:Deutsch label https://github.com/BoboTiG/ebook-reader-dict/issues?q=is%3Aissue+is%3Aopen+label%3Alocale%3ADeutsch.

I catched non implemented template with 
```
print(f"[{word}] --- {template[0]}")
```
at the end of de last_template_handler function and ran a script to find the number of times the template is used.

So here is a list of german templates needing our attention (and the number of times they appear in the sections we are interested in)

Hebr,326
lang,134
Bibel,131
Lautschrift,102
Arab,80
Ref-dejure,51
Üt?,46
Wikipedia,39
noredlink,19
Farsi,16
w,14
Audio,13
Üxx5,10
Pl.,9
la,8
Gen.,7
mf,6
NNBSP,6
Herkunft,6
en,6
fr,6
gmh,6
IPA,5
grc,5
veraltet,5
Benutzer,5
Taste,5
vatd.,5
goh,4
it,4
germ.,4
IA,4
vgl.,4
linkFr,4
Ref-Duden,4
Bpur,4
Dativ,4
İA,3
DMG,3
nds,3
ISO 9,3
Fremdsprachige Beispiele,3
!,3
he,3
linkLa,3
Beispiele,3
vul.,3
Genitiv,3
da,2
ang,2
Literatur,2
Üxx4?,2
Pl.2,2
Anker,2
ar,2
Urdu,2
nl,2
akk,2
IPA-Text,2
hi,1
sa,1
linkLat,1
Koptisch,1
Color,1
sv,1
pl,1
haw,1
Ref-behindthename,1
nf,1
yi,1
pdc,1
(R),1
ru,1
ü,1
gehoben,1
Ü?,1
Plainlink,1
QS Bedeutung,1
es,1
ch,1
Ref-DWDS,1
MZ,1
Lit-Bahlow,1
tpw,1
gn,1
Beispiele fehlen,1
Herkunft fehlt,1
erweitern,1
tr,1
sw,1
Unicode,1
Hebräische Schrift,1
Paschto,1
Sinnverwandte Wörter,1
Kontamination,1
sux,1
arc,1
Pl.1,1
Hintergrundfarbe,1
Part.,1
Prät.,1
R,1
Ref-Bibel,1
Ref-Adelung,1
Akkusativ,1
polytonisch,1
Unterbegriffe,1
Kintransitiv,1
el,1
Abkürzungen,1
Synonyme,1
CH&LI,1
Übersetzungen,1
non,1
lt,1
got,1

**Comment by Moonbase59** [comment]
Thanks for your help! I’ll try to work on the templates soon. Is there some definite place in the Wiktionaries where they elaborate on templates used? I seem never be able to find that…

**Comment by lasconic** [comment]
You mean all the templates used in the whole wiktionary for a given locale ? I don't know.
For de, I found 
* https://de.wiktionary.org/wiki/Kategorie:Wiktionary:Vorlage (but it doesn't say anything about the usage, and it's a manual category)
* https://de.wiktionary.org/wiki/Spezial:Alle_Seiten?from=&to=&namespace=10 (but same, it doesn't say anything about usage, but one can visit each page and see the pages where the templates is used).

In any case, we don't need to implement all templates but just the ones used in the sections we render.

**Comment by Moonbase59** [comment]
Do we have to _exclude_ those we _don’t_ (currently) use?

**Comment by lasconic** [comment]
> Thanks! Do we have to _exclude_ those we _don’t_ (currently) use?

There is no need to implement the ones we don't use for now. We all have limited time, so let's focus on the most impactful ones ?

---

I just merged a PR with support of more templates.
The gist is updated: https://gist.github.com/lasconic/7eac492986876dc87b9381e788d0aab3
Templates to support : 116 --> 66
Number of times the templates are used : 1302 --> 818

**Comment by tjaderxyz** [comment]
I have been using this dictionary on KOReader and it's been serving me well, thanks for making it available!

The main problem I have so far is the lack of inflected forms. For example, it has an entry for the verb _tragen_, but not for the conjugated form _trage_, and it has an entry for the adjective _rot_, but not for the declined form _rote_.

In both cases there's an entry for the inflected form in Wiktionary, saying it's an inflected form. In my opinion the ideal result would be for the inflected form to lead directly to the main form's definition, but just showing the inflected form definition would already be better than the current behaviour.

I took a look at the code but couldn't figure out either why the inflected forms are being dropped nor how to make one word lead to another word's definition, but I'm not too familiar with how the generation works overall.

**Comment by lasconic** [comment]
Thank you for your feedback. Since you use KOreader, you use the stardict format. Right now I'm not sure if "variants" will be carry on when we convert from Kobo format to Stardict but in any case, variants are not implemented in German yet.
If they would be implemented the same way than for French and Spanish it would work the way you describe.
You can see how I did it in spanish here : https://github.com/BoboTiG/ebook-reader-dict/pull/1227

Reading https://github.com/ilius/pyglossary/blob/master/pyglossary/plugins/ebook_kobo_dictfile.py it seems variants are read from Kobo file, so it could be that they work in stardict.

**Comment by tjaderxyz** [comment]
I tested the Spanish dictionary in KOReader and it works as expected, both *rojo* and *roja* bring the definition for *rojo*.

Thanks for pointing to the Spanish implementation commit, I'll study it when I have some time and try to implement something similar for German (if no one gets to it before me).

**Comment by BoboTiG** [comment]
I close that one as the primary subject is now well handled :)
Thanks everyone :champagne:
