### ISSUE TITLE
Feature request: Add (Wiktionary dump) date to StarDict, possibly others

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1162]
I usually add the date of the Wiktionary dump to the _StarDict_ `.ifo` file, in the format `date=2022-01-27`. Maybe this is also feasible for other formats. It helps enormously to differentiate between dictionary versions.

Could we add that, so the project auto-generates it?

Should be easy to add this to `convert.py`, I’d think.

If you have objections using the dump date as date and prefer using the actual _generation date_, we could instead add some text to the `description` field, like maybe: `(based on DE Wiktionary as of 2022-01-27)`.

**Comment by BoboTiG** [comment]
Actually, we keep track of both dates.

For Kobo, we add a `INSTALL` file in the `dicthtml-$LOCALE-$LOCALE.zip` file, and it contains the Wiktionnary dump + file create dates.

We could add more details in the `.ifo` file too, let me check that.

**Comment by BoboTiG** [comment]
:heavy_check_mark: :)

**Comment by Moonbase59** [comment]
Real useful for people to check if they want an update, thanks!
