### ISSUE TITLE
Reduce vertical space of the whole definition

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1172]
In https://github.com/BoboTiG/ebook-reader-dict/issues/1161#issuecomment-1025090041 we discussed the fact that a whole word definition takes quite some vertical space. Let's see if we can make it smaller without compromise the readability

**Comment by Moonbase59** [comment]
I haven’t had time to delve deeper into the code yet, but I’d also suggest to use some kind of **output templates**, so a uniform appearance can be reached (that’s something I really like in this project), and a developer could _include/exclude_ more or less information, and _influence the presentation_ of elements (sequence, emphasis, maybe coloring even).

This should also make it easier to generate a non-HTML (text-only) version of the outputs, while keeping uniformity, for those sad devices/apps that can’t (yet) cope with HTML output. Like _Foliate_ which currently only handles StarDict’s "m" format.

All this could be a good step forward in making something that more closely resembles my Rexx script example outputs. (Having hyphenation, pronunciation, etymology, abbreviations, synonyms and examples, see https://github.com/BoboTiG/ebook-reader-dict/issues/1161#issue-1115876115.)

**Comment by BoboTiG** [comment]
Actually we are using a template: https://github.com/BoboTiG/ebook-reader-dict/blob/7d987175f2b9cafdc3aed519a17468df01da7e86/wikidict/constants.py#L20-L31

Maybe is it a good time to move to a real template engine like Jinja2?

**Comment by Moonbase59** [comment]
Unsure about _Jinja2_, but a definite **YES**. Maybe a first step could be to remove above template from code and use a per-language, easily editable _file_ instead? And—for now—stick with using "kinda" HTML and moustache-type variable substitution?

Reason being, _part-of-speech_, _cases_ and _inflections_ have _big differences_ between languages. I really wish we had one "world language"… Would make communicating so much easier. Sigh.

**Comment by lasconic** [comment]
To keep the discussion alive, here is a screenshot of the default Spanish dictionary and ours on Kobo. See how compact the default spanish dictionary is.


![screen_008](https://user-images.githubusercontent.com/234271/153602209-c206af6d-f43d-4208-a1e3-a7c9ceb97f72.png)
![screen_009](https://user-images.githubusercontent.com/234271/153602220-2ac83d7d-42d7-4b4c-a8e9-92f070e407f3.png)

**Comment by Moonbase59** [comment]
@lasconic: I love compact, due to the restricted screen estate on hardware readers. Although the shown Spanish example _should_ use a line break before #1.

@ilius: I also thought about that, but we’d need our own numbering, so no predefined bullets or numbers. Reason: For later expansion. Numbers in Wiktionary usually refer to "meaning #x", so you can have none, one or multiple same-numbered examples:

![Integrationsproblem - GoldenDict_003](https://user-images.githubusercontent.com/3706922/153780665-295ed021-b784-45bf-9849-3829e85de8b7.png)

Many examples (»Beispiele:«) for meanings (»Bedeutungen:«) #1 and #2 here.

**Comment by ilius** [comment]
@Moonbase59 Interesting!
In FreeDict-based dictionaries (converted by PyGlossary), there is an "Examples" section under each meaning(aka "sense"), which becomes a list if there are more than one examples. This introduces another problem: list within list.
And if there are too many examples for first few meanings, you may need to scroll down to see all meanings and find the one you are looking for. Although it does make it more organized. Just something to think about.

**Comment by Moonbase59** [comment]
Oh yes, I couldn’t find a word offhand, but I know we also have sub-lists somewhere like "sense" 1a, 1b, 1c and such. Here is another one, "Linux", with meanings (senses) 1–4, and synonyms, examples and even etymology referencing these numbers (top=mine, bottom=this project’s):

![Linux - GoldenDict_001](https://user-images.githubusercontent.com/3706922/153781828-a5d29e7d-8f63-47e7-896e-3ce550f7bd63.png)

**Comment by BoboTiG** [comment]
Closing that issue since the primary request is done, or not doable.
