### ISSUE TITLE
Compress df file output

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1173]
See https://github.com/BoboTiG/ebook-reader-dict/issues/1161#issuecomment-1024989236

* Who uses the df file ? 
* Do they use it directly in a device that couldn't use the compressed version ?
* Can these users handle the decompression process ?

**Comment by Moonbase59** [comment]
I don’t have access to a Kobo. Maybe we can gather some info on that on [MobileRead](https://www.mobileread.com/forums/) (English) and [E-Reader Forum](https://www.e-reader-forum.de/) (German)?

These two seem to be the most frequented forums for people who wish to optimize their devices. Both also have Kobo subforums (is `.df` a Kobo-only format?).

**Comment by lasconic** [comment]
df is not a "kobo format", meaning Kobo ereaders can't read it. It's only an input format for other scripts I believe. It is a text file indeed, and I guess it's only used by users as an input in pyglossary to generate other formats (like we do for stardict).

**Comment by BoboTiG** [comment]
@lasconic is totally right. We introduced the DictFile format only to be able to generate the StarDict, because we could not use "the dicthtml" Kobo file as input.

We could compress that file if PyGlossary can read it, it will save a good amount of bytes.
