### ISSUE TITLE
Compress StarDict 'dict-data.dict' to 'dict-data.dict.dz'

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1180]
Most readers should be able to read '.dz' (compressed dictionaries) files nowadays.

I suggest we also compress the StarDict `dict-data.dict` files into `dict-data.dict.dz`. Upon successful compression the `.dict` file can be removed. Saves much space.

I use `dictzip` for that. On Debian derivatives, it can usually be got, together with `dictunzip` and `dictzcat`, from the package repos, using:

```bash
sudo apt install dictzip
```

If invoked without other parameters, `dictzip` will remove the originating `.dict` file, so the following command should be enough:

```bash
dictzip dict-data.dict
```
(from within the `data/XX` folder)

**Comment by BoboTiG** [comment]
I am not sure it is needed as those files are only used internally, and not sent/stored anywhere.

What is your use case?

**Comment by Moonbase59** [comment]
The generated StarDict dictionaries. E-Readers don’t usually have much free space, and the downloading would also be faster. The current EN StarDict compresses 108.5 MB into 30.6 MB this way—a big improvement.

Due to the special `.dz` format, a StarDict reader doesn’t have to unpack the whole `.dict.dz` file but can access the dictionary directly in chunks, ~57 usable KB if I remember correctly.

**Comment by lasconic** [comment]
If it's only for the StarDict output, we could probably call pyglossary with the relevant option to get a dict.dz file instead .dict.

https://github.com/ilius/pyglossary/blob/master/doc/p/stardict.md

**Comment by Moonbase59** [comment]
@lasconic: A good idea, I almost forgot about that option. I seem to remember you’d have to install `dictzip` manually so `pyglossary` could use it, couldn’t find pyglossary’s doc on that quickly. Would be important for the automated workflow, though.

**Comment by lasconic** [comment]
You are right : https://github.com/ilius/pyglossary/issues/338

**Comment by BoboTiG** [comment]
Oh OK I get it, I thought shipping a Zip'ed StarDict was enough. We could save even more momory by also compressing the `data-info.dict`. Thanks for the explanations @Moonbase59.

Do you know how good is it supported by eBook readers?

About compressing the `res/` folder, it is already quite optimal: files are stored using the deflate algorithm, and compressing a potential `res.zip` (images already compressed) into the final Zip'ed dict will not save place (and it would actually need more CPU resources on eReaders to decompress them).

We could simply GZip `data-info.dict`, no need for an external tool, I guess.
