### ISSUE TITLE
Incorrect br tag in output

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1184]
```html
<w>
  <p><a name="Wiktionary" /><b>Wiktionary</b> \ˈwɪkʃən(ə)ɹi\, \ˈwɪkʃənɹɪ\<br /><br />
  <p>Blend of <i>wiki</i>&nbsp;+&nbsp;<i>dictionary</i>.</p></br>
  <ol>
    <li>A collaborative project run by the Wikimedia Foundation to produce a free and complete dictionary in every language; the dictionaries, collectively, produced by that project.</li>
    <li>A particular version of this dictionary project, written in a certain language, such as the English-language Wiktionary (often known simply as the English Wiktionary).</li>
  </ol>
  </p>
</w>
```

See the third line, it should be <br /> and not </br>

The bad `</br>` is  here: https://github.com/BoboTiG/ebook-reader-dict/blob/9a02781b5f0840520aad2c9def08ba87137bac1c/wikidict/convert.py#L75

First reported here https://github.com/BoboTiG/ebook-reader-dict/issues/1174#issuecomment-1026698982

**Comment by lasconic** [comment]
@BoboTiG You are right, the HTML parser is flexible.

Current with wrong br:
![screen_001](https://user-images.githubusercontent.com/234271/151977808-025908df-c599-4077-9162-e441866cd22d.png)


With a correct <br />
![screen_002](https://user-images.githubusercontent.com/234271/151977841-e9d3bcfb-7154-4995-b69d-7674b2b39977.png)


Without br at all
![screen_003](https://user-images.githubusercontent.com/234271/151977880-59017de7-97f5-45dc-8ce4-456ddeb1f8fc.png)

**Comment by lasconic** [comment]
I'll just fix it.

**Comment by BoboTiG** [comment]
Great, thanks! :muscle:
