### ISSUE TITLE
[DE] Missing a right curly bracket?

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1192]
https://github.com/BoboTiG/ebook-reader-dict/blob/1204f5ac5ceb8d60df5806511602fd6497a79499/wikidict/lang/de/__init__.py#L21

Sure about this? Or do we miss the 2nd right curly bracket?
(Just doing a test run)

**Comment by lasconic** [comment]
Pretty sure it's used with "startswith"

**Comment by BoboTiG** [comment]
@lasconic is right. So we use the minimal string that would match.
