### ISSUE TITLE
Add website in StarDict ifo file

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1193]
I think more people should be aware of this project. I happen to know almost _any_ _StarDict_ user opens their `.ifo` file and peeks into it.

The StarDict [documentation](https://github.com/huzheng001/stardict-3/blob/96b96d89eab5f0ad9246c2569a807d6d7982aa84/dict/doc/StarDictFileFormat#L82) says we can also have a `website=` entry here. How about putting

- this repo’s main page, or
- the actual download location for the dictionary

into that field?

:wink:

**Comment by BoboTiG** [comment]
Good idea :+1: :)
