### ISSUE TITLE
dictzip on MacOS

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1205]
Nobody's perfect. My dev env is on MacOS. 

Anyone knows how to install dictzip ? (or should I compile it... ?)

**Comment by Moonbase59** [comment]
> Nobody's perfect. My dev env is on MacOS.

Thanks for the grin of the day @lasconic :-)

Probably compile? Then again, I found a list of dictzip repos in different languages, but I don’t know how good/compatible/fast these are: https://github.com/dictzip

**Comment by lasconic** [comment]
```
brew install dict
```

**Comment by Moonbase59** [comment]
Homebrew is one best inventions ever, for Macs!
