### ISSUE TITLE
[ES] Add variant for verbs and adjectives

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1223]
I just started to read a book in Spanish. Perfect opportunity to give some feedback.

1. When I click on "apropiada" directly from the book I got a hit in the default dictionary but not in ours. The dictionary says (in french) : "Votre recherche de "apropiada" ne correspond à aucun terme dans le dictionnaire. La correspondance la plus proche est "apropiado". (you search doesn't match any word in the dictionnary, the closest is "apropiado") and it displays "apropiada". Maybe we could add some variant so we get a direct match ?

2. "asoleada": no hit in our dictionary, a noun in the default one which is not what I was looking for.

**Comment by lasconic** [comment]
It's not only for adjectives...

"labores", el plural de [labor](https://es.wiktionary.org/wiki/labor) is not found in the default dictionary or in ours..

**Comment by BoboTiG** [comment]
We improved a lot the french dictionary, now we see other locales are not at the same level :)
Let's add whatever it needs :+1:

**Comment by lasconic** [comment]
One thing I found out thought. The Spanish wiktionary seems under developed compared to the English one (of course) but also the French one. Several missing words (compared to the default kobo one). Not sure we can use the same tricks we used for french.

Also I'm not sure if it's worth to make the code more complex before tackling https://github.com/BoboTiG/ebook-reader-dict/issues/1149 and before a some busy weeks for me. 

I will push whatever I have on my fork.

**Comment by lasconic** [comment]
While at it, I'm looking into verbs too. Do we know if there is a limit of variants per word ?

**Comment by Moonbase59** [comment]
A more general question is also: How do we want to handle these cases? Separate entries with a link to the base form (_can_ we link within the dict?) or multiple variants in _one_ entry?

In the German dictionaries, we have _both_:

### One entry with base form reference

Looking up "angemessen" (≈"apropiado"), I find a lot of _suggestions_ (probably done by GoldenDict’s fuzzy search, see at the left) but only _one_ entry, having a link to the base form ("Grundformverweis Konj: anmessen"). On many readers, I can then tap on the word "anmessen" in the dictionary entry and it will jump to the base form, even without it being an actual link. (Can the Kobos do that?)

![angemessen - GoldenDict_001](https://user-images.githubusercontent.com/3706922/154459096-a501595e-3774-4b37-b06a-e3a345d22eb3.png)

### Multiple variants in one entry

Looking up the word "Arbeit" (="work"), I get multiple variants in one entry: "Arbeit" (noun), "arbeit" (conjugated form of "arbeiten"), "Arbeiten" (declined noun "Arbeit"), "arbeiten" (verb).

![arbeit - GoldenDict_001](https://user-images.githubusercontent.com/3706922/154461861-ca89fedb-c52c-400c-b99d-c9e46d718a7a.png)

**Comment by lasconic** [comment]
So far "variants" feature is only implemented in the FR dictionary. So what you see in the first case is probably Golden Dict (assuming what we see here is related to this project and not yours). 

Kobo has a click to word feature indeed.

The current implementation in this project, in french, redirects to the infinitive verb when one clicks on a conjugated form in a book and does it directly. Same for irregular plural. Clicking on "vitaux" should display "vital". Clicking on "aimait" should display "aimer".

I propose to do the same in Spanish. Clicking on "apropiada" should display "apropiado" directly and clicking on "amando" should display "amar". 

According to me there is little value in displaying that "apropiada" is the feminine form of "apropiado" and then require a click on apropiado to know the actual meaning of the word.

Also "variant" has a particular meaning for us/kobo. When you tap or search a "variant" the definition of another word is displayed. That's it. So your second case has not much to do with variant. On Kobo, if you search for "Albeit" you will get the meaning of "Albeit" and not "arbeit". If "variant" is implemented the same in german than in french (and in spanish with this proposal) then searching for "arbeit" would display "arbeinten" only and "Arbeinten" would display "Arbeit".
That being said, variant is a long term problem in german since there are still > 100 templates to cover :)

**Comment by lasconic** [comment]
Some problematic cases in spanish:

* https://es.wiktionary.org/w/index.php?title=gastada could redirect to "gastado" like "apropiada" redirects to "apropiado" but [gastado](https://es.wiktionary.org/w/index.php?title=gastado) should redirect to "gastar" since there is no good meaning. We don't have this double redirection implemented even in french.
