### ISSUE TITLE
[ES] word "ruego" is empty and should have one definition

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1229]
- Wiktionary page: https://es.wiktionary.org/w/index.php?title=ruego

As you can see there is a definition and we don't display it.

```
$python -m wikidict es --get-word=ruego
ruego   

```

**Comment by BoboTiG** [comment]
It's because the wikicode doesn't contain the `== {{lengua|es}} ==` head section. Instead, it uses thr [`ES`](https://es.wiktionary.org/wiki/Plantilla:ES) model.
