### ISSUE TITLE
Add migaku compatible dictionary files

### ISSUE THREAD

**Issue by perlop** [BoboTiG/ebook-reader-dict#1235]
Expected: Any change you can add zip files in json or yomichan format that are compatible with migaku? I would like to use these files with migaku browser extension.

Model link, if any: 
Here is info on migaku json format:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/14243372/156143796-d596fd41-de1a-40be-83a2-ef865119ed67.png">

**Comment by lasconic** [comment]
Maybe better suited for [pyglossary](https://github.com/ilius/pyglossary)?  We use pyglossary to convert to other formats.
Do you have more documentation on the format ?
