### ISSUE TITLE
[FR] Support 'Diagramme d'échecs' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1266]
- Wiktionary page: https://fr.wiktionary.org/wiki/opposition

**Comment by lasconic** [comment]
Or be brave and https://python-chess.readthedocs.io/en/latest/svg.html

**Comment by lasconic** [comment]
python-chess might miss some features. 
* The footer
* Displaying "o"  as in https://fr.wiktionary.org/wiki/contr%C3%B4ler

Except this, it supports fen notation, and via `set_piece_map` we should be able to implement the wiktionary notation.

**Comment by BoboTiG** [comment]
Nickel :ok_hand:

**Comment by lasconic** [comment]
"opposition" is the only word triggering the template not supported error because the template is not on a single line. I fixed it on wiktionary and the warning is gone... Maybe it's a too quick fix ?

**Comment by lasconic** [comment]
If we would decide to include this single line, we can test all words with chess diagram with python -m wikidict fr --gen-dict="opposition,contrôler,contre-gambit,gambit en second,mat de l’escalier,mat des Arabes,mat des épaulettes,mat du guéridon,mat du lion" --output=test_wik 
```
$ mkdir test_wik
$ python -m wikidict fr --gen-dict="opposition,contrôler,contre-gambit,gambit en second,mat de l’escalier,mat des Arabes,mat des épaulettes,mat du guéridon,mat du lion" --output=test_wik
```

**Comment by BoboTiG** [comment]
Let's say we want to move forward, and display nice chess board for those words? :)
Do you already have some code, or should I start from scratch if you have no free time?

**Comment by lasconic** [comment]
I don't have code but before starting, make sure the diagram wiki code is really in a part of the word we parse. I don't remember the detail but I believe we don't get this template often even fir the words that contain it.

**Comment by BoboTiG** [comment]
Well, you are right: none of the words are missing such template because it is simply outside of sections we are interested in. I'll close the issue then :)
