### ISSUE TITLE
New locale: Russian 

### ISSUE THREAD

**Issue by victornove** [BoboTiG/ebook-reader-dict#1270]
Hello,

I stumbled across this as i was trying to find a way to parse the wiktionary, and it is super useful, thanks!

I have a project which needs english, french, german, spanish and russian word definitions (I use get-word mostly). So I added russian as best I could.

I'm not sure my code is very kosher (and I could not run find-templates as it seems to crash with memory errors.), but if you are interested in a russian locale I'd be happy to work on it so it could be useful. 

Thanks

**Comment by BoboTiG** [comment]
Hey @victornove,

Of course we are interested in the Russian locale :)

There was a previous request, but as I said in https://github.com/BoboTiG/ebook-reader-dict/issues/882#issuecomment-850847547 I am completely useless here.

Let's open a pull request so that we can help you out.

**Comment by victornove** [comment]
Ok, I opened a pull request.

In hindsight, since I only use the get-word function (and I injected POS into the definition) I might have broken some things for your dictionaries? But that is easy to turn off. I also completely ignored the testing part :D

**Comment by BoboTiG** [comment]
Done with #1271. :heart:
