### ISSUE TITLE
Separate out multiple etymologies or parts of speech in the same word

### ISSUE THREAD

**Issue by 1over137** [BoboTiG/ebook-reader-dict#1294]
Thanks for this project!

I'm the author of [VocabSieve](https://github.com/FreeLanguageTools/vocabsieve), and I am fairly certain that a few users of my tool are using your dictionaries.

I noticed that these dictionaries combine all the meanings into one single long list. This is not the easiest to read when the word has multiple definitions.

For example, with the word `extent`, your dictionary gives the following:
--
\ɪkˈstɛnt\ 
From Middle English *extente*, from Anglo-Norman *extente* and Old French *estente* (“valuation of land, stretch of land”), from *estendre*, *extendre* (“extend”) (or from Latin *extentus*), from Latin *extendere* (See **extend**.)
1. A range of values or locations.
2. The space, area, volume, etc., to which something extends.
3. *(computing)* A contiguous area of storage in a file system.
4. The valuation of property.
5. *(law)* A writ directing the sheriff to seize the property of a debtor, for the recovery of debts of record due to the Crown.
6. *(obsolete)* Extended.

It is not obvious here that the 6th definition is in a separate part of speech (adjective)

For reference, this is what the built-in Wiktionary query feature produces:
--

*Noun*  
1. A range of values or locations.  
2. The space, area, volume, etc., to which something extends.  
3. A contiguous area of storage in a file system.  
4. The valuation of property.  
5. A writ directing the sheriff to seize the property of a debtor, for the recovery of debts of record due to the Crown.  
*Adjective*  
1. Extended.

Also, could you also release a version of each dictionary that does not include the etymology? They can take up a lot of space, and my tool is generally expected to be used with brief definitions. It does have a feature to simply strip out the top lines, but it's not that reliable.

This is what the interface looks like:
![20220513-194715](https://user-images.githubusercontent.com/22680475/168402078-80c8ed74-ffa7-4905-a8fa-00569bc579ae.png)

**Comment by BoboTiG** [comment]
Hey @1over137,

About POS, please refer to #1149, it will be the main issue to follow.

About removing the etymology, we do not plan to generate more dictionaries, but what can be done is to ease stripping it out.
A quick idea: if we added an HTML ID, like `<p id="etym">...</p>`, would it help on your side?

**Comment by BoboTiG** [comment]
We now generate etymology-free dictionaries following #1440.

The next on #1149 :)
