### ISSUE TITLE
Fix data auto-update scripts with double quotes

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1347]
4a20f9bbf6ae47ee4351ffc64ab6cd2928c527b7 breaks python file: it now contains syntax errors like

```python
{
    "currency": "<span style="color:red;"><b>deprecated label</b></span>",
}
```

**Comment by BoboTiG** [comment]
That seems weird to display "deprecated label" in red color, at least the real label should be displayed too. Maybe is there more than double quote handling to check :thinking:

**Comment by lasconic** [comment]
I would propose to ignore deprecated labels and not include them at all.
