### ISSUE TITLE
Unit test failing on Mac Apple Silicon

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1390]
python -m pytest tests/test_3_convert.py::test_simple is failing

A gè.html file is expected but there is none in the zip file. The tests seems to run ok on github/linux and I believe it worked on a mac intel. I tracked down the problem to `guess_prefix` where "gèlent" or whatever is read from the json file containing "ge\u0300lent" gives a prefix `ge` instead of `gè`.

I can't find the root cause. Any idea @BoboTiG  ?

**Comment by BoboTiG** [comment]
No, I've no idea for now.

We should try to isolate if it is a specific Python version (or range of versions) that has a different behaviour. Same for Intel versus Silicon.

I can give a try today, using a custom Github Action on that repository. Maybe should we extend that Action to Windows too, just to be sure. And the test should run only `tests/tests_N_action.py` I guess.

**Comment by BoboTiG** [comment]
Hmm there is no ARM runners for GitHub Actions. And I do not have such a machine anymore, so I can't really help :thinking:
It should have failed sooner, correct? Could you try older Python versions? If we can at least knwo when it started to fail, I could give a hand bissecting CPython commits (given it would be a change done there).

**Comment by lasconic** [comment]
I have this new mac for a month or so and I believe it always failed. I was running Python 3.9.13 and had the problem. I update to 3.10.6 to be a on par with the CI but I still have the problem.

I wonder if it doesn't come from the way we store unicode data in JSON. Maybe just doing dump() is not enough to be 100% cross platform ?

**Comment by BoboTiG** [comment]
Can you share a JSON file containing the problematic data? And how to produce it too, so that we can try on other platforms.

**Comment by BoboTiG** [comment]
Can you give a try using `dumps(..., ensure_ascii=False`?

**Comment by lasconic** [comment]
The problem is reading  data-20201217.json attached. [data-20201217.json.zip](https://github.com/BoboTiG/ebook-reader-dict/files/9560895/data-20201217.json.zip)

Here is test code. Running it will display "ge" for "gèlent"

```
import json
from pathlib import Path
from typing import Dict

file = Path("./data-20201217.json")
with file.open(encoding="utf-8") as fh:
   words: Dict[str, str] = json.load(fh)

for word in words:
   print(word)
   print(f" {word[:2]}")
```

**Comment by lasconic** [comment]
data-20201217.json contains "ge\u0300lent"

what about yours ? Does it contains "g\u00e8lent" ?

**Comment by lasconic** [comment]
I see no difference with `ensure_ascii=False` in both `parse` and `render`. Except that it hides the problem even more. With a text editor, I read "gèlent" in the json file but `word[:2]}` is still "ge"
Now I just realize that "éperon" is not a problem...

**Comment by lasconic** [comment]
Ok I see the problem in the XML file we create a in craft_data too. I can't find "gèlent" with a search in visual studio. So it has to do with the decoding of the filename. I believe I copied my repo from a Mac Intel instead of doing a clean checkout. Let's see if I start from scratch...

**Comment by lasconic** [comment]
And it also works with `ensure_ascii=False`.
Sorry for the noise...

**Comment by BoboTiG** [comment]
Ah! Glad it is not an issue on our end :)
