### ISSUE TITLE
[EL] Fix gender name, add template

### ISSUE THREAD

**Issue by chopinesque** [BoboTiG/ebook-reader-dict#1407]
I have made some changes fixing the name for m gender and adding an extra template that was missing (κτεπε → κατʼ επέκταση), https://el.wiktionary.org/wiki/%CE%B8%CF%81%CF%8C%CE%BD%CE%BF%CF%82

https://github.com/BoboTiG/ebook-reader-dict/pull/1406

**Comment by BoboTiG** [comment]
Thanks @chopinesque.
