### ISSUE TITLE
[FR] Add support for the 'ar-terme' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1411]
- Wiktionary page: https://fr.wiktionary.org/wiki/Muad-Dib
- Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:ar-terme

**Comment by lasconic** [comment]
Here we need to port https://fr.wiktionary.org/wiki/Module:ar-pronunciation

**Comment by lasconic** [comment]
And it includes https://fr.wiktionary.org/wiki/Module:ar-translit

Piouff...

**Comment by BoboTiG** [comment]
> Piouff...

:100: ^^

On the other hand, when all arabic templates will be done, I think the French dictionary will be almot 100% supported. :medal_sports:

**Comment by lasconic** [comment]
Both modules are imported from en wiktionary and they have unit tests there
https://en.wiktionary.org/wiki/Module:ar-translit/testcases

**Comment by lasconic** [comment]
The problem with the testcases is that they are on the english wiktionary and so they pass with the code of the module running on en.wiktionary.org... The fr.wiktionary editors copied the english modules at one given time and then they edited them, and the ones on en.wiktionary.org evolved... Now, the french and the english ones give different results and so the french module would not pass the english test cases. 

For example:
On fr.wiktionary.org
```
{{ar-IPA|tr=yawmu l-iṯnayni}}
```
is rendered
```
jaw.mu l.iθ.naj.ni
```

the same wikicode is rendered on en.wiktionary.org is rendered:
```
/jaw.mu liθ.naj.ni/
```

**Comment by lasconic** [comment]
Another fun example :)
At one given moment, after the french editors copied it, the english module ar-pronunciation changed the sign for [pharyngealization](https://en.wiktionary.org/wiki/pharyngealization) (or whatever) from https://en.wiktionary.org/wiki/ˁ to https://en.wiktionary.org/wiki/ˤ
And so the english tests will not pass for the french module...

**Comment by lasconic** [comment]
The **4** words with ar-terme :)

abelmeluch
Muad-Dib
adobe
qasida

**Comment by BoboTiG** [comment]
We could just ignore the template given the words count for the required work.

**Comment by lasconic** [comment]
As promised a short feedback on chatGPT for Lua to Python 3 conversion : It kind of work but unfortunately just kind of, so you spend quite some time debugging because chatGPT decided to make a subtile change in the code. Also, there is a limit to the length you can send and receive and so it's inconvenient. This last point might be solved with the premium subscribtion or using the GPT3 API directly (?). It was fun to try, and when it works it feels like magic.

**Comment by lasconic** [comment]
> What a job you've done here!

Thanks, I believe French is now very close to 100%

**Comment by BoboTiG** [comment]
Let's wait for GPT4, it could surprise us :)
