### ISSUE TITLE
Investigate why some variants are not taken into account

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1418]
Reported by [Alex6](https://www.tiger-222.fr/?d=2020/04/17/22/14/21-un-dictionnaire-alternatif-et-complet-pour-votre-kobo#id00446d).

In French, the word [encalminés](https://fr.wiktionary.org/wiki/encalmin%C3%A9s) doesn't return definitions.
Using our CLI, we can confirm what is available on the Wiktionary: **encalminés** has 2 variants (_encalminé_, and _encalminer_):

```
$ python -m wikidict fr --get-word encalminés 
encalminés \ɑ̃.kal.mi.ne\  

[variants] encalminer, encalminé
```
```
$ python -m wikidict fr --get-word encalminer
encalminer \ɑ̃.kal.mi.ne\  

De calme, avec le préfixe en-.


  1. Faire cesser, ou cesser, d’avancer, par manque de vent.
  2. (Figuré) Bloquer l’avancement, le progrès.
```
```
$ python -m wikidict fr --get-word encalminé 
encalminé \ɑ̃.kal.mi.ne\  

(Siècle à préciser) De calme avec les affixes en- et -iné.


  1. (Marine) Immobilisé, en parlant d’un voilier, par l’absence de vent ou à l’abri dans un havre.
  2. (Figuré) En parlant d'une personne : à l'arrêt, en attente de.
[variants] encalminer
```

I open the issue for more investigations, for instance I didn't check Kobo logs yet.

In such a situation, I would have thought both words to be displayed :thinking:

**Comment by lasconic** [comment]
To test, we can create a dictionary with the 3 words only.

**Comment by lasconic** [comment]
My first guess would be that we don't register encalminés because it's a plural and we hoped for Kobo to display encalminé automatically.
Because of : https://pgaskin.net/dictutil/dicthtml/format.html and this statement:

*It is not necessary to explicitly specify variants for things like plurals with a s suffix, as if a word cannot be found, the first prefix match will be used (i.e. tests will match a headword/variant named test). For this reason, words should be sorted from shortest to longest in alphabetical order in general (to prevent accidental matches of the wrong word).*

**Comment by BoboTiG** [comment]
Another use case:

```
python -m wikidict fr --get-word contingente                                      
contingente \kɔ̃.tɛ̃.ʒɑ̃t\ f. 

  1. (Désuet) (Chez Descartes) Variante de cotangente.
[variants] contingent, contingenter
```

So the Kobo will only display "1. (Désuet) (Chez Descartes) Variante de cotangente.", but the awaited definition here is the one from "contigent".

Same issue with "frauduleuses" that doesn't display definitions.

Maybe could we improve that without having to rewrite the Kobo firmware :D

**Comment by pgaskin** [comment]
> My first guess would be that we don't register encalminés because it's a plural and we hoped for Kobo to display encalminé automatically.

IIRC, I was only referring to English when I said that.

**Comment by BoboTiG** [comment]
Using a custom dict created like:

```bash
$ 
```

we got that `en.raw.html` file:

```html
<w>
    <p><a name="encalminé" /><b>encalminé</b> \ɑ̃.kal.mi.ne\<br /><br />
    <p><i>(Siècle à préciser)</i> De <i>calme</i> avec les affixes <i>en-</i> et <i>-iné</i>.</p><br />
    <ol>
        <li><i>(Marine)</i> Immobilisé, en parlant d’un voilier, par l’absence de vent ou à l’abri dans un havre.</li>
        <li><i>(Figuré)</i> En parlant d'une personne : à l'arrêt, en attente de.</li>
    </ol>
    </p><var>
        <variant name="encalmines" />
    </var>
</w>
<w>
    <p><a name="encalminer" /><b>encalminer</b> \ɑ̃.kal.mi.ne\<br /><br />
    <p>De <i>calme</i>, avec le préfixe <i>en-</i>.</p><br />
    <ol>
        <li>Faire cesser, ou cesser, d’avancer, par manque de vent.</li>
        <li><i>(Figuré)</i> Bloquer l’avancement, le progrès.</li>
    </ol>
    </p><var>
        <variant name="encalmine" />
        <variant name="encalmines" />
        <variant name="encalminees" />
    </var>
</w>

</html>
```

We can see that accents were removed from variants. I'm a little bit rusty, so maybe it's OK.

**Comment by BoboTiG** [comment]
Removing the call to https://github.com/BoboTiG/ebook-reader-dict/blob/fe3d7b430ea891f67450f6ccac1edf4e94c80ec4/wikidict/convert.py#L195-L200 fixes the issue.

It was added in #1227. Maybe could we call `strip_accents()` only for the Spanish dictionary?

**Comment by lasconic** [comment]
> We can see that accents were removed from variants. I'm a little bit rusty, is it expected @lasconic?

*The VARIANT must be normalized by trimming whitespace and lowercasing it (following unicode normalization rules, i.e. normalizing accented characters as well)*
According to https://pgaskin.net/dictutil/dicthtml/format.html again

**Comment by lasconic** [comment]
If you have a better behaviour without it, let's remove it for spanish as well.

**Comment by BoboTiG** [comment]
Hm but we can see that **not** normalizing the variant works (at least for the current example). And normalization was added sooner in the year, quite "late" in the project.

**Comment by BoboTiG** [comment]
It's just that those lines seem weird: https://github.com/BoboTiG/ebook-reader-dict/blob/fe3d7b430ea891f67450f6ccac1edf4e94c80ec4/wikidict/convert.py#L286-L287

`guess_prefix()` uses the non-normalized variant, while we store the normalized version in the dict. Maybe such behaviour is wrong, or only necessary for spanish :thinking:

**Comment by BoboTiG** [comment]
(Or maybe latest Kobo updates improved the "search" process, and normalization became obsolete.

**Comment by BoboTiG** [comment]
> Yes, I would get rid of the normalisation if it works for french and see if problems arise in spanish.

Let's see then :+1:
