### ISSUE TITLE
Investigate signature display on Kobo 4.24.15676

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#143]
See #142 for some details. I need to upgrade to Kobo 4.24.15676 and check what can be done to get back a normal behavior.

The current behavior is that if the Zip is copied into `.kobo/dict` it will display both signatures:
> Wiktionnaire (c) 2020
> Le Robert Micro (C) 2013 Dictionnaires Le Robert

But it works correctly when copied into `.kobo/custom-dict`. However, the orginal dictionary (Le Robert) is used by default and it is not convenient to select the Wiktionary dict every time.

**Comment by lasconic** [comment]
This is also promising no ? https://github.com/pgaskin/dictutil/issues/14#issuecomment-698098228

>A custom credit line can be added to the bottom of all entries in the dictionary (newline then the text in italics) by setting it as the zip global archive comment.

**Comment by lasconic** [comment]
I just tested and it works for both dict/customdict and both for the in-book dictionary and the search. I'm running 4.24.15676.
What's your policy in term of firmware support?

**Comment by lasconic** [comment]
For reference: see PR #193

**Comment by BoboTiG** [comment]
Indeed, that's exactly what I was thinking for the fix. And getting rid of the hack is soo attractive :)

I have no policy , mostly because I have no numbers (which firmware versions are in use?). But I think losing the signature on old ones is not an issue.

I have a similar dilemma with # but maybe can we generate 2 dictionaries (one for < 4.24 and for for >= 4.24.
