### ISSUE TITLE
[EN] Support 'uder' template

### ISSUE THREAD

**Issue by gkoscso** [BoboTiG/ebook-reader-dict#1435]
**Dictionary EN-EN (StarDict)**
A quite large number of articles has a buggy etymology section containing the term "from Uder" instead of " from Latin", "from French", etc. _(Goldendict full-text search shows 2661 hits on "from Uder".)_

An example:

**jargon**

- _wiktionary.org:_ 

> From Middle English jargoun, jargon, from Old French jargon, a variant of gargon, gargun (“chatter; talk; language”).

- _dict-en-en StarDict dictionary:_

> From Middle English jargoun, jargon, from Uder fro, a variant of gargon, gargun (“chatter; talk; language”).

**Comment by BoboTiG** [comment]
I'll push a fix right now :+1:

**Comment by BoboTiG** [comment]
Done, it'll be in the dictionnary tomorrow.

**Comment by gkoscso** [comment]
Thank you for the quick fix!
