### ISSUE TITLE
[EN] Syntax error in scripts/en-labels.py

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1439]
There is an error that prevents "en-labels.py" to run properly.

The error seems to be triggered by the code `exec`ed:

```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 96, in <module>
    process_page(url, repl, stop_line, var_name)
  File "scripts/en-labels.py", line 46, in process_page
    exec(code, globals())
  File "<string>", line 1556
SyntaxError: 'return' outside function
```

**Comment by lasconic** [comment]
Here is the breaking change https://en.wiktionary.org/w/index.php?title=Module%3Alabels%2Fdata&type=revision&diff=70326507&oldid=70326007
