### ISSUE TITLE
[CA] Add transliteration in 'etim-lang' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1447]
- Wiktionary page: https://ca.wiktionary.org/wiki/feocromocitoma

Wikicode:
```
{{etim-lang|grc|ca|φαιός|trad=gris}}
```

Output:
```
Del grec antic <i>φαιός</i> («gris»)
```

Expected:
```
Del grec antic <i>φαιός</i> (<i>phaiós</i>, «gris»)
```

---

Model link, if any: https://ca.wiktionary.org/wiki/Plantilla:etim-lang

**Comment by lasconic** [comment]
Quite a mess here.

The transliteration is done automatically for some languages. It's done by a module per language. For a given language code, we can look here for a `trans` parameter https://ca.wiktionary.org/wiki/M%C3%B2dul:llengua/taula#L-267 (for grc)
and we have the name of the module. For grc, it's https://ca.wiktionary.org/wiki/M%C3%B2dul:grc-trans and we need to translate this LUA script to python and do the same for the other languages with a trans_module in llengua/taula... So 15 LUA scripts or so. It would be convenient to do LUA to Python automagically :)

**Comment by BoboTiG** [comment]
What a mess to use `--check-words` without that issue being fixed! ^^

**Comment by lasconic** [comment]
There are 15 transliterations module but so far we have 2 examples for the grc code. Maybe we could start with this one.

**Comment by BoboTiG** [comment]
> There are 15 transliterations module but so far we have 2 examples for the grc code. Maybe we could start with this one.

Agree!

**Comment by lasconic** [comment]
I took a look to the CA grc trans template. It's an old copy of the english one at https://en.wiktionary.org/wiki/Module:grc-translit but it doesn't pass the unit tests... So we are again in this position... or we implement the english one, it's more correct in our dictionary but it will be wrong and `--check-word` will fail for catalan, or we implement the CA one, it will pass --check-word but it might be incorrect... 
What do you think ? @BoboTiG

**Comment by lasconic** [comment]
Here is a Python version of the CA one : https://github.com/BoboTiG/ebook-reader-dict/commit/cead498ae3b1192d154ad7d8cd7a2725543f1b16
To be tested and commented...

**Comment by lasconic** [comment]
Btw, https://github.com/BoboTiG/ebook-reader-dict/issues/1614 is also related

**Comment by BoboTiG** [comment]
Sorry for the late answer!

Implementing the CA version seems better as we want to follow the Wiktionary output more than being "correct".
You've already done all the job, I just agree with you, most specially when we see all issues it tackles at once 👏🏻
