### ISSUE TITLE
[FR] Adapt "composé de" output

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1460]
- Wiktionary page: https://fr.wiktionary.org/wiki/hexavalent

Wikicode:
```
{{composé de|lang=fr|hexa-|-valent|m=1}}
```

Output:
```
Composé de <i>hexa-</i> et de <i>-valent</i>
```

Expected:
```
Dérivé du préfix <i>hexa-</i>, avec le suffixe <i>-valent</i>
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:compos%C3%A9_de

**Comment by BoboTiG** [comment]
Another variant: https://fr.wiktionary.org/wiki/arthroscopie

**Comment by lasconic** [comment]
I discussed this change in the discussion page https://fr.wiktionary.org/wiki/Discussion_mod%C3%A8le:compos%C3%A9_de

**Comment by lasconic** [comment]
It seems the dev who changed the behavior doesn't care about the output. Since we want to reflect the wiktionary even if we don't agree, (and I don't really want to modify the template there myself) I propose to implement the change just as they did ?
