### ISSUE TITLE
[FR] Improve support for the "term" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1492]
- Wiktionary page: https://fr.wiktionary.org/wiki/intergouvernemental

Wikicode:
```
{{term|lang=fr|droit international public}}
```

Output:
```
<i>(Lang=fr)</i>
```

Expected:
```
<i>(Droit international public)</i>
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:term

Looking at the model, we are missing several use cases. Even if there can be a lot of keywords arguments, only a few are needed in order to cover all possibilities.

**Comment by lasconic** [comment]
oops I have it ready

**Comment by lasconic** [comment]
Forgot to assign myself
:(

**Comment by BoboTiG** [comment]
No worries :D
