### ISSUE TITLE
[FR] Add "pc" HTML filter

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1493]
- Wiktionary page: https://fr.wiktionary.org/wiki/La_Haye-Fouassi%C3%A8re

That check doesn't pass, I don't know yet why:
```bash
$ python -m wikidict fr --check-word 'La Haye-Fouassière'
```

**Comment by BoboTiG** [comment]
Another one: https://fr.wiktionary.org/wiki/belyankite

**Comment by lasconic** [comment]
First one is a side effect of the fix I did for siècle2.. not sure if we can make it work

**Comment by lasconic** [comment]
Second one a well. Small caps rendered to capitals is not good...
