### ISSUE TITLE
Smarter link-with-namespace filter

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1494]
- Wiktionary page: https://fr.wiktionary.org/wiki/halq%E2%80%99em%C3%A9ylem

Wikicode:
```
[[Stó:lō]]
```

Output:
```
None
```

Expected:
```
Stó:lō
```

The wikicode is stripped at https://github.com/BoboTiG/ebook-reader-dict/blob/fdca309f31290fdee99fe76efb2b2f33b45112c1/wikidict/utils.py#L391

Not sure what to do for now, just reporting the issue.

**Comment by BoboTiG** [comment]
With 1b09061fa129f1f74b9d1c161156c1d92f893a51 it will be easier to use locale-specific code then.

**Comment by lasconic** [comment]
Mmm ok, I would have pass the language code in clean to get the correct array of namespace. If I understand correctly, here we will need to write a "clean" function per language with the current clean being the default. Correct ?

**Comment by BoboTiG** [comment]
I didn't want to add the new argument to `clean()` everywhere. We already have the locale name passed `process_template()`.
So you can still go with your idea, it'll just a 2-lines change to actually add the new argument to `clean()` (instead of ~30 changes before the refactoring).

**Comment by lasconic** [comment]
I have something more or less working but I'm scratching my head on these two (on top of [[Stó:lō]]) or course. Not sure how to handle this yet

[[Fichier:Blason ville fr Petit-Bersac 24.svg|vignette|120px|'''Base''' d’or ''(sens héraldique)'']]
[[Annexe:Principales puissances de 10|10{{e|&minus;6}}]] [[gray#fr-nom|gray]]

**Comment by BoboTiG** [comment]
Would you like to open a draft PR so that I can try too?

**Comment by lasconic** [comment]
There you go. 
1/ I'm not sure it's really needed to keep all-namespaces.py in scripts. They probably don't change that often.
2/ I can't find a way to diffentiate the Fichier and Annexe namespace but we need to clean them at different time.
3/ The line you reference above is commented in my code but it we used to pass this test...

```
clean("[[http://www.tv5monde.com/cms/chaine-francophone/lf/Merci-Professeur/p-17081-Une-peur-bleue.htm?episode=10 Voir aussi l’explication de Bernard Cerquiglini en images]]")
```

**Comment by BoboTiG** [comment]
1/ You're right, we could move the file to `langs`.
2/ 3/ Still checking :watch:

**Comment by BoboTiG** [comment]
OK I made progress, will propose a patch on the PR.

**Comment by BoboTiG** [comment]
1/ After more thinking, keeping namespaces in scripts would ease our work when adding new locales, and it will handle updates automatically. I would say we can keep it as-is. The only tiny detail is about usong `ALL_LOCALES` instead of having duplicate lists; but it's a minor issue.

**Comment by lasconic** [comment]
OK but then it's less easy to implement 2 categories of namespaces, the one with text and the one without.

**Comment by lasconic** [comment]
I believe it breaks 
```
{{recons|lang-mot-vedette=fr|[[Reconstruction:proto-germanique/*berhtaz|berht]]}}
```

**Comment by BoboTiG** [comment]
Can you share the word using it 🙏 ?

**Comment by lasconic** [comment]
Sorry https://fr.wiktionary.org/wiki/Berthe

**Comment by lasconic** [comment]
Ok. I have a simple solution... It passes all the tests already in the code... I must miss something.

https://github.com/BoboTiG/ebook-reader-dict/pull/1530

**Comment by lasconic** [comment]
Ok. Already found a problem ...

https://fr.wiktionary.org/wiki/Daghestan uses the File namespace ...

A solution could be to always add File and Category, the english namespaces in the pattern list.

**Comment by BoboTiG** [comment]
> A solution could be to always add File and Category, the english namespaces in the pattern list.

:+1:
