### ISSUE TITLE
[FR] Fix "term" handler

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1504]
Following #1498, we have errors with those Wiktionary pages:
- https://fr.wiktionary.org/wiki/billet_de_change
- https://fr.wiktionary.org/wiki/billet_promissoire
- https://fr.wiktionary.org/wiki/Occident
- https://fr.wiktionary.org/wiki/sou

Wikicode:
```
{{term|{{smcp|xix}}{{e}} s.}}
```

Output:
```python
  File "lang/fr/template_handlers.py", line 1122, in render_term
    return term(capitalize(data["libellé"] or data["1"] or parts[0]))
IndexError: list index out of range
```

**Comment by BoboTiG** [comment]
The root cause seems to be when we populate `parts` and `data`. As the first part is actually the result of another template, it contains a `=` sign, and at the end:
- `parts = []`
- `data = defaultdict(<class 'str'>, {'<span style': "'font-variant:small-caps'>XIX</span><sup>e</sup> s."})`

**Comment by lasconic** [comment]
Well, I can silent the error by checking the length of parts but it will just hide the problem...

The only good way is to use the logic of https://en.wiktionary.org/wiki/Module:parameters
And it means we need to get and store all the possible parameters for a template...

I can't think of a middle ground. And you ?

**Comment by BoboTiG** [comment]
What if we use a smarter split mechanism? We ar ecurrently splitting on `=` to populate `data`. Maybe could we prevent the split when it's followed by `"` or something like that :thinking: 

I'll try one thing or two.
