### ISSUE TITLE
[CA] Handle "+word" in "comp" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1531]
- Wiktionary page: https://ca.wiktionary.org/wiki/argilar

Wikicode:
```
{{comp|ca|argila|+ar}}
```

Output:
```
<i>argila</i> i <i>+ar</i>
```

Expected:
```
<i>argila</i> i la desinència <i>-ar</i>
```

---

Model link, if any: https://ca.wiktionary.org/wiki/Plantilla:comp

**Comment by BoboTiG** [comment]
Another issue: https://ca.wiktionary.org/wiki/xoc using `{{comp|ca|xocar|+Ø}}` and `+Ø` becomes `Ø`.

**Comment by lasconic** [comment]
xoc has changed. See https://ca.wiktionary.org/w/index.php?title=xoc&oldid=2008967
