### ISSUE TITLE
[CA] Add support for transliteration in "e" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1546]
- Wiktionary page: https://ca.wiktionary.org/wiki/mi

Wikicode:
```
{{e|el|μ}}
```

Output:
```
μ
```

Expected:
```
μ (<i>m</i>)
```

---

Model link, if any: https://ca.wiktionary.org/wiki/Plantilla:e

**Comment by lasconic** [comment]
See #1447
