### ISSUE TITLE
Use ICU to sort words correctly

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#155]
[IUC](https://github.com/ovalhub/pyicu) should be used to correctly sort words according to the target locale:
```python
from icu import Collator, Locale

collator = Collator.createInstance(Locale.getFrance())
# or collator = Collator.createInstance(Locale("fr_FR.UTF-8"))
words = sorted(words, key=collator.getSortKey)
```

For more details, go see the [Miroslav Šedivý - Your Name Is Invalid!](https://www.youtube.com/watch?v=IuZBTjaphsY&list=PL8uoeex94UhHgMD9GOCbEHWku7pEPx9fW&index=13) conference from the EuroPython 2020.

**Comment by lasconic** [comment]
Could you show where "sort" is needed in the current code? I couldn't find it.

**Comment by BoboTiG** [comment]
It would be here: https://github.com/BoboTiG/ebook-reader-dict/blob/c04f61c4ccd55d6872ccc4758a6dd6bb7f44ab9b/scripts/convert.py#L95

**Comment by lasconic** [comment]
I probably miss the point... so sorry for the naive question... but do we really need to sort the wordlist to create the Trie ?

**Comment by BoboTiG** [comment]
You are right to ask because: no, I am not sure at all :)

**Comment by BoboTiG** [comment]
In fact, we could even remove that `sorted()`, WDYT?

**Comment by BoboTiG** [comment]
I do not recall why I added it at first 🤔

**Comment by lasconic** [comment]
Ok :) It makes sense to remove it.
