### ISSUE TITLE
[PT] Support "codelang" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1607]
- Wiktionary page: https://pt.wiktionary.org/wiki/fariseu

Wikicode:
```
{{codelang|grc}}
```

Output:
```
<i>(Codelang)</i>
```

Expected:
```
grego clássico
```

---

Model link, if any: https://pt.wiktionary.org/wiki/Predefini%C3%A7%C3%A3o:codelang

**Comment by lasconic** [comment]
codelang uses the default implementation of mediawiki to get the language name from the ISO code : [#language](https://www.mediawiki.org/wiki/Help:Magic_words##language), which in turn use the CLDR project and one of these files https://github.com/unicode-org/cldr-json/tree/f27f55f1dd487af7cf4260f56296ee1c7649b7fc/cldr-json/cldr-localenames-full/main

**Comment by BoboTiG** [comment]
So we could fetch https://github.com/unicode-org/cldr-json/blob/42.0.0/cldr-json/cldr-localenames-full/main/pt-PT/languages.json or the SHA256 you provided is the exact version we should use?

**Comment by BoboTiG** [comment]
And https://github.com/unicode-org/cldr-json/pull/43 "‿"

**Comment by lasconic** [comment]
I'm still looking for the code in the CLDR extension that does that. The SHA was just the latest one. 
I'm would go for just "pt" and I don't know if the localenames-full https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-localenames-full/main/pt/languages.json is used or the "modern" one https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-localenames-modern/main/pt/languages.json
