### ISSUE TITLE
[IT] Support langs single template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1625]
- Wiktionary page: https://it.wiktionary.org/wiki/'sto

Wikicode:
```
{{it}}
```

Let's see if we can use an [API](https://it.wiktionary.org/w/api.php?) instead of fetching/parsing https://it.wiktionary.org/wiki/Categoria:Template_lingua_testo.

**Comment by BoboTiG** [comment]
Here is the API.

**Comment by BoboTiG** [comment]
OK, I may used the wrong list.

For instance, `{{ang}}` returns `inglese` when `anglosassone` is awaited (https://it.wiktionary.org/wiki/Danimarca). And other subtlities.

**Comment by BoboTiG** [comment]
Another issue: {{gem}} is not in the current list were `germanico` is awaited (https://it.wiktionary.org/wiki/Gilberto).

**Comment by lasconic** [comment]
it -> italiano is hardcoded in the template : https://it.wiktionary.org/w/index.php?title=Template:it&action=edit
I doubt we will find an API for that.

But if we end up using the API and caches, we would use "parse" or "expandtemplate" and save a bit of work on the render step :-)

**Comment by BoboTiG** [comment]
I'll go with the fetch/parse of all those pages then.

> But if we end up using the API and caches, we could use "parse" or "expandtemplate" and save a bit of work on the render step :-)

If you have ideas, we can do all what we want ;)
