### ISSUE TITLE
[EN] Support  'mono' and 'monospace' templates

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1649]
- Wiktionary page: https://en.wiktionary.org/wiki/shebang

Wikicode:
```
{{monospace|#!}}
```

Output:
```
(Monospace)
```

Expected:
```
<span style="font-family: monospace, monospace;">#!</span>
```
To be tested on actual device
---

Model link, if any: https://en.wiktionary.org/wiki/Template:mono
Aliases https://en.wiktionary.org/wiki/Special:WhatLinksHere?target=Template%3Amono&namespace=&hidetrans=1&hidelinks=1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/ebook-reader-dict/issues/1649">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/1649/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/1649/pledge.svg">
</picture>
</a>

**Comment by lasconic** [comment]
In the same area, see https://en.wiktionary.org/wiki/Template:nobr
and alias nowrap

https://en.wiktionary/wiki/carbyne
https://en.wiktionary/wiki/bull
https://en.wiktionary/wiki/separatrix

**Comment by lasconic** [comment]
@BoboTiG What would you do for nowrap/nobr ? Do we use the same style ? Or do we ignore the command and output the text as it ?

**Comment by BoboTiG** [comment]
I would say we use the same style.
