### ISSUE TITLE
[EN] Error with Gamaliel

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1652]
- Wiktionary page: https://en.wiktionary.org/wiki/Gamaliel

Wikicode:
```
{{given name|en|male|from=Hebrew<t:God is my reward>}}
```

Output:
```python
  File "lang/en/template_handlers.py", line 428, in render_given_name
    suffix += f"{langs[from_split[0]]} {from_split[1]}"
KeyError: 'Hebrew<t'
```

Expected:
```
A male given name from Hebrew (“God is my reward”)
```

**Comment by lasconic** [comment]
The data is correct when render_given_name is executed but this function lacks support for <t:God> notation. 
See https://en.wiktionary.org/wiki/Module:names#L-83
