### ISSUE TITLE
[ES] Smarter output for "etimología2" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1711]
Wiktionary pages: 
- https://es.wiktionary.org/wiki/abocetar (lowercase)
- https://es.wiktionary.org/wiki/hocico (uppercase)

Wikicode:
```
{{etimología2|[[a- (ES) (2)|a-]] ([[morfema]]) + [[boceto|bocet]] ([[lexema]]) + [[-ar]] ([[morfema]])}}
{{etimología2|de [[hocicar]]}}
```

Output:
```
A- (morfema) + bocet (lexema) + -ar (morfema) 
De hocicar
```

Expected:
```
a- (morfema) + bocet (lexema) + -ar (morfema) 
De hocicar
```

So we need to be smarter as of when to use uppercase.

---

Model link, if any: https://es.wiktionary.org/w/index.php?title=Plantilla:etimolog%C3%ADa2&action=edit and the revelant code:

```
-->| #default = {{ucfirst:{{{1}}}}}<!--
   -->{{detección namespace<!--
   -->|main={{#ifeq:{{lc:{{{leng|x}}}}}|x||[[Categoría:{{uc:{{{leng}}}}}:Palabras con etimología libre]]}}<!--
   -->}}<!--
```

**Comment by lasconic** [comment]
I might be wrong but I believe we can't solve this one unless we change the whole architecture of the parsing.

When we process etimologia2, the links are already resolved so in the first case we get
```
{{etimología2|a-
```
and in the second case
```
{{etimología2|de
```
and we do uppercase the first letter.

The wiktionary software gets `{{etimología2|[[` and it does uppercase and nothing is changed.

I believe we already encountered this issue but I can't find anything in the issue tracker.
