### ISSUE TITLE
[ES] Handle multiple parameters to "variantes" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1712]
- Wiktionary page: https://es.wiktionary.org/wiki/acrotera

Wikicode:
```
{{variantes|acrótera|acroteria}}
```

Output:
```
<b>Variante:</b> acrótera
```

Expected:
```
<b>Variante:</b> acrótera
```

---

Model link, if any: https://es.wiktionary.org/wiki/Plantilla:variantes

Actually, I am wondering why we do not ignore such a template @lasconic?

**Comment by lasconic** [comment]
> Actually, I am wondering why we do not ignore such a template @lasconic?

We already had this discussion apparently.

https://github.com/BoboTiG/ebook-reader-dict/issues/832
