### ISSUE TITLE
user_functions.html usefulness?

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1751]
I'm not sure https://github.com/BoboTiG/ebook-reader-dict/blob/master/html/wikidict/user_functions.html is used by anyone. I would like to simplify the CI, having less requirements, and just remove the HTML file.

@lasconic do you want to vote against?

**Comment by lasconic** [comment]
I never used this file and it's not clear to me why it was added in the first place. It does polute my search results when I search the code in VStudio. So no, I don't want to vote against !
