### ISSUE TITLE
Locale request: Romanian

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1771]
- Wiktionary page: https://ro.wiktionary.org

I was contacted by email about potential Romanian dictionaries. So lets add them :)

@lasconic I'll give a try, or do you want to work on it?

**Comment by lasconic** [comment]
I have an evening tonight but I don't plan to work on the project much in the next weeks.

**Comment by BoboTiG** [comment]
I'll find some time later in the week, or the next one. If you want to give a try tonight, just open a PR so that I can continue the work later :)

**Comment by lasconic** [comment]
Probably the sections: https://ro.wiktionary.org/wiki/Categorie:Formate_p%C4%83r%C8%9Bi_de_vorbire

**Comment by lasconic** [comment]
And the only way I could find : process the code and replace {{-substantive-|ron}} by `=== {{-substantive-|ron}} ===`

**Comment by BoboTiG** [comment]
Ian, and Maria, provided me a lot of useful details (for variants handling, and so on). Here is what I received by email.

Romanians have 4 general verb conjugation patterns.  We will provide an example of each in case that will be useful to you.

Verbs (“Verbe”) in the infinitive
- 1st conjugation – verbs ending in -a: a cânta to sing
  - To Sing (a cânta)
    - https://ro.wiktionary.org/wiki/c%C3%A2nta
    - https://en.wiktionary.org/wiki/c%C3%A2nta#Verb

- 2nd conjugation – verbs ending in -ea: a vedea to see
  - To See (a vedea)
    - https://ro.wiktionary.org/wiki/vedea
    - https://en.wiktionary.org/wiki/vedea#Verb_2

- 3rd conjugation – verbs ending in -e: a merge to walk
  - To Go (a merge)
    - https://ro.wiktionary.org/wiki/merge
    - https://en.wiktionary.org/wiki/merge#Verb_4

- 4th conjugation – verbs ending in -i and -î: a fugi to run
  - To Run (a fugi)
    - https://ro.wiktionary.org/wiki/fugi#Verb
    - https://en.wiktionary.org/wiki/fugi#Verb_4

- Additionally, some important verbs are irregular, such as:
  - To Be (a fi)
    - https://ro.wiktionary.org/wiki/fi#Verb
    - https://en.wiktionary.org/wiki/fi#Verb_2
  - To Have (a avea)
    - https://ro.wiktionary.org/wiki/avea#Verb
    - https://en.wiktionary.org/wiki/avea#Verb_2
  - To Give (a da)
    - https://ro.wiktionary.org/wiki/da#Verb
    - https://en.wiktionary.org/wiki/da#Verb_13

		
- a form of a verb (like "ate" for the past of eat)
We will use the “compound past” forms of each verb we listed above:

Verbs in the compound past (described as the “past participle”) 
- 1st conjugation
  - “I have sang” (am cântat)
    - https://ro.wiktionary.org/wiki/c%C3%A2ntat#Verb
    - https://en.wiktionary.org/wiki/c%C3%A2ntat#Verb

- 2nd conjugation
  - “I saw” (am văzut)
    - https://ro.wiktionary.org/wiki/v%C4%83zut
    - https://en.wiktionary.org/wiki/v%C4%83zut#Verb

- 3rd conjugation
  - “I have gone” (am mers)
  - https://ro.wiktionary.org/wiki/mers#Verb https://en.wiktionary.org/wiki/mers#Verb_4

- 4th conjugation – verbs ending in -i and -î: a fugi to run
  - To Run (a fugi)
    - https://ro.wiktionary.org/wiki/fugi#Verb
    - https://en.wiktionary.org/wiki/mers#Verb

- Additionally, some important verbs are irregular, such as:
  - “I was” (am fost)
    - https://ro.wiktionary.org/wiki/fost#Verb
    - https://en.wiktionary.org/wiki/fost#Participle

  - To Have (a avea)
    - https://ro.wiktionary.org/wiki/avut#Verb
    - https://en.wiktionary.org/wiki/avut#Verb

  - To Give (a da)
    - https://ro.wiktionary.org/wiki/dat#Verb
    - https://en.wiktionary.org/wiki/dat#Verb_4

- an adjective (“adjectiv”)
There are masculine and feminine adjectives, we will provide examples of both. (We did our best here but it seems the Romanian wikitionary does not have certain conjugations of these adjectives. I will probably add them over time with my wife, as this project has galvanized our love of studying this language)
- Masculine singular:
  - Frumos (beautiful, pretty)
    - https://ro.wiktionary.org/wiki/frumos#Adjectiv
    - https://en.wiktionary.org/wiki/frumos#Adjective
- Feminine singular:
  - Frumoasă (beautiful, pretty)
    - https://ro.wiktionary.org/wiki/frumoas%C4%83#Adjectiv
    - https://en.wiktionary.org/wiki/frumoas%C4%83#Adjective
- Masculine Plural:
  - Frumoși (beautiful, pretty)
    - https://en.wiktionary.org/wiki/frumo%C8%99i
    - (There was no suitable Romanian page for this conjugation, if that is a problem we can send another example.)

- a noun (“substantiv”) (masculine, feminine, and neuter)
- Masculine: Man – (bărbat)
  - https://ro.wiktionary.org/wiki/b%C4%83rbat#Substantiv
  - https://en.wiktionary.org/wiki/b%C4%83rbat#Noun
- Feminine: Woman (femeie)
  - https://ro.wiktionary.org/wiki/femeie#Substantiv
  - https://en.wiktionary.org/wiki/femeie#Noun
- Neuter/Neutral: Fountain pen – Stilou
  - https://ro.wiktionary.org/wiki/stilou#Substantiv
  - https://en.wiktionary.org/wiki/stilou#Noun

- a proper noun (“nume propriu”)
- Hungary (the country):
  - https://ro.wiktionary.org/wiki/Ungaria#Nume_propriu
  - https://en.wiktionary.org/wiki/Ungaria#Proper_noun
- Transylvania
  - https://ro.wiktionary.org/wiki/Transilvania#Nume_propriu
  - https://en.wiktionary.org/wiki/Transilvania#Proper_noun_8


- a plural (like "fruits", where the singular is "fruit")
- Orange (portocală) (feminine)
  - https://ro.wiktionary.org/wiki/portocal%C4%83#Substantiv
  - https://en.wiktionary.org/wiki/portocal%C4%83#Noun
- Oranges (portocale)
  - https://ro.wiktionary.org/wiki/portocale#Substantiv
  - https://en.wiktionary.org/wiki/portocale
- Drinking glass (pahar) (neuter)
  - https://ro.wiktionary.org/wiki/pahar
  - https://en.wiktionary.org/wiki/pahar#Noun_2
- Drinking glasses (pahare)
  - https://ro.wiktionary.org/wiki/pahare#Substantiv
  - https://en.wiktionary.org/wiki/pahare

**Comment by lasconic** [comment]
After a quick look, it seems Romanian would benefit a lot from https://github.com/BoboTiG/ebook-reader-dict/issues/1149

https://ro.wiktionary.org/wiki/mai for example has several etymologies, and we will get only one and several part of speech that we will not display.

**Comment by BoboTiG** [comment]
Indeed. Well, that will be quite a work it seems.
Lets do a best effort support using the whatevrr etymology we get for now.

**Comment by lasconic** [comment]
Another interesting fact, the romanian wiktionary seldom uses templates in definitions and etymologies.

**Comment by BoboTiG** [comment]
And here is the first version: https://github.com/BoboTiG/ebook-reader-dict/releases/tag/ro 🍾

**Comment by BoboTiG** [comment]
I'll generate new dictionaries, and close that issue since the support is quite complete.

@drkoll if you find any issue, or if a word is missing from dictionaries but present on the wiktionary, just open an issue, and we will have a look :)
