### ISSUE TITLE
[CA] Handle the 'etim-lang' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#179]
- Wiktionary page: https://ca.wiktionary.org/wiki/advenir

Wikicode:
```
{{etim-lang|la|ca|axioma}}
```

Output:
```
None
```

Expected:
```
Del llatí <i>axioma</i>.
```

---

Model link, if any: https://ca.wiktionary.org/wiki/Plantilla:etim-lang

**Comment by lasconic** [comment]
The Catalan wiktionary has https://ca.wiktionary.org/wiki/Viccionari:%C3%8Dndex_d%27idiomes but it's not as complete as needed to cover all the languages in https://ca.wiktionary.org/wiki/Categoria:Etimologia_en_catal%C3%A0

I checked the source of wiktionary etim-lang and they use [CLDR from unicode.org](https://github.com/unicode-org/cldr/blob/master/common/main/ca.xml) and then change it for their [own need](https://ca.wiktionary.org/wiki/M%C3%B2dul:llengua/taula)... Do you really want to automate all of this for less than 40 languages used?

**Comment by BoboTiG** [comment]
You go go as you want ;)

**Comment by lasconic** [comment]
OK. Too late... Lockdown...

For the wiki page

```
# Last version of CLDR ca.xml file
# https://raw.githubusercontent.com/unicode-org/cldr/d6b0b968a492da6c34a37b33b200aee940f45d0d/common/main/ca.xml
# Last version of https://ca.wiktionary.org/w/index.php?title=M%C3%B2dul:llengua/taula
# https://ca.wiktionary.org/w/index.php?title=M%C3%B2dul:llengua/taula&oldid=1600882

import xml.etree.ElementTree as ET
import re
tree = ET.parse('ca.xml')
root = tree.getroot()

languages = {}
for l in root.iter("language"):
    iso = l.get('type')
    name = l.text
    languages[iso] = name


file1 = open('module.html', 'r')
Lines = file1.readlines()
file1.close()

count = 0
# Strips the newline character
pattern = re.compile('.*\"s2\">\"([^\"]+)\"')
iso = ""
name = ""
for line in Lines:
    line = line.strip()
    if line.startswith("<span class=\"n\">c</span>"):
        m = pattern.match(line)
        iso = m.group(1)
    elif line.startswith("<span class=\"n\">nom"):
        m = pattern.match(line)
        name = m.group(1)
        if iso:
            languages[iso] = name

print("{")
for iso, lang in languages.items():
    print(f'    "{iso}": "{lang}",')
print("}")


print(f"# {len(languages):,}")

```

**Comment by BoboTiG** [comment]
Ah this is really great then! When the PR will be good, I will add the wiki page with your script. Think to isolate the langs into a `langs.py` as done for other locales.
