### ISSUE TITLE
[EN] Fix broken "en-labels.py" script

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1827]
```python
Traceback (most recent call last):
  File "scripts/en-labels.py", line 184, in <module>
    results |= process_page(page_url, repl, stop_line, var_name, print_result=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/en-labels.py", line 55, in process_page
    exec(code, globals())
  File "<string>", line 4
    for _, v in pairs(labels) do
                              ^^
SyntaxError: invalid syntax
```

**Comment by lasconic** [comment]
Problem is here : https://en.wiktionary.org/wiki/Module:labels/data/lang/mt
They recently move all the data in a module... 

Same for https://en.wiktionary.org/wiki/Module:labels/data/lang/sq

**Comment by lasconic** [comment]
Many other errors in update-locale. I will try to fix them.
* 404 is not well handled, maybe a change in requests ? or a bug
* `scripts/en-form-of.py` is broken, the layout of the source page has changed.

**Comment by lasconic** [comment]
The PR should fix update locale data entirely.
