### ISSUE TITLE
Poll: Move etymology below definitions?

### ISSUE THREAD

**Issue by Gabriel85** [BoboTiG/ebook-reader-dict#1846]
[Edit from @BoboTiG] Please vote using a reaction on that message:
- 👍🏻 you would like to have etymology **below** definitions
- 👎🏻 you like the current behavior where etymology is **above** definitions
- ❤️ you have **no** strong **opinion**, and whatever we do will be OK

---

Would it be possible to move the etymology below the definitions in order to improve legibility?
It's nice to have it available, but I think in most cases for most people it is not what they are looking for. I know Wikipedia shows it first (unlike paper dictionaries) and it looks nicer like that, but it is suboptimal for ePaper devices with limited screen estate.

**Comment by BoboTiG** [comment]
As it is not the first time we receive such a request, I made that issue a poll (+edited the description).

**Comment by Gabriel85** [comment]
Well since it has been nearly 2 months, and the "overwhelming" majority of voters supports my suggestion, I propose putting the etymology below the definition! 
If people start complaining about it, I guess it would not be a big deal to reverse it again?

**Comment by Gabriel85** [comment]
> As of 2024-03-24:
> 
> * 👍🏻 6
> * 👎🏻 1
> * ❤️ 2
> 
> Even if the number of voters is quite small, I guess we can go for etymologies at the bottom.

Thank you! 👍
