### ISSUE TITLE
Split by part of speech

### ISSUE THREAD

**Issue by raffaem** [BoboTiG/ebook-reader-dict#1877]
If I look up for example "byline" in wiktionary (https://en.wiktionary.org/wiki/byline), the entry is split by part of speech:
![image](https://github.com/BoboTiG/ebook-reader-dict/assets/54762742/318137bf-f989-4f48-a78d-d2ca0f5d7e72)

Instead, if I use the dictionaries in this repo, it isn't:
![image](https://github.com/BoboTiG/ebook-reader-dict/assets/54762742/1a23f806-943e-4d5a-bfb7-d33c18d449cb)

Would it be possible to have the entries split by part of speech?

**Comment by BoboTiG** [comment]
Hello @raffaem,

You are not the first one to ask for such a feature. I redirect you to #1149 to track it.
