### ISSUE TITLE
[RU] Dictionary not yet available

### ISSUE THREAD

**Issue by sunnysideup249** [BoboTiG/ebook-reader-dict#1888]
Not sure if it's intentional but I am unable to download the files for the Russian Dictionary. The only thing available is the source code.

**Comment by BoboTiG** [comment]
Russian dictionaries are not available yet. Someone needs to step up to help on the subject, someone with russian skills :)

**Comment by sunnysideup249** [comment]
Ah I see, apologies for being so daft. I can speak Russian but my computer skills are close to nil, let me know if there's any way I can help!

**Comment by kyxap** [comment]
maybe there should be open issue which you can refer to? 

also while ru dic is broken it seems a good idea to link to the issue and say - hey, we know that is broken here is the issue... 

anyway, I could help with fixing the ru dic but at this point im not sure where is the issue coming from except broken links

**Comment by kyxap** [comment]
@BoboTiG what I need to do pull/create dic locally? I've use github ci [scripts ](https://github.com/BoboTiG/ebook-reader-dict/blob/master/.github/workflows/auto-updates.yml) but `render` takes 30+ mins not sure if its expected

**Comment by BoboTiG** [comment]
@kyxap, from your venv:

```console
python -m wikidict ru
```

**Comment by BoboTiG** [comment]
Russion dictionary is soooo long to finish because of the way we retreive etymologies: we fetch a Wikimedia API endpoint for 1,353,118 words. That's not something proper, I'll skip that part for now.

**Comment by BoboTiG** [comment]
I fixed all errors.

Current state:
- no etymologies
- lots of templates missing
- dictionaries are working, I'll enable back them

**Comment by BoboTiG** [comment]
I close that issue now that [Russian dicts are available ](https://github.com/BoboTiG/ebook-reader-dict/releases/tag/ru)(cfb1a5741b721ce9bd4a099bef787f4c99fdcc87). 🍾
