### ISSUE TITLE
Generate dictionaries in the DICT.org format for Plato

### ISSUE THREAD

**Issue by ariasuni** [BoboTiG/ebook-reader-dict#1954]
[Plato](https://github.com/baskerville/plato)’s native format is DICT.org (different format than dictfile). It would be nice if you provided dictionaries with this format directly.

I saw that you’re using `pyglossary`, which supports `DICT.org` (and the `dictzip` option, which Plato supports):
https://github.com/ilius/pyglossary/blob/master/doc/p/dict_org.md

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/ebook-reader-dict/issues/1954">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/1954/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/1954/pledge.svg">
</picture>
</a>

**Comment by BoboTiG** [comment]
I am trying to work on that feature.

@ariasuni, which language do you want me to try first in order to ease our testing?

**Comment by BoboTiG** [comment]
@ariasuni You will be able to try new dictionaries by tomorrow :)
