### ISSUE TITLE
Replace Dict by DefaultDict in extract_keywords

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#1964]
Currently `extract_keywords_from` in `user_functions.py` return a `defaultdict` but is typed with a `Dict` type. All the functions in `lang_code/template_handlers` expect a `Dict`, but really get a `defaultdict`.  
A consequence we get this type of remarks from Sourcery LLM https://github.com/BoboTiG/ebook-reader-dict/pull/1963#discussion_r1489551296

Ok to type it correctly ? And change all the template_handlers functions ?

@BoboTiG  ?

**Comment by BoboTiG** [comment]
👍🏻
