### ISSUE TITLE
[FIL/TGL] Support Filipino/Tagalog template

### ISSUE THREAD

**Issue by saweeet** [BoboTiG/ebook-reader-dict#1972]
- Wiktionary page: https://en.wiktionary.org/wiki/filipino ; https://en.wiktionary.org/wiki/tagalog
- Model link: 

Thank you in advance!

**Comment by lasconic** [comment]
Unless you mean you want to add support for the tagalog language : https://tl.wiktionary.org/wiki/Tagalog ?
