### ISSUE TITLE
Keep the whole etymology

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#198]
- Wiktionary page: https://fr.wiktionary.org/wiki/bath

Command:
```
python -m scripts --locale="fr" --get-word="bath" 
```

Output:
```
bath \bat\ (m.) 

(Adjectif, nom 1) (1846) Origine discutée : 

  1. (Argot) (Désuet) Super ; bon ; agréable.
  2. Papier à lettre de provenance anglaise, de belle qualité, qui a joui d’une grande vogue au XIXème siècle.
  3. Mesure des liquides chez les Hébreux, valant 18,08 litres puis plus tard environ 38,88 litres.
```

The etymology is clearly truncated. It has a sublist and even a second etymology.

Not a big priority, I just opened the issue to keep the track.

**Comment by BoboTiG** [comment]
Another one: https://fr.wiktionary.org/wiki/picotin

**Comment by lasconic** [comment]
https://fr.wiktionary.org/wiki/à minima

**Comment by lasconic** [comment]
Also https://fr.wiktionary.org/wiki/non-r%C3%A9sistance

Is it for french only ?

**Comment by lasconic** [comment]
I had a quick look. It seems we would need `etymology` to become a list of list (of list ?) just like `Definitions`. Maybe we could even reuse this type for etymology. WDYT ?
I might have a try in the coming week.

**Comment by BoboTiG** [comment]
Yes, we could reuse `Definitions` 👍

**Comment by BoboTiG** [comment]
I did not encounter complex etymologies on other locales, but I am not using other dictionaries. I would vote to fix etymologies for all locales.

**Comment by lasconic** [comment]
![screen_001](https://user-images.githubusercontent.com/234271/116284393-27137980-a7e1-11eb-8215-b3a6baeeec28.png)
![screen_002](https://user-images.githubusercontent.com/234271/116284401-2844a680-a7e1-11eb-8909-f22ff034fb22.png)

**Comment by lasconic** [comment]
Is this rendering ok ?

**Comment by BoboTiG** [comment]
It seems nice.
Do you think we should find a way to differentiate the etymology from definitions?

**Comment by BoboTiG** [comment]
We could go like that and eventually adjust the rendering later (let's see how it works for us on a day-to-day basis), WDYT?

**Comment by lasconic** [comment]
Sure. Some etymologies are crazy btw : https://fr.wiktionary.org/wiki/marron

I'm still working on the tests. PR to come.

**Comment by BoboTiG** [comment]
Wow, I really hope that such etymolgy is rare enough to no mimic the "Le Littré" (where it becomes really unpleasant to read).

Anyway, that will be a great improvement to the dictionaries 🍾

**Comment by lasconic** [comment]
The PR is in. It doesn't cover all languages. I believe it's complete for french (except if there are subsublist...) and it improves `en` and `pt`.

**Comment by BoboTiG** [comment]
Awesome! I triggered the update workflow manually: dictionaries are coming!

**Comment by BoboTiG** [comment]
It works like a charm :)
I tried with "bruine" which has a weird etyomology and "baroud". It is pleasant to have the whole etymology 💪

**Comment by lasconic** [comment]
Great ! Thanks !
