### ISSUE TITLE
[EL] Support "αρχ", "μσν" and "βλφρ" templates

### ISSUE THREAD

**Issue by chopinesque** [BoboTiG/ebook-reader-dict#1994]
Not sure how to add support for these templates?

- Wiktionary page: https://el.wiktionary.org/wiki/%CE%AC%CE%B3%CE%B1%CE%BB%CE%BC%CE%B1

output on wiktionary: `παράσταση < μεσαιωνική ελληνική παράστασις < αρχαία ελληνική παρίστημι < αρχαία ελληνική παρά + ίστημι`
wiktionary source: : `'''{{PAGENAME}}''' < {{μσν}} '''[[παράστασις]]''' < {{αρχ}} [[παρίστημι]]  < {{αρχ}} [[παρά]] + [[ίστημι]]`

output on ebook-reader-dict: `παράσταση < {{μσν}} παράστασις < {{αρχ}} παρίστημι < {{αρχ}} παρά + ίστημι`

### Templates and their expansions
βλφρ = δείτε την έκφραση:
αρχ = αρχαία ελληνική
μσν = μεσαιωνική ελληνική
μτφρ = (μεταφορικά)
μτβ = (μεταβατικό)

**Comment by chopinesque** [comment]
I got a suggestion from the AI system "Consider using a dictionary to map template names to phrases to reduce code repetition." to deal with code like this:

```
    if tpl == "μτφρ":
        phrase = "μεταφορικά"
        if not data["0"]:
            phrase = term(phrase)
        return phrase
```
How could that be implemented?

**Comment by BoboTiG** [comment]
Do not worry about that for now. For a first pass, your code is fine.

FTR I just disabled the bot because it way too verbose , and reviews are made more difficult.

**Comment by BoboTiG** [comment]
And thanks for the patch 🍾 !
