### ISSUE TITLE
[FR] Retrieve all italic templates

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#200]
- Wiktionary page: https://fr.wiktionary.org/wiki/basse

Wikicode:
```
{{instruments à cordes|fr}}
```

Output:
```
<i>(Instruments à cordes)</i>
```

Expected:
```
<i>(Musique)</i>
```

**Comment by lasconic** [comment]
It seems all these templates (instruments à cordes, divinités...) could be imported from https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:Mod%C3%A8les_de_domaine_d%E2%80%99utilisation no ?

**Comment by BoboTiG** [comment]
You are right. I was too lazy to do that at the time. Maybe a simple Python scrapper would work? The thing is that (it seems to me) we need to click on each and every word to get the real "them" to use. This can be done one-time and we would keep the code in the Wiki for later needs, WDYT?

**Comment by lasconic** [comment]
> WDYT?

:) 

See https://gist.github.com/lasconic/391f19dffac8605b6f5fa4c7a3c40d96 for the scaper code and the result... What do you want to do with it ?

**Comment by BoboTiG** [comment]
💪 

As there is scraping, I would love to see that object moved to its own file, like done with `langs.py` (with the same kind of docstring, I will provide a Wiki link when the script will be finalized): https://github.com/BoboTiG/ebook-reader-dict/blob/ad489932448c3f001b22ea7674f85972aa180cbd/scripts/lang/fr/__init__.py#L192

As done with `langs.py`, adding the number of entries in the dict would be cool.

Also, no need for the `term`, just generate the same list of the one existent, while keeping it sorted.

**Comment by BoboTiG** [comment]
The original dict contains more than just ones from the new list. So you should move the result of the scraping into its own file and do something like that in `fr/__init__.py`:
```python
templates_italic = {
    **basic_italic_templates,  # or whatever fitting your mind
    "abréviation": "Abréviation",
    # ...
}

**Comment by lasconic** [comment]
Unfortunately, this last bit doesn't always work. `templates_italic` is dealt with here: https://github.com/BoboTiG/ebook-reader-dict/blob/master/scripts/utils.py#L366 and in the case of `divinités`(see issue #197) it will not work since len(parts) > 1.
An other suggestion ?

**Comment by lasconic** [comment]
For the moment, I made a special case for "divinités". See PR#206

**Comment by BoboTiG** [comment]
The way you handled "divinités" is the right one ;)

I will review your PR tomorrow 👍

**Comment by lasconic** [comment]
The gist is updated : https://gist.github.com/lasconic/391f19dffac8605b6f5fa4c7a3c40d96

**Comment by BoboTiG** [comment]
=> https://github.com/BoboTiG/ebook-reader-dict/wiki/%5BFR%5D-Parsing-the-domain-templates
