### ISSUE TITLE
What is your Kobo firmware?

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#202]
We would like to add new features that would break the support for old Kobo firmware (like #54). We first need some metrics before doing that.

Could you add a reaction to that message with:
- 👍 if your are using a firmware >= 4.20
- 👎 if you are using a firmware < 4.20

Thanks a lot :)

**Comment by lasconic** [comment]
👍

**Comment by patalex74** [comment]
👍

**Comment by akorx** [comment]
I think a lot of people who upgrade their dictionay are "geeks", so they upgrade the firwmare too...

**Comment by akorx** [comment]
👍

**Comment by patalex74** [comment]
👍

**Comment by BoboTiG** [comment]
Thanks, let's move froward and support 4.24+.

**Comment by akorx** [comment]
What will be the new functions?

**Comment by BoboTiG** [comment]
Nothing big:
- the dictionary signature is not part of each word definition in the HTML but into the ZIP comment (it generates smaller files)
- maybe the handling of the `<math>` HTML tag (#54) that would crash firmwares < 4.20.
