### ISSUE TITLE
[ru] Ru dictionary is not found - dead links

### ISSUE THREAD

**Issue by kyxap** [BoboTiG/ebook-reader-dict#2031]
Hi there,

I wandering if there any issue with ru dics since I can't download it, getting `Not Found`

All links from: https://github.com/BoboTiG/ebook-reader-dict/blob/master/docs/ru/README.md  seems to be broken.

Wound appreciate any help, thanks

**Comment by BoboTiG** [comment]
Duplicate of #1888.
