### ISSUE TITLE
Investigate a proper font for unicode characters

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#207]
- Wiktionary page: https://fr.wiktionary.org/wiki/fez

Arabic characters from the etymology are not well printed on a (french-configured) Kobo. It only displays squares.
I think a custom firmware with custom configuration may allow to use another font, let's check that and recommend an appropriate (and hopefully universal) font for all unicode characters.

**Comment by lasconic** [comment]
It is indeed possible to patch to change the dictionary font.
See https://www.mobileread.com/forums/showpost.php?p=3521137&postcount=48 
and https://www.mobileread.com/forums/showthread.php?t=333428 for 4.24.15676

**Comment by lasconic** [comment]
A possible solution for everyone (meaning not only patchers) would be to generate images for the unsupported scripts...

**Comment by BoboTiG** [comment]
We would then lose the support for firmwares < 4.20 (cf #54).

But even without that, I am not a big fan of such workaround. For math symbols, this is clearly the only way, but for unicode characters, this is a bad thing.

**Comment by BoboTiG** [comment]
I just tried those fonts, and none displayed arabic characters:
- sans-serif
- Gill Sans
- Kobo Nickel (my new default :)
- Bookerly

**Comment by BoboTiG** [comment]
I have a very nice result with the [Amiri font](https://www.amirifont.org/). Follow [those steps](https://www.mobileread.com/forums/showpost.php?p=3400706&postcount=28) to download and rename files accordingly. Copy font files into your Kobo, inside the "fonts" folder at the root. If it does not exist, create it.

Then in the kobopatch "Dictionary text font-family/font-size/line-height", add this line:
```yaml
  - ReplaceString: {Offset: 54, Find: "Georgia ", Replace: "Amiri   ", MustMatchLength: yes}
```

Output:
![screen_001](https://user-images.githubusercontent.com/2033598/99187260-cd992000-2755-11eb-8fe7-752fbaf04844.png)

**Comment by BoboTiG** [comment]
I am now looking at a complete font that would support more unicode characters.

**Comment by lasconic** [comment]
My goto unicode font is FreeSerif from [Freefont](https://www.gnu.org/software/freefont/).
You can download a TTF here : http://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip

**Comment by BoboTiG** [comment]
Great one, I adapted it 👍 

![screen_001](https://user-images.githubusercontent.com/2033598/99187854-4352bb00-2759-11eb-9f4b-86c72f3b284d.png)
![screen_002](https://user-images.githubusercontent.com/2033598/99187855-46e64200-2759-11eb-935d-65ea2a26a215.png)

**Comment by lasconic** [comment]
Nice.
A good test epub for Unicode support: http://www.jonnoring.net/unicode-test-publication-v001.epub

**Comment by BoboTiG** [comment]
I will test it tomorrow 👍

**Comment by BoboTiG** [comment]
Note to myself: add the wiki entry.

**Comment by BoboTiG** [comment]
First draft here: https://github.com/BoboTiG/ebook-reader-dict/wiki/HOWTO-Use-custom-font-on-Kobo
