### ISSUE TITLE
[EN] Remove positioning code before rendering

### ISSUE THREAD

**Issue by benasocj** [BoboTiG/ebook-reader-dict#2073]
- Wiktionary page: https://en.wiktionary.org/wiki/scourge

When looking up "scourge" in StarDict format some `class="floatright"` text is being shown on the top which should not be visible:
```
scourge
/skɜɹd͡ʒ/, /skɜːd͡ʒ/
{| class="floatright"

|-

|

|

|}

in a museum.

From Middle English scourge (“a lash, whip, scourge; affliction, calamity; person who causes affliction or calamity; shoot of a vine”), and then either:
...
```
Sorry for not providing things like Wikicode or the output of the script since I don't know how to use them.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/ebook-reader-dict/issues/2073">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/2073/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/2073/pledge.svg">
</picture>
</a>

**Comment by BoboTiG** [comment]
Here is the wikicode:

```
===Etymology 1===
{| class="floatright"
|-
| {{PIE word|en|h₁eǵʰs}}
| {{PIE word|en|ḱóm}}
|}{{root|en|ine-pro|*(s)ker-|id=cut|*h₃reǵ-}}
[[File:Karwats.jpg|thumb|A scourge ''(noun {{senseno|en|whip}})'' [[exhibit#Verb|exhibited]] in a [[museum#Noun|museum]].]]
```

**Comment by lasconic** [comment]
Unfortunately, it's not that easy. At this point, in clean() we only get one line at a time... We could remove tables in adjust_wikicode() with `code = re.sub(r"\{\|.*?\|\}", "" , code, flags=re.DOTALL)` but that would remove every tables (might be bad for variants search for example, see https://github.com/BoboTiG/ebook-reader-dict/issues/2085 ... Maybe do it in adjust_wikicode for english only ?

**Comment by BoboTiG** [comment]
:thinking: I think we support tables for French only as of now, correct?

Your suggestion seems fine: adapting `adjust_wikicode()` only for English, and see if we loose words, or if any errors pop up.
