### ISSUE TITLE
[FR] Redirect plural of a noun to singular or to a verb if it exists ?

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#208]
Several french words can be plural names or form of a verb. Currently with the fix for #167, we redirect to the verb for these words. 

Examples:
* minutes
* grises
* courses

**Comment by BoboTiG** [comment]
It is a shame we lose one or the other form. Should we "merge" definitions of "minuter" and "minute" for "minutes"? Something like:
```
minutes \pron\ genre

<u>Verbe</u>

(etymology)

- def 1
- def 2

<u>Nom</u>

(etymology)

- def 1
- def 2
```

I am not sure at all, just exposing an idea.

Another idea would be to append a definition to the noun: "Conjugaison du verbe <b>minuter</b>.". Like that, the whole definition is present and also a simple tap on the verb will redirect to its definition.

Do you have another idea? Or should we just say we use the noun/verb only.

**Comment by lasconic** [comment]
> Another idea would be to append a definition to the noun: `Conjugaison du verbe <b>minuter</b>.`. Like that, the whole definition is present and also a simple tap on the verb will redirect to its definition.

Really? Tap on a word in a definition doesn't work for me. It does for you ?

I guess your proposal is the best. 
It means we need to detect verb form with a s at the end. Remove the "s" and check if the word exists. If it does, then we shouldn't store this form as a variant of the infinitive but instead store it as a word with both definition... Quite involved...

**Comment by BoboTiG** [comment]
> Really? Tap on a word in a definition doesn't work for me. It does for you ?

From a definition, I can long-tap on a word to have a second definition. This will not work further though.

> I guess your proposal is the best.
> It means we need to detect verb form with a s at the end. Remove the "s" and check if the word exists. If it does, then we shouldn't store this form as a variant of the infinitive but instead store it as a word with both definition... Quite involved...

We can detect the singular with a regex. For example, [soleils](https://fr.wiktionary.org/wiki/soleils):
```
# ''Pluriel de'' [[soleil]].
```

**Comment by lasconic** [comment]
I did a check like this:

```python
# For each word, we have a variant field if the word is "pure verb form" (it does have other section than "Forme de verbe")
def make_variants(words: Words) -> Variants:
    """Group word by variant for later HTML creation, see save()."""
    variants: Variants = defaultdict(list)
    for word, details in words.items():
        details = Word(*details)
        # Variant must be normalized by trimming whitespace and lowercasing it.
        variant = details.variant.lower().strip()
        if variant:
            variants[variant].append(word)
            if word.endswith("s"): #crude detection of plural
                singular = word[:-1]
                maybe_noun = words.get(singular) #do we have the singular?
                if maybe_noun and not Word(*maybe_noun).variant: #make sure we are not redirecting to a verb (je mange, tu manges)
                    #verb for is also a singular noun
                    print(singular + "  --  " + variant)

    return variants
```

Result: https://gist.github.com/lasconic/8438230f4f79bb0d21ed7adea723ad54

**Comment by lasconic** [comment]
What's your firmware version ? Long tap doesn't work here with the latest firmware.

**Comment by BoboTiG** [comment]
The check is almost good, but it will miss "x" (travail -> travaux) and maybe some corner-case I am not aware of. But updating the condition with "x" should do the trick for most of the words I guess.

I am using Kobo 4.20.14622. I should upgrade to 4.24 when I can.

**Comment by lasconic** [comment]
The intersection between plural of noun and verb form ending in x is probably very small to inexistent.

**Comment by BoboTiG** [comment]
Ah yes, very small win :)

**Comment by lasconic** [comment]
Another interesting one...
* [grognasses](https://fr.wiktionary.org/w/index.php?title=grognasses). It should display the definition of grognasse, grogner and grognasser

I'm not really sure how to test all these cases (and the cases highlighted [here](https://github.com/BoboTiG/ebook-reader-dict/issues/215#issuecomment-725433705)) since they rely on kobo implementation. Is there an open source implementation of the search algorithm ?

**Comment by BoboTiG** [comment]
It will not be an easy one for sure. I am not aware of an open-source implementation of the algorithm, out best guest is what is done in [dictutil](https://github.com/pgaskin/dictutil). Also, by enabling logs in the Kobo, we can see a small part of what is being searched for each words, but this is light.

**Comment by lasconic** [comment]
I had a working implementation and I found an exception... 

suis -> sui, être, suivre

Also, the implementation (similar to [this one](https://github.com/BoboTiG/ebook-reader-dict/issues/215#issuecomment-725433705)) would display "suis" three times and the definition of sui, être, suivre... without the word "sui", "être" etc...

**Comment by BoboTiG** [comment]
I am more and more thinking we need to clearly separate definitions for each word (noun, verb, adjective, ...). Let's say we already had that level of details, it would ease to manipulate definitions to split/merge and display only revelant ones depending of the case.

That would require a lot of rewriting just to achieve the separation stuff. But then, it would unlock more specific outputs.

I am also more and more thinking the current code is too complex and not customizable. It will quickly become spaghetti, if it is not already the case :)

**Comment by BoboTiG** [comment]
We can try without a big refactoring, do you think you could achieve a better result by changing the `WORD_FORMAT` template and crafting the HTML for a whole word in `convert.py`? That would allow us to display the current word with its (sub)definitions. Here, instead of having three times "suis", we would be able to print "sui, être, suivre".

OR I am mistaken everything and it is the Kobo that controls the display?

**Comment by lasconic** [comment]
> I am more and more thinking we need to clearly separate definitions for each word (noun, verb, adjective, ...). Let's say we already had that level of details, it would ease to manipulate definitions to split/merge and display only revelant ones depending of the case.

Huge +1

> That would require a lot of rewriting just to achieve the separation stuff. But then, it would unlock more specific outputs.
> 
> I am also more and more thinking the current code is too complex and not customizable. It will quickly become spaghetti, if it is not already the case :)

It was quite clear before I started touching it :) but yes, it's slowly getting there.

**Comment by lasconic** [comment]
> We can try without a big refactoring, do you think you could achieve a better result by changing the `WORD_FORMAT` template and crafting the HTML for a whole word in `convert.py`? That would allow us to display the current word with its (sub)definitions. Here, instead of having three times "suis", we would be able to print "sui, être, suivre".
> 
> OR I am mistaken everything and it is the Kobo that controls the display?

No need to craft the whole word I believe. We would just need to output "word" in the "name" attribute and whatever we want in the <b></b> after that. I will have a look...

**Comment by BoboTiG** [comment]
Let's tackle the biggest majority of words and we will handle "suis" and other specific cases later.

**Comment by BoboTiG** [comment]
Could you try to keep 100% of coverage? 🙏 
The new variants code is not tested :/

```
scripts/convert.py                      137      7    95%   186-192
```

**Comment by BoboTiG** [comment]
Your last patch work like a charm. "duss" returns finally "devoir" 💪

**Comment by BoboTiG** [comment]
I also checked "grognasses" and "suis". The dictionary is killer now, thanks a lot for you work :)
