### ISSUE TITLE
[FR] Handle verb forms with two first letters different from infinitive

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#210]
A few verbs in french change dramatically when they are conjugued. Currently, if a verb form doesn't have the same two letters than the infinitive, they are not found.

List of verbs: https://gist.github.com/lasconic/d3fde4a6155528647703314153b2a8f7

**Comment by BoboTiG** [comment]
Is it expected to have "s’abstenir" instead of "abstenir" in your list?

**Comment by lasconic** [comment]
No it's not but that's a bug for wiktionary. Same for `variant :'verbes' : word : 'somment'`. I tried to fix this one.

**Comment by BoboTiG** [comment]
Surprinsignly, there is not change in the words count before and after the patch. I thought there would be more words taken into account 🤔 
See [yesterday](https://github.com/BoboTiG/ebook-reader-dict/runs/1371665987?check_suite_focus=true) and [today](https://github.com/BoboTiG/ebook-reader-dict/runs/1377253449?check_suite_focus=true).

(And when checking those logs, I saw new errors: upcoming tickets :)

**Comment by lasconic** [comment]
This is weird. I just tested on my device and the verb forms are found when I search in the dictionary: meaning I get an autocomplete but no definition is displayed. I do see a definition in the HTML file once gunzipped though. I will try to investigate.

**Comment by lasconic** [comment]
Ok. I didn't test on my device with the right dictionary... It does work.



> Surprisingly, there is no change in the words count before and after the patch. I thought there would be more words taken into account 🤔
If you compare the word count in data.json, it's normal. The PR only changed the convert step.
