### ISSUE TITLE
Improve auto-update scripts robustness

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2122]
In the past, several auto-update commits removed lot of data.
Latest examples are:
- 603cd2860d2973f5529deff7f1a9902c414c6ff2
- 6dc86ea0cd5dc191b0f2f00b798d3fd9d3001bcc

I think we should find a way to prevent such deletions.

First idea, I would propose to do a check on entries counts before, and after, a script is run: if the difference is like >= 1%, then raise a `ValueError("Too many deletions, please check manually.")` exception.

I'm also open to suggestions, as always :)

**Comment by lasconic** [comment]
File size or line count maybe ?

**Comment by BoboTiG** [comment]
I was thinking of lines count.

**Comment by BoboTiG** [comment]
I'll try something, if you are not yet working on it on your side.

**Comment by lasconic** [comment]
I'm not
