### ISSUE TITLE
[ES] Ignore "ejemplo" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2135]
- Wiktionary page: https://es.wiktionary.org/wiki/vellosidad

**Comment by BoboTiG** [comment]
Well, the Spanish wiki is under heavy lifting, this page now displays a big red error:

> Error de Lua en Módulo:contexto en la línea 55: attempt to concatenate global 'leng_upper' (a nil value).

So I cannot test my changes. Therefore, I'll push a commit when they will fix the mess.

**Comment by lasconic** [comment]
If only they could change the spanish wiki so it looks more like the other ones :)

**Comment by BoboTiG** [comment]
> If only they could change the spanish wiki so it looks more like the other ones :)

So true haha :100:
