### ISSUE TITLE
[ES] "es-campos-semanticos" script error

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2140]
```python
Traceback (most recent call last):
  File "scripts/es-campos-semanticos.py", line 52, in <module>
    next_page_url = process_cs_page(next_page_url, results)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/es-campos-semanticos.py", line 27, in process_cs_page
    last_link = nextpage_div.find_all("a")[-1]
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by BoboTiG** [comment]
:thinking:  https://es.wiktionary.org/wiki/Categor%C3%ADa:Plantillas_de_campo_sem%C3%A1ntico is now empty, that explains why.

**Comment by BoboTiG** [comment]
It seems to have moved to https://es.wiktionary.org/wiki/M%C3%B3dulo:auto_cat/campos_sem%C3%A1nticos.

**Comment by lasconic** [comment]
Yes, looks like it.
Also see https://es.wiktionary.org/wiki/Wikcionario:Lista_de_etiquetas

**Comment by BoboTiG** [comment]
> Yes, looks like it. Also see https://es.wiktionary.org/wiki/Wikcionario:Lista_de_etiquetas

We can use the data directly: https://es.wiktionary.org/wiki/M%C3%B3dulo:contexto/csem
