### ISSUE TITLE
Support multiple pronunciations

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#216]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=pas

Wikicode:
```
'''pas''' {{pron|pa|fr}}, {{pron|pɑ|fr}} {{m}}
```

Output:
```
\pa\ 
```

Expected:
```
\pa\, \pɑ\
```

---

**Comment by lasconic** [comment]
We could change "search" by "findall" here: https://github.com/BoboTiG/ebook-reader-dict/blob/89d1271b673cd05f02edafc1e74cc0738916c8bb/scripts/get.py#L262

But we will find all prononciation of word, independently of his classes (noun, verb etc...)

**Comment by BoboTiG** [comment]
I have a possible fix for that.
