### ISSUE TITLE
[RO] Investigate why the number of words is so small

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2241]
I bet we are missing several head sections.

Current state with the Wiktionary dump of 2024-10-20 is `96,342` / `96,812`, but there are [168,444](https://ro.wiktionary.org/wiki/Special:Statistici) referenced words so far.

**Comment by lasconic** [comment]
Maybe the missing words are non RO ones ? Like https://ro.wiktionary.org/wiki/caprimulgus  ?

**Comment by BoboTiG** [comment]
Yup, maybe. The difference seems a little too large, I'll be able to have a look today or tomorrow, at least just to confirm we are OK.

**Comment by BoboTiG** [comment]
New state is `96,556` / `97,026`. Not much, you were right about non-RO words :muscle: :)
