### ISSUE TITLE
[EL] Adjust output of "*" template

### ISSUE THREAD

**Issue by chopinesque** [BoboTiG/ebook-reader-dict#2247]
- Wiktionary page: https://el.wiktionary.org/w/index.php?title=%CE%B1%CF%83%CF%84%CE%AD%CF%81%CE%B9
- Model link: https://el.wiktionary.org/w/index.php?title=%CE%A0%CF%81%CF%8C%CF%84%CF%85%CF%80%CE%BF:*&action=edit

This template (context in that page `ελληνιστική κοινή *ἀστέριον`) directs to the γλωσσολογία page (not necessary in our case) and has a tooltip "`αμάρτυρος υποθετικός τύπος (ή αντιγραμματικός)`" (meaning "a non-attested form")

**Comment by BoboTiG** [comment]
Currently it renders as https://github.com/BoboTiG/ebook-reader-dict/blob/4db5a40cbda3ac85eed3bed3f0c9434c982e0fe1/wikidict/lang/el/__init__.py#L94

I guess, a better support would be to simply ignore the template. It is not useful to display a "*" in the text.

**Comment by chopinesque** [comment]
Just replace with a normal asterisk symbol (not big), it is standard to indicate such words, see https://linguistics.stackexchange.com/questions/338/meaning-of-star-asterisk-in-linguistics

Currently the output on Stardict is: `{{*}}`

**Comment by BoboTiG** [comment]
A simple asterisk symbol is fine, yes 👍
