### ISSUE TITLE
[EL] Exclude pages with template {{λείπει ο ορισμός}}

### ISSUE THREAD

**Issue by chopinesque** [BoboTiG/ebook-reader-dict#2248]
- Wiktionary page: https://el.wiktionary.org/wiki/%CF%83%CE%BA%CE%B9%CE%BF%CF%83%CE%BA%CF%8C%CF%80%CE%B9%CE%BF
- Model link: 

The page above has a definition, however, what I see in my Stardict file is: 

```
"σκιοσκόπιο","<i>ουδέτερο</i>.
<ol><li>{{λείπει ο ορισμός}}</li></ol><p><b>σκιοσκόπιο</b> <</p></html>"
```
Looks like page was updated 3rd of November and the file I downloaded is not that recent.

`λείπει ο ορισμός` means definition missing, 997 matches

  How can we exclude all entries that contain a specific template, this one for example? `{{λείπει ο ορισμός}} `
https://el.wiktionary.org/wiki/%CE%A0%CF%81%CF%8C%CF%84%CF%85%CF%80%CE%BF:%CE%BB%CE%B5%CE%AF%CF%80%CE%B5%CE%B9_%CE%BF_%CE%BF%CF%81%CE%B9%CF%83%CE%BC%CF%8C%CF%82

**Comment by BoboTiG** [comment]
Yes, you can add the template to this list: https://github.com/BoboTiG/ebook-reader-dict/blob/4db5a40cbda3ac85eed3bed3f0c9434c982e0fe1/wikidict/lang/el/__init__.py#L69

**Comment by chopinesque** [comment]
Thanks, does that mean than the specific template will disappear from the entry or that the whole entry will be excluded?

**Comment by BoboTiG** [comment]
Only the template will be discarded. If there are ther definitions, they will be included as usual.

**Comment by BoboTiG** [comment]
No need to do something special. As there will be no definitions, then the word will not be included on the dict.

For instance, lets say a word contains both a noun and a verb sections. If the noun has only the missing definition template, and the verb might have valid definitions, then the word will be included on the dict.

So the easy way, as we do for all locales, is to ignore the template, and the process will take care of keeping the word if relevant data is still present.
