### ISSUE TITLE
[EL] Support "θηλ του" template

### ISSUE THREAD

**Issue by chopinesque** [BoboTiG/ebook-reader-dict#2255]
- Wiktionary page: https://el.wiktionary.org/wiki/%CF%84%CF%83%CE%B9%CE%B3%CE%B3%CE%AC%CE%BD%CE%B1

It is displayed in wiki code as `{{θηλ του|τσιγγάνος}}` (feminine of τσιγγάνος) the expansion should be `θηλυκό του [[τσιγγάνος]]` (with the word linked).

- Model link:  https://el.wiktionary.org/wiki/%CE%A0%CF%81%CF%8C%CF%84%CF%85%CF%80%CE%BF:%CE%B8%CE%B7%CE%BB_%CF%84%CE%BF%CF%85

**Comment by chopinesque** [comment]
When I test it I get

```
τσιγγάνα  '<i>θηλυκό</i>.'

[variants] τσιγγάνος

```
Whereas it should be

```
τσιγγάνα  '<i>θηλυκό του</i>'  τσιγγάνος

```

**Comment by BoboTiG** [comment]
That's expected. We do that for other locales as well: when you pick a flexion of a word, its "original" form is set in the variants. If there are additional etymology/definitions, they are displayed. And on supported devices like Kobo, the "original" form is also displayed.

**Comment by chopinesque** [comment]
The point is that it should say <i>θηλυκό του</i> and not just <i>θηλυκό</i>

**Comment by BoboTiG** [comment]
Oh, I didn't get that.

Actually, the first line is composed as is:

```
WORD [/PRONUNCIATION/[, /PRONUNCIATION/, ...] '<i>GENGER</i>'[, '<i>GENGER</i>', ...]
```

For GENDERs, we have either "f." or "feminine", "n." or "neutral", etc. But no sentence or full definition like "feminine of xxx".
