### ISSUE TITLE
[FR] Support "ruby" template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#2268]
- Wiktionary page: https://fr.wiktionary.org/wiki/awamori
- Model link: https://fr.wiktionary.org/wiki/Mod%C3%A8le:ruby

**Comment by lasconic** [comment]
Wow, I didn't know these tags ! Now I'm curious. Does kobo browser support the <ruby> and <rt> HTML tags ?
https://www.w3schools.com/tags/tag_ruby.asp

**Comment by BoboTiG** [comment]
Same fo me, it is surprising!

I'll try them right now.
