### ISSUE TITLE
[FR] Handle "graphie" Template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#236]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=huit

Wikicode:
```
{{graphie|h}}
```

Output:
```

```

Expected:
```
‹ h ›
```

---

Template link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:graphie

**Comment by lasconic** [comment]
graphie is listed in template_ignored because of https://github.com/BoboTiG/ebook-reader-dict/issues/44

I guess this is because  ् for example is not part of the default font ?

The thing is `graphie` is used with other valid chars like h in [huit](https://fr.wiktionary.org/w/index.php?title=huit), û in [piqûre](https://fr.wiktionary.org/w/index.php?title=piqûre) etc...

If the problem is the font, then I would handle it anyway, and redirect to https://github.com/BoboTiG/ebook-reader-dict/issues/207 if anyone complains :)

**Comment by BoboTiG** [comment]
Let's go then 👍 
Hopefully FreeSerif will handle it :)
