### ISSUE TITLE
[FR] Sub sub list not handled correctly

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#237]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=marron

Wikicode:
```
# {{par analogie|fr}}
## {{term|de couleur}}
### [[brun|Brun]], couleur du fruit [[mûr]]. 
```

Output:
```
3. (Par analogie)
      a. (De couleur)
```

Expected:
```
2. (Par analogie)
      a. (De couleur)
            i. Brun, couleur du fruit mûr
```

---

Model link, if any:

**Comment by lasconic** [comment]
FWIW, this is different from issue #73. Here the lists are hierarchical, so we should be able to handle it.

**Comment by BoboTiG** [comment]
Great, I never encountered such subsublist. Should we take care of possible subsubsublist also? :)

**Comment by lasconic** [comment]
base.wiki has one. I believe we are safe with subsub for now ;) but I could be wrong
