### ISSUE TITLE
[FR] Handle "agglutination" template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#239]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=aujourd%E2%80%99hui

Wikicode:
```
{{agglutination|fr|m=1}}
```

Output:
```

```

Expected:
```
agglutination
```

---

Template link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:agglutination

**Comment by BoboTiG** [comment]
Are you working on it?

**Comment by lasconic** [comment]
No, but it seems there are a few other here https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:Mod%C3%A8les_%C3%A9tymologiques that we don't handle and behave more or less the same than "dénominatif"

**Comment by lasconic** [comment]
For example [gendarme](https://fr.wiktionary.org/w/index.php?title=gendarme)
{{univerbation}} https://fr.wiktionary.org/wiki/Mod%C3%A8le:univerbation. Maybe we should deal with all of them at once ?

**Comment by lasconic** [comment]
Ok. I'm working on it.

**Comment by BoboTiG** [comment]
To ease our workflow, assign issues to yourself when you want to work on it ;)
