### ISSUE TITLE
[FR] Handle 'Unité' template (capital U...)

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#254]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=katana

Wikicode:
```
{{Unité|60|cm}})
```

Output:
```

```

Expected:
```
60 cm
```
Note the space !
---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:Unit%C3%A9

**Comment by BoboTiG** [comment]
I have an idea to fix all those capital issues, let me try something :)

**Comment by BoboTiG** [comment]
Nope, my idea was wrong, let's handle those templates case by case then.
