### ISSUE TITLE
[FR] Handle 'phon' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#255]
- Wiktionary page: https://fr.wiktionary.org/wiki/cheval

Wikicode:
```
{{phon|u|fr}}
```

Output:
```

```

Expected:
```
[u]
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:phon

**Comment by BoboTiG** [comment]
It seems more that we should display bolder letter, right?
```
<b>[u]</b>
```

The font-weight is not really bold but for the Kobo we can say it is OK, WDYT?

**Comment by lasconic** [comment]
Sure, let's see how it looks. For a full word see https://fr.wiktionary.org/w/index.php?title=natchez
