### ISSUE TITLE
[FR] Meta issue : handle empty templates

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#257]
There are still a few templates with empty result: https://gist.github.com/lasconic/aee4e2cb467d94a79db5e54bc6d7d7f2

**Comment by BoboTiG** [comment]
Ah yes, quite a lot! Out of curiosity, could you share the code you used to generate that list? It may be useful for other locales.

**Comment by lasconic** [comment]
```
def transform(word: str, template: str, locale: str) -> str:
    parts_raw = [p for p in template.split("|") if not p.startswith("lang=")]
    parts = [p.strip() for p in parts_raw]
    parts = [p.strip("\u200e") for p in parts]  # Left-to-right mark
    tpl = parts[0]

    # {{formatnum:-1000000}}
    if ":" in tpl:
        parts_raw = template.split(":")
        parts = [p.strip() for p in parts_raw]
        tpl = parts[0]

    # Help fixing formatting on Wiktionary (some templates are more complex and cannot be fixed)
    if parts != parts_raw and tpl not in templates_warning_skip[locale]:
        warn(f"Extra character found in the Wikicode of {word!r} (parts={parts_raw})")

    # Convert *parts* from a list to a tuple because list are not hashable and thus cannot be used
    # with the LRU cache.
    result: str = transform_apply(word, tpl, tuple(parts), locale)
    if not result and tpl not in templates_ignored[locale] and not tpl.startswith("?"):
        print("----->>> " + word)
        print(template)
    return result
```

**Comment by BoboTiG** [comment]
Hm maybe should we use such thing to help improving locale support. Thanks!

**Comment by BoboTiG** [comment]
I am done for today, what a productive one 💪 

Do you mind updating the gist? I will see if I can find some time tomorrow to tackle some templates (and review your potential PRs).

**Comment by lasconic** [comment]
I will try updating the git but so far I see no output at all... weird.

**Comment by lasconic** [comment]
Down to 310 lines for about 55 templates. 
I couldn't make it work with DEBUG=1 (no output, not even warning...) but I defined debug=True in the function...

**Comment by BoboTiG** [comment]
Running that command is printing the message:
```shell
DEBUG=1 python -m scripts --locale="fr" --get-word="mon"
```

**Comment by lasconic** [comment]
but somehow the following doesn't for me

```
DEBUG=1 python -Wd -m scripts --locale fr --fetch-only
```

**Comment by lasconic** [comment]
Some templates have double spaces... what do you think of replacing double spaces by simple spaces in `transform_apply`? Is there a function to do that already?

**Comment by BoboTiG** [comment]
Hm I would rather fix them on Wiktionary. I can do that right now :)

**Comment by BoboTiG** [comment]
Done ✅

**Comment by lasconic** [comment]
Good ! "etylpp" in Marrakech is fixed too. So no need to worry about this one.

**Comment by lasconic** [comment]
Same for "christianisme", it has been removed by the same "Wiktionnariste en résidence" !

**Comment by BoboTiG** [comment]
Fixing on Wiktionary is the good move, thanks to him/her :)

**Comment by BoboTiG** [comment]
OK, I broke the auto-update job and I now understand why you did not manage to have a working script with `DEBUG=1`. I will fix that ASAP.

**Comment by lasconic** [comment]
The tests are not passing on master I believe.

**Comment by BoboTiG** [comment]
Fixed now, sorry :)

**Comment by BoboTiG** [comment]
I close the issue now that almost all templates are well handled. This is an interesting way of working, we may do the same for other locales (if we have motivation and time ^^).
I let you choose the next locale, if you have a preference go ahead. I think/fear that English may need a good amount of time to handle it completely.

**Comment by lasconic** [comment]
English might surprised us. It's hopefully more structured and maintained than French.
