### ISSUE TITLE
[FR] Handle the 'familier' italic template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#306]
- Wiktionary page: https://fr.wiktionary.org/wiki/mon

Wikicode:
```
{familier|fr|nocat=1}}
```

Output:
```
None
```

Expected:
```
<i>(Familier)</i>
```

**Comment by lasconic** [comment]
Maybe there is something we can do for 
{familier|fr|nocat=1}}
{spécifiquement|fr|nocat=1}}
{génériquement|fr|nocat=1}}
etc... no ?

**Comment by BoboTiG** [comment]
About "familier", it is a simple italic templates and it should not need a specific handler. If we are sure that wehn "nocat=1" is part of the template and the first part is actually just a word to captialize + italic, then we may try something yes :)

**Comment by lasconic** [comment]
Well, right now, all the following works because we made this assumption (minus the notcat) in the defaut last_template_handler I believe.

{familier|fr}} 
{spécifiquement|fr}}
{génériquement|fr}

**Comment by BoboTiG** [comment]
What do you propose? If you try something, go ahead ;)

**Comment by lasconic** [comment]
I tried the following but it would hide this one https://github.com/BoboTiG/ebook-reader-dict/issues/312.. So let's handle them all...
```
    if len(parts) == 1 and len(data) == 1 and data['nocat']:
        return term(capitalize(lookup_italic(tpl, locale)))
```

**Comment by BoboTiG** [comment]
Yeah, there are always exceptions. We are almost finished, addng 3 more is not a big deal IMO.
