### ISSUE TITLE
[FR] Handle "cit_réf" / "cit réf" template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#323]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=baboune

Wikicode:
```
{{cit_réf|Rabelais|Quart livre, c 56, 1552}}
```

Output:
```

```

Expected:
```
<i>Rabelais</i>, Quart livre, c 56, 1552
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:cit_r%C3%A9f

**Comment by BoboTiG** [comment]
Should we handle or ignore it? It seems like other citation templates we are actually ignoring 🤔

**Comment by lasconic** [comment]
it's only one article but here we have empty parenthesis () in the text if we ignore it. It's your call ;)

**Comment by BoboTiG** [comment]
Empty parentheses is not what we want. Let's handle it then :)

**Comment by BoboTiG** [comment]
And maybe "cité_ref" should be fixed on Wiktionary directly. (And here my last patch that removed printing all templates is not helping... :)
