### ISSUE TITLE
[FR] Add support for the 'Deva' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#343]
- Wiktionary page: https://fr.wiktionary.org/wiki/d%C3%A9vanagari

Wikicode:
```
{{Deva|[[देव]]|deva|divin}}
```

Output:
```
None
```

Expected:
```
देव
```

---

Model: https://fr.wiktionary.org/wiki/Wiktionnaire:BCP_47/script-A

**Comment by lasconic** [comment]
Do we really need it or we only edit the 3 occurences of Deva in https://fr.wiktionary.org/wiki/d%C3%A9vanagari ?

**Comment by BoboTiG** [comment]
I would say to no alter the word on the Wiktionary.

Let's see if we encounter such templates in other locales before working on it.
