### ISSUE TITLE
Clean-up <<foo/bar>> wikicode

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#349]
- Wiktionary page: https://en.wiktionary.org/wiki/Iraq

Wikicode:
```
<<country>>
<<region/Middle East>>
<<capital/Baghdad>>
```

Output:
```
<<country>>
<<region/Middle East>>
<<capital/Baghdad>>
```
And as the Kobo renders HTML, the user will only see:
```
>
>
>
```

Expected:
```
country
Middle East
Baghdad
```

**Comment by lasconic** [comment]
See also in french 
Citation/Amélie Nothomb/Pétronille 
Citation/Amélie Nothomb 

in https://fr.wiktionary.org/w/index.php?title=Acariaz
