### ISSUE TITLE
[EN] Handle the 'doublet' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#353]
- Wiktionary page: https://en.wiktionary.org/wiki/word#Etymology_1

Wikicode:
```
{{doublet|en|verb}}
```

Output:
```
<i>Doublet</i> <b>verb</b>
```

Expected:
```
Doublet of <i>verb</i>.
```

---

Model link: https://en.wiktionary.org/wiki/Template:doublet

**Comment by lasconic** [comment]
Also handle https://en.wiktionary.org/wiki/Template:piecewise_doublet in the same PR
