### ISSUE TITLE
[FR] Support for e/ème/er/ère templates

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#354]
- Wiktionary page: 

Wikicode:
```
XVI{{ème}}
```

Output:
```
XVI<i>Eme</i>
```

Expected:
```
XVIe
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:e

**Comment by lasconic** [comment]
I found this one by logging the templates in the `last_template_handler` in defaults.py just before the return. I'm sure there is still many templates we don't support that can be discovered like this.

**Comment by BoboTiG** [comment]
Good catch. The whole `e` template needs more tests, it only handle a few cases.

**Comment by lasconic** [comment]
https://fr.wiktionary.org/wiki/Mod%C3%A8le:1er can probably be handle with them.

See https://fr.wiktionary.org/wiki/tromp%C3%A8-je

**Comment by lasconic** [comment]
In the same line, we need to support https://fr.wiktionary.org/wiki/Mod%C3%A8le:o
See https://fr.wiktionary.org/wiki/Vitrolles-en-Lub%C3%A9ron

**Comment by lasconic** [comment]
Also 'numéro' : https://fr.wiktionary.org/wiki/Mod%C3%A8le:num%C3%A9ro
See https://fr.wiktionary.org/wiki/majorit%C3%A9_de_l%E2%80%99article_24
