### ISSUE TITLE
Add support for several magic words

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#356]
- Wiktionary page: 

Wikicode:
```
{{CURRENTYEAR}}
```

Output:
```
<i>(CURRENTYEAR)</i>
```

Expected:
```
2020
```

---

**Comment by BoboTiG** [comment]
I did not know that one. Where is it used?

**Comment by BoboTiG** [comment]
It is only used in french pages? I would more thinking of it as a global variable.

**Comment by lasconic** [comment]
It's used on this page : https://fr.wiktionary.org/wiki/apr._J.-C. (and this page only I believe)

**Comment by BoboTiG** [comment]
Hm that page does not exist.

**Comment by BoboTiG** [comment]
```
https://fr.wiktionary.org/wiki/apr._J.-C.
```
It seems GH has some issue handloing the link.

Let's add this special code, we could do it from `utils.py::clean()` I think.

**Comment by lasconic** [comment]
FWIW : https://www.mediawiki.org/wiki/Help:Magic_words#Date_and_time

**Comment by lasconic** [comment]
I also found {{PAGENAME}} in https://fr.wiktionary.org/wiki/De_Witte
