### ISSUE TITLE
[FR] Handle 'attention' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#360]
- Wiktionary page: https://fr.wiktionary.org/wiki/alternatif

Wikicode:
```
{{attention}}
```

Output:
```
<i>(Attention)</i>
```

Expected:
I don't know ... Nothing ? or unicode  ⚠  U+26A0 WARNING SIGN but the default Georgia font doesn't support it ...

---

Model link, if any:

**Comment by BoboTiG** [comment]
We can go with the unicode ⚠.
