### ISSUE TITLE
[FR] Support 'pp' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#362]
- Wiktionary page: https://fr.wiktionary.org/wiki/battue

Wikicode:
```
{{pp}}
```

Output:
```
<i>(Pp)</i>
```

Expected:
```
participe passé
```
Note, no italic

---

Model link, if any: https://fr.wiktionary.org/w/index.php?title=Mod%C3%A8le:pp

**Comment by BoboTiG** [comment]
It should be italic, no? On the Wikipage and the model page, both are italic 🤔

**Comment by BoboTiG** [comment]
I also added support for `pré` and `prés`, both in italic. Upcoming PR ⌛

**Comment by lasconic** [comment]
Yes, italic.
