### ISSUE TITLE
[EN] Parse gender string

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#377]
Many templates, including doublet and l have a "g" parameter containing a gender and number string.
See https://en.wiktionary.org/wiki/Module:gender_and_number

We need function to parse such a string and send back a meaningful string

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tiger-222) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/BoboTiG/ebook-reader-dict/issues/377">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/377/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/BoboTiG/ebook-reader-dict/issues/377/pledge.svg">
</picture>
</a>

**Comment by BoboTiG** [comment]
@lasconic I'm not sure to understand the issue :sweat_smile: 
W>ould you mind adding an example of what is missing :pray:?

**Comment by lasconic** [comment]
I don't really have an example of a non working page. It's more a potential issue. Let me try to explain.

The ["doublet" template](https://en.wiktionary.org/wiki/Template:doublet) like many others take a `gN` parameter. This parameter can be a 'complex' string that needs to be parsed according to https://en.wiktionary.org/wiki/Module:gender_and_number. Right now, we don't replicate this function but we just output the string in italic. See https://github.com/BoboTiG/ebook-reader-dict/blob/master/wikidict/lang/en/template_handlers.py#L701 It works in simple cases but could break if an editor would use a more complex syntax.

Does it make sense ?

**Comment by BoboTiG** [comment]
Aaah yes, it makes sense. I didn't see the `gN` parameters of models.

**Comment by lasconic** [comment]
Example of a broken word : https://en.wiktionary.org/wiki/funeral
