### ISSUE TITLE
[EN] Handle the 'place' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#379]
- Wiktionary page: https://en.wiktionary.org/wiki/Iraq

Wikicode:
```
{{place|en|A country in the Middle East|modern=Republic of Iraq}}
```

Output:
```
<i>Place</i> <b>A country in the Middle East</b>
```

Expected:
```
A country in the Middle East; modern Republic of Iraq
```

---

Model link, if any: https://en.wiktionary.org/wiki/Template:place

**Comment by lasconic** [comment]
This one supposes quite some work if we want to support it thoroughly... It depends on several lists that needs to be scrapped...

**Comment by lasconic** [comment]
The cleanup for issue https://github.com/BoboTiG/ebook-reader-dict/issues/349 has been a bit radical.

See https://en.wiktionary.org/wiki/Saint-Domingue 

```
<<isl:pref/Hispaniola>>
```

```
island of Hispaniola
```

**Comment by lasconic** [comment]
A piece of code to get the Place types

```python
import re
import requests
from bs4 import BeautifulSoup




def get_soup(url):
    req = requests.get(url)
    page = req.content
    soup = BeautifulSoup(page, features="html.parser")
    return soup

url = "https://en.wiktionary.org/wiki/Template:place"
soup = get_soup(url)
tables = soup.find_all("table", "wikitable")

columns = ["placetype", "article", "display", "preposition", "aliases"]

placetypes = {}
print("placetypes = {")
body = tables[0].find("tbody")
trs = body.find_all("tr")
trs.pop(0) # remove header
count_alias = 0
for tr in trs:
    tds = tr.find_all("td")
    tds = [t.text.strip() for t in tds]
    tds = dict(zip(columns, tds))
    if tds:
        placetype = tds.pop("placetype", None)
        aliases = tds.pop("aliases").split(',')
        placetypes[placetype] = tds
        print(f'    "{placetype}": {{ ', end='')
        for key in tds.keys():
            print(f'"{key}": "{tds[key]}", ', end='')
        print("},")
        for alias in aliases:
            if alias:
                count_alias +=1
                print(f'    "{alias}": {{ ', end='')
                for key in tds.keys():
                    print(f'"{key}": "{tds[key]}", ', end='')
                print("},")
print("}")

print(f"# {len(trs):,} + {count_alias:,} = {len(trs) + count_alias:,}")
```

**Comment by BoboTiG** [comment]
Hm should we replace `<<` and `>>` with `{{` and `}}`, and treat that as templates? It would be more easy then, any thoughts?

**Comment by lasconic** [comment]
It's a can of worms, really... I don't know enough about this alternate notation to have a strong opinion...

Another example

wikicode 
```
<<historic caplc>>
```

expected 
```
historical capital and largest city
```

**Comment by lasconic** [comment]
Do you know if this template, "place", is the only one using this notation ?

**Comment by lasconic** [comment]
I started to work on this. My test cases are 
* https://en.wiktionary.org/wiki/Vermont
* https://en.wiktionary.org/wiki/Paris
* https://en.wiktionary.org/wiki/Iraq.

Current state: 
* the <<>> notation is not supported at all, except when it happens to work... 
* no support for additional parameters except for `modern=``
* no support for https://en.wiktionary.org/wiki/Template:place#Recognized_placenames USA -> The United State
* no support for plural of local types
* no support of probably a lot more...

**Comment by BoboTiG** [comment]
Basic support is enough for now ;)
