### ISSUE TITLE
[EN] Discover unhandled templates

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#399]
I added some code at the end of the english `last_template_handler` in order to log the templates that are rendered by default.
To limit the number of templates, I print only templates with more than 2 `parts` and with `data`, especially if `nocat` is not the only `data`

The code and the result is available here: 
https://gist.github.com/lasconic/139942e3761200eaa62e0a3a9be3d4f6
First file is the code.
Second file is the template name and the number of hits : it gives a sense of the impact if the support for a template is handled
Third file is the full list, convenient to find one or more examples of the template used on wiktionary.

I discovered a couple of templates that should be ignored: https://github.com/BoboTiG/ebook-reader-dict/issues/395
and many others that needs to be implemented...

I was not sure where to put this, so I open an issue. Please, let me know if it's not the right place.

**Comment by BoboTiG** [comment]
That's a nice way keep track of what needs to be done. There are finally quite a lot of templates :)

**Comment by lasconic** [comment]
181 ;) and a couple less with the ignored ones from #395

**Comment by lasconic** [comment]
90 done, 90 to go...

**Comment by lasconic** [comment]
To discover more unhandled templates, for English or French, we could look for template rendered by default but containing special chars like "-" or "_". They are probably rendered badly...

**Comment by lasconic** [comment]
Another idea to find unhandled or bad supported templates.
We could add a "check-word" command, it would call parse_get_word to get a list of etymology and definitions, then it would get the HTML from the wiktionary, strip HTML everywhere (definitions, and wiktionary page) and do a string search of the each definition in the page. If we don't find the definition in the page, we render it differently...
I'm not saying we should do this for all words, but maybe a random selection from time to time to detect bad rendering ? WDYT ?

**Comment by BoboTiG** [comment]
That's a nice idea!
What we could do it to select randomly N words from the JSON and call `--check-word` on it with the proposed process. And we even could add `--check-word` in-between `--parse` and `--render` steps (maybe only on the CI) to have regular checks on random data.

Indeed, the critical part of `--check-word` will be the HTML stripping and getting rid of ignored templates.

WDYT?

**Comment by BoboTiG** [comment]
What an awesome idea you had. This is a huge win! (#536, #539).

We are good to close the issue, right?

**Comment by lasconic** [comment]
Sure, let's close it

**Comment by BoboTiG** [comment]
I will add a script to call `--check-word` on N randomly words from the JSON. It promises some good moments.

**Comment by lasconic** [comment]
Glad you like the idea !
We will have quite a lot of false positives with ignored templates... see "avoir".
And fuzzy search would be convenient to show the most likely text. Maybe using https://github.com/taleinat/fuzzysearch

**Comment by BoboTiG** [comment]
With the new argument (#541), I tried to run with `2`, `20` and `100`. I got only one issue with "memento". That a good start.

I have no idea right now how we can deal with false positives. Hopefulle, some ignored templates are either at the beggining or the end of definitions.

**Comment by lasconic** [comment]
we can remove some html tags... for "avoir"

```Python
def get_wiktionary_page(word: str, locale: str) -> str:
    """Get a *word* HTML."""
    url = f"https://{locale}.wiktionary.org/w/index.php?title={word}"
    with requests.get(url) as req:
        html = req.text
        bs = BeautifulSoup(markup=html, features="html.parser")
        for a in bs.find_all("a", href=True):
            if a['href'].startswith("#cite"):
                a.decompose()
        return no_spaces(bs.text)
```

**Comment by BoboTiG** [comment]
Hm we will have to handle a lot of corner cases for all locales 🤔

**Comment by lasconic** [comment]
Who knows, maybe not :)

**Comment by BoboTiG** [comment]
:)

Another one: https://fr.wiktionary.org/wiki/alaterne.

**Comment by BoboTiG** [comment]
I will try your solution, if you are not working on it.

**Comment by BoboTiG** [comment]
FTR, I tested 1000 words and got only 5 errors (3x #543 and 2x ignored templates).

**Comment by lasconic** [comment]
Go for it

**Comment by lasconic** [comment]
You tested french only ? Or other languages too ?

**Comment by BoboTiG** [comment]
Only French for now.

**Comment by BoboTiG** [comment]
Patch merged in master.

**Comment by BoboTiG** [comment]
English is quite well handled too (tested with 200 words only). What comes out is the `prefix` template (I do not see the difference between what is on the Wiktionary and what we are rendering ... ) and verbs handling.
