### ISSUE TITLE
Fix handling of templates data containing an equal sign

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#407]
- Wiktionary page: https://en.wiktionary.org/wiki/EPR%3DER

Wikicode:
```
{{alternative form of|mul|ER{{=}}EPR}}
```

Output:
```
<i>Alternative form of</i> <b></b>
```

Expected:
```
<i>Alternative form of</i> <b>ER=EPR</b>
```

**Comment by lasconic** [comment]
Maybe an idea, mimic the parameter module : https://en.wiktionary.org/wiki/Module:parameters
