### ISSUE TITLE
Output to other formats

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#409]
The comment here : https://www.mobileread.com/forums/showpost.php?p=4061955&postcount=28
and the wiki pages 

* HOWTO Convert to mobi for the Kindle
* HOWTO Convert to StarDict

shows that there is an interest for a "small" wiktionary in other formats. 

Could we use the CI to provide more download options ? Is penelope the right tool for the job ? what about pyglossary ? Should we output a [df file](https://pgaskin.net/dictutil/dictgen/#dictfile-format) and let pyglossary do the job to convert to mobi, startdict or something else ? 

Providing more formats could also bring more eyeballs on the project, more bug reports and maybe more devs to reimplement all these wiki templates :)

**Comment by BoboTiG** [comment]
Yes, that would be a good thing to do that from our CI.

Before thinking too much on that subject, I would like to refactor the whole project to separate steps clearly and ease changing/adapting/adding stuff to one step or another. I will open a meta issue to discuss all of that.

**Comment by BoboTiG** [comment]
Out of curiosity: do you have merge rights?

**Comment by lasconic** [comment]
I believe I do but I'm happy not using them for now. Looking forward to your meta issue :)

**Comment by BoboTiG** [comment]
I close the issue as we are now creating StarDcit and DictFile files. Let's open a specific issue if another format is asked.
