### ISSUE TITLE
[EN] Support 'SI-Unit' template and friends

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#424]
- Wiktionary page: 
According to https://github.com/BoboTiG/ebook-reader-dict/issues/399, we need at least
SI-unit --> https://en.wiktionary.org/wiki/hectometre
SI-unit-2 --> https://en.wiktionary.org/wiki/petameter
SI-unit-np --> https://en.wiktionary.org/wiki/petahertz
SI-unit-abb --> https://en.wiktionary.org/wiki/fmole

Wikicode:
```
{{SI-unit|en|hecto|metre|length}}
```

Output:
```
<i>SI-unit</i> <b>hecto</b>
```

Expected:
```
(<i>metrology</i>) An SI unit of length equal to 10<sup>2</sup> metres. Symbol: hm
```

---

Model link, if any: 
https://en.wiktionary.org/wiki/Template:SI-unit (other templates are linked)

**Comment by BoboTiG** [comment]
I fixed `check.sh` on master ;)
