### ISSUE TITLE
[FR] Ignore 'Article' and 'périodique' templates

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#433]
- Wiktionary page: https://fr.wiktionary.org/wiki/in%C3%A9galo-scepticisme

This is the only word using it that throw a warning on our CI. I vote for simply ignoring the template as it is a quite complex one and only use here. There may be other usages, but as the CI did not trigger other warnings, I guess we are safe to just ignore it.

The template is parsed but not displayed as it is part of another ignored one: "source".

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:p%C3%A9riodique

**Comment by BoboTiG** [comment]
WDYT @lasconic?

**Comment by lasconic** [comment]
I agree. Let's ignore them.
