### ISSUE TITLE
[EN] Support 'nuclide' and 'frac' templates

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#437]
- Wiktionary page: https://en.wiktionary.org/wiki/ionium

Wikicode:
```
{{nuclide|230|90|Th}}
```

Output:
```

```

Expected:
```
<sup>230</sup><sub style="margin-left:-2.3ex;">90</sub>C
```

---

Model link, if any: https://en.wiktionary.org/wiki/Template:nuclide

**Comment by lasconic** [comment]
[dicthtml-en.zip](https://github.com/BoboTiG/ebook-reader-dict/files/5645415/dicthtml-en.zip)

I tested the html / css syntax on Kobo with Georgia. It works. @BoboTiG Could you test with FreeSerif if you are still using it ?

**Comment by lasconic** [comment]
Same for "frac" template. The attached dictionary contains "ell" and "ionium". Both work ok on a vanilla kobo with the latest firmware.
[dicthtml-en.zip](https://github.com/BoboTiG/ebook-reader-dict/files/5645689/dicthtml-en.zip)

**Comment by BoboTiG** [comment]
I'll try it tomorrow 👍

**Comment by BoboTiG** [comment]
It renders well 👍 

![screen_011](https://user-images.githubusercontent.com/2033598/101242961-41976a00-36fd-11eb-9b81-96361ab5444f.png)
![screen_012](https://user-images.githubusercontent.com/2033598/101242962-42c89700-36fd-11eb-8808-65293e5cd7cb.png)
