### ISSUE TITLE
[FR] Handle ar-mot and ar-terme

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#456]
- Wiktionary page: https://fr.wiktionary.org/wiki/alezan
https://fr.wiktionary.org/wiki/Muad-Dib

Wikicode:
```
{{ar-mot|elHasan_}}
```

Output:
```
<i>(Ar-mot)</i>
```

Expected:
```
 الحَسَن (elHasan_) 
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:ar-mot

**Comment by lasconic** [comment]
Started here: https://github.com/lasconic/ebook-reader-dict/tree/fix-456

**Comment by BoboTiG** [comment]
Wow. You can let french comments in the script, as it is quite a block code!

**Comment by lasconic** [comment]
it's mainly a conversion of the lua function at https://fr.wiktionary.org/wiki/Module:arabe
I would *never* comment in french :)

**Comment by BoboTiG** [comment]
![screen_001](https://user-images.githubusercontent.com/2033598/102525813-174d9100-409b-11eb-8ee2-e63d2ec5ca7f.png)
![screen_002](https://user-images.githubusercontent.com/2033598/102525817-187ebe00-409b-11eb-8906-67f1ae18fc69.png)
