### ISSUE TITLE
[Meta] Locale refactoring

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#459]
Should we rework how locales are handled? This leads to huge `last_template_hanlder()` containg too much stuff inside.
I did not think about it now, just opening the issue for later discussion.

**Comment by lasconic** [comment]
Local handling seems fine, since wiktionaries are so different locale per locale but last_template_handler is really a drag. As a first step, we could create functions for some of the templates and put them in their own files ? maybe a data structure to call the function based on the template name ?

**Comment by BoboTiG** [comment]
Yes, I was thinking of such stuff.

We could create a function per template, all simply. For the `composé de` template, the normalized function `compose_de()` would be called.

**Comment by BoboTiG** [comment]
I removed the part saying this should be tackled only after #458. In fact, this can be done when we want.

**Comment by lasconic** [comment]
Some templates are rendered by the same function. So we would need a dictionary of "template name" / "function name", somehow very similar to the template_multi one.

**Comment by BoboTiG** [comment]
Yeah. Let's go for a `renderer.py` file where the mapping + functions are stored. WDYT?

**Comment by lasconic** [comment]
OK. I will have a look.

**Comment by BoboTiG** [comment]
As you said, go in several steps to ease reviews ;)

**Comment by lasconic** [comment]
Yes, first step, tackle the french locale only.

**Comment by lasconic** [comment]
FR and ES are in, a PR is pending for EN. I believe we don't need this for CA and SV right now. WDYT ?

Next, I will check if we can remove the logic from last template handler and generalize it like you did for other locale stuff.

**Comment by BoboTiG** [comment]
You are right. Other locales are small and do not need such treatment.

**Comment by lasconic** [comment]
OK moving the call  to render_template in transform_apply() is not as a easy as I expected... there are a lot of problems with scopes, typing etc.. So for now, the code will stay like this and I would consider the refactor done.

**Comment by BoboTiG** [comment]
👍 nice job !
