### ISSUE TITLE
[QA] Why this line doesn't trigger the QA ? 

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#462]
https://github.com/BoboTiG/ebook-reader-dict/blob/8f93968784c065ddb0237bb52193086fd148ef46/scripts/lang/fr/__init__.py#L703

**Comment by BoboTiG** [comment]
It is working for me. If I change the expected result, doctests are failing. What error do you have? 🤔

**Comment by lasconic** [comment]
The line is too long. More than 120 chars. 
Sometimes I have the error, sometimes I don't... I solved it by adding # noqa after the whole docstring. See https://github.com/BoboTiG/ebook-reader-dict/pull/461/commits/b300d9ccfaa9bddcc61af0c78c30d27f5fb03ee3#diff-d67b389ed56ec2d71f5d46cec026cb0e755f528fa9794aafb9e82eb9a6cbb82aR698

**Comment by BoboTiG** [comment]
Oh I see. Let's go with that fix then 👍
