### ISSUE TITLE
StarDict file

### ISSUE THREAD

**Issue by kbnhvn** [BoboTiG/ebook-reader-dict#481]
Hi,

I tried the StarDict zip, but .dict file is missing, only .ifo and .idx inside.
Maybe I have to use .df file, but how?

Many thanks for your work !

**Comment by kbnhvn** [comment]
I managed to convert .df to StarDict files using PyGlossary. Now I have .dict.dz, .idx, .ifo, .syn files and "res" folder. It works with my ereader.

**Comment by BoboTiG** [comment]
Could you share the command used to generate the dict?

And what StarDict file did you try exactly?

**Comment by kbnhvn** [comment]
I first tried the dict-fr.zip file, from release. But it only contains .ifo and .idx files.
Then I downloaded the dict-fr-fr.df file, and convert it to StarDict file with PyGlossary, using interative CLI.

Steps used:
Download PyGlossary-master from [https://github.com/ilius/pyglossary](url)
sudo pip3 install mistune==2.0.0a4
Open CLI in PyGlossary-master folder
sudo python3 main.py --cmd
> Input file: dict-fr-fr.df
> Output file: dict-fr
> Output format: Stardict
> Select action (ENTER to convert):

It gaves me some errors for "res" files but I now have a folder "res" and dict-fr.dict.dz, dict-fr.ifo, dict-fr.idx, dict-fr.syn files.

Put all these files in a folder "dict-fr" in my ereader's "dict" folder .

My linux skills are quite poor, so I don't know if all these steps are the best ones.

**Comment by BoboTiG** [comment]
Thanks a lot for those details. I updated files in the release page. Do you mind trying again to let me knwo if the process is good now 🙏 ?

**Comment by kbnhvn** [comment]
This release works well.
Thanks a lot for your work !!

**Comment by BoboTiG** [comment]
Ah cool, thanks for your test 💪

**Comment by kbnhvn** [comment]
I don't know how It should look.
How it looks on Boox Nova 3 (Android):

[https://rehost.diberie.com/Picture/Get/r/33583](url)

**Comment by BoboTiG** [comment]
It seems quite fine for a first support. On the Kobo it looks like http://www.tiger-222.fr/?d=2020/04/17/22/14/21-un-dictionnaire-alternatif-et-complet-pour-la-votre-liseuse#projet (click on links, they are screenshots).

**Comment by kbnhvn** [comment]
Yes it's fine.
I tried with words used as examples in this link.
Some functions are missing (like maths formulas)

https://rehost.diberie.com/Picture/Get/t/33590
https://rehost.diberie.com/Picture/Get/t/33591
https://rehost.diberie.com/Picture/Get/t/33592

**Comment by kbnhvn** [comment]
For maths formulas and characters, it's an issue with StarDict, just checked on other dictionaries.
I don't know if StarDict can handle it.
