### ISSUE TITLE
[EN] Add auto-update script for si_units.py

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#512]
The title says all.

**Comment by BoboTiG** [comment]
@lasconic I am stuggling finding the template data. Can you give me some links? 🙏

**Comment by lasconic** [comment]
I wrote this one manually. 
The best source is probably: https://en.wiktionary.org/w/index.php?title=Template:SI-unit&action=edit
but I doubt SI units will change anytime soon.
