### ISSUE TITLE
[CA] Handle the 'etim-lang' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#514]
- Wiktionary page: https://ca.wiktionary.org/wiki/allerar

Wikicode:
```
{{etim-lang|roa-oca|ca|lleer}}
```

Output:
```
None
```

Expected:
```
Del català medieval <i>lleer</i>
```

---

Model link, if any: https://ca.wiktionary.org/wiki/Plantilla:etim-lang

**Comment by lasconic** [comment]
I believe this bug is already fixed ?

**Comment by BoboTiG** [comment]
It seems a duplicate of #179 🤔 
Let's close this one then, good catch!
