### ISSUE TITLE
[PT] Add a script to fetch 'escopos'

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#554]
- Wiktionary page: https://pt.wiktionary.org/wiki/Ajuda:Guia_de_edi%C3%A7%C3%A3o/Lista_de_escopos

This will be used to populate `templates_italic` and fix a lot of issues found by `--check-word`. We just need to find the good page listing of the values.

**Comment by lasconic** [comment]
Probably https://pt.wiktionary.org/w/index.php?title=Predefini%C3%A7%C3%A3o:escopo/n%C3%BAcleo&action=edit ?

**Comment by BoboTiG** [comment]
Ah yes, exactly. I am definitely not efficient to find those kind of links ... :D
