### ISSUE TITLE
[FR] Tweak handling of the 'composé de' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#572]
- Wiktionary page: https://fr.wiktionary.org/wiki/morinelle

Wikicode:
```
{{composé de|m=1|morin|morine|-elle|lang=fr}}
```

Output:
```
Dérivé de <i>morin</i>, <i>morine</i> et <i>-elle</i>
```

Expected:
```
Composé de <i>morin</i>, <i>morine</i> et <i>-elle</i>
```

**Comment by BoboTiG** [comment]
Same "error" for https://fr.wiktionary.org/wiki/imbrouillable.

**Comment by BoboTiG** [comment]
And https://fr.wiktionary.org/wiki/adextr%C3%A9.

**Comment by lasconic** [comment]
Also see https://fr.wiktionary.org/wiki/eurasien

**Comment by lasconic** [comment]
And a bit different but related : https://fr.wiktionary.org/wiki/bimestre

**Comment by lasconic** [comment]
https://fr.wiktionary.org/wiki/antipolice

**Comment by lasconic** [comment]
https://fr.wiktionary.org/wiki/bloc_d%E2%80%99obturation_de_puits

**Comment by lasconic** [comment]
https://fr.wiktionary.org/wiki/p%C3%A9ricolpite

**Comment by lasconic** [comment]
https://fr.wiktionary.org/wiki/ent%C3%A9rographie
