### ISSUE TITLE
Optimize parse step by filtering foreign words out

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#575]
I used `check-word-random` a couple of times and find it disturbing to see chinese words being checked. 
`check-word-random` uses the file created by parse step and in this step we don't filter out foreign words. I believe we can do it with just a string match on head_sections[locale].

**Comment by lasconic** [comment]
For french parse_wikicode.json was 1.8GB, it's not 973MB.
Parse time is more or less the same.

**Comment by lasconic** [comment]
But tests are failing... I'm on it.

**Comment by BoboTiG** [comment]
Nice addition!
