### ISSUE TITLE
Arabic and Persian scripts not rendered in italic

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#584]
- Wiktionary page: https://fr.wiktionary.org/wiki/tasse

Wikicode:
```
De l’{{étyl|ar|fr|mot=طس|tr=tass|sens=[[coupe]], [[écuelle]]}}, lui-même, selon certains, [[emprunté]] au {{étyl|fa|fr|mot=تشت|tr=tašt|sens=tasse}}, [[soucoupe]], ce qui serait inexact selon {{w|Henri Lammens|Lammens}}. Les dérivés''تشت tašt'' et ''طست tast'', respectivement persan et arabe, sont du même radical « de haute antiquité » arabe: ''طس tas'''.
```
Here, arabic characters are well printed when they are handled by the `étyl` template. But when those characters are part of the "normal" text, their representation is broken. I mean:
```python
# OK
{{étyl|ar|fr|mot=طس|tr=tass|sens=[[coupe]], [[écuelle]]}}

# BAD
''طس tas''
```

I will post a screenshot in coming days to demonstrate the issue.

**Comment by BoboTiG** [comment]
Here is the screenshot, I do not know yet why this renders badly:
![screen_001](https://user-images.githubusercontent.com/2033598/106354373-b21fc900-62f1-11eb-9569-4dddb08186b7.png)

**Comment by lasconic** [comment]
It would be very cool to have a command to :
* get one or more words with get-word
* create a kobo dict with them (zipped and/or unzipped)
:)

**Comment by BoboTiG** [comment]
Ah yes! Like `--gen-dict WORD [WORD...]`. :+100

**Comment by lasconic** [comment]
See #666 

Can you reproduce with this dictionary ? 
[dicthtml-fr.zip](https://github.com/BoboTiG/ebook-reader-dict/files/5919373/dicthtml-fr.zip)

**Comment by BoboTiG** [comment]
`--gen-dict` is a killer feature, wht an idea! :)

**Comment by BoboTiG** [comment]
Same result with that dict.

**Comment by lasconic** [comment]
The HTML looks good.
I believe it's the italic. Freeserif doesn't have italic arabic or the webkit version on the Kobo doesn't handle italic correctly for these scripts... Not sure italic is really used in arabic or persic.

**Comment by BoboTiG** [comment]
Good catch.

**Comment by lasconic** [comment]
Yes, no arabic in freeserif italic https://fonts2u.com/free-serif-italic.font

**Comment by lasconic** [comment]
I'm not sure if we can do much more. I couldn't find a unicode font with italic arabic.

**Comment by BoboTiG** [comment]
If it was only "tasse" I would have changed the formatting on the Wiktionary. But I doubt it is the only one.

**Comment by lasconic** [comment]
Can we find them somehow ? Look for `''+arabic letter` in the wikicode dump? or in render.py look for '<i>+arabic' before writing the definitions?

**Comment by lasconic** [comment]
``
`
<i>[^<]*([\u0627-\u064a]+)[^<]*</i>
```

**Comment by lasconic** [comment]
I could detect a few: https://gist.github.com/lasconic/56762057597b1eaa8c0465ab89c4dc22


added the following in `parse_word` in `render.py` and ran `--render`

```Python
    
    regex = r"<i>[^<]*([\u0627-\u064a]+)[^<]*</i>"
    def check_arabic(definition: str):
        matches = re.findall(regex, definition)
        if matches:
            print("####ERROR arabic in italic in definition :" + word, flush=True)
            print(definition, flush=True)
            print(matches, flush=True)
    
    for definition in definitions:
        if isinstance(definition, tuple):
            for subdef in definition:
                if isinstance(subdef, tuple):
                    for subsubdef in subdef:
                        check_arabic(subsubdef)
                else:
                    check_arabic(subdef)
        else:
            check_arabic(definition)
            
    if etymology:
        matches = re.findall(regex, etymology)
        if matches:
            print("####ERROR arabic in italic in etymology :" + word, flush=True)
            print(etymology, flush=True)
            print(matches, flush=True)
```
