### ISSUE TITLE
[ES] [[Categoría]] shouldn't be printed

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#588]
- Wiktionary page: https://es.wiktionary.org/wiki/flagrancia

Wikicode:
```
[[Categoría:ES:Palabras con el sufijo -ncia]]

```

Output:
```
Categoría:ES:Palabras con el sufijo -ncia
```

Expected:
```
_Nothing_
```

---

Model link, if any:

**Comment by BoboTiG** [comment]
We could leverage the `pattern_file` maybe.
