### ISSUE TITLE
[FR] Pluriels irréguliers

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#59]
Dans la continuité de #56, il reste quelques mots qui ne sont pas bien pris en charge : yeux, cris, ...

**Comment by BoboTiG** [comment]
@NicoR45 les modifications seront apportées dans l'archive de demain. J'ai fait comme tu proposais : si la définition comporte seulement "Pluriel de" (entre autres) mais qu'il ne s'agit pas d'un mot irrégulier, alors on jarte la définition.

Pour le moment, la liste des définitions à ignorer est :
https://github.com/BoboTiG/ebook-reader-dict/blob/b9865e16ff2de1fd70870aa8582484a64ee7a212/scripts/lang/fr/__init__.py#L109-L114

Et les mots à garder :
https://github.com/BoboTiG/ebook-reader-dict/blob/b9865e16ff2de1fd70870aa8582484a64ee7a212/scripts/lang/fr/__init__.py#L121-L135

Il y a "cris" dans cette liste, car il ne serait jamais affiché sinon ("Cris" aurait l'ascendant"). J'imagine qu'il y aura d'autres exceptions à ajouter, mais on a une bonne base là.

**Comment by BoboTiG** [comment]
J'avais pensé à une autre solution, mais je ne suis pas certain que ça soit bon ni que ça vaille la peine. Prenons le cas de "yeux" : en fait, on copierait la totalité des informations de "oeil" et on afficherait tel quel.

Mais ça pourrait dérouter les personnes car la vraie définitions ne serait pas affichée ("Pluriel de xxx").

**Comment by NicoR45** [comment]
Bonjour,
Impec je teste asap.
Merci :)

**Comment by NicoR45** [comment]
Bonjour BobTiG,
Après plusieurs heures de lecture, RAS.
Le dico d'origine fait pâle figure à coté de ton dico.
Je suis en train de finir Les Furtifs de Damasio et franchement c'est pas du luxe d'avoir pu bénéficié de ton dico ;-)
Merci !

**Comment by BoboTiG** [comment]
M'en parle pas, Damasio est un bon client avec ses mots :)

Super nouvelle alors, merci pour les tests :muscle:
