### ISSUE TITLE
[ES] Ignore 'forma verbo' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#590]
- Wiktionary page: https://es.wiktionary.org/wiki/musculo

Wikicode:
```
{{forma verbo|muscular|p=1s|t=presente|m=indicativo}}
```

Output:
```
<i>(Forma verbo, Muscular, P=1s, T=presente, M=indicativo)</i>
```

Expected:
```
<i>Primera persona del singular (yo) del presente de indicativo de</i> muscular <i>o de</i> muscularse.
```

---

Model link, if any: https://es.wiktionary.org/wiki/Plantilla:forma_verbo

**Comment by lasconic** [comment]
Should we ignore this one instead ?

**Comment by BoboTiG** [comment]
I would say yes, let ignore that template.
