### ISSUE TITLE
[FR] Add support for the 'ar-cf' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#643]
- Wiktionary page: https://fr.wiktionary.org/wiki/Mourad
- Model link: https://fr.wiktionary.org/wiki/Mod%C3%A8le:ar-cf

**Comment by lasconic** [comment]
this is a hard one... We need to replicate https://fr.wiktionary.org/wiki/Module:arabe#L-474 arabe.appliquer like we did for arabiser.

**Comment by BoboTiG** [comment]
Yes. We can just postpone its handling until more word will be using it.

**Comment by BoboTiG** [comment]
Another one: https://fr.wiktionary.org/wiki/alm%C3%A9e

**Comment by lasconic** [comment]
ar-terme: https://fr.wiktionary.org/wiki/qasida

**Comment by BoboTiG** [comment]
ar-terme: https://fr.wiktionary.org/wiki/Muad-Dib

**Comment by BoboTiG** [comment]
Here are all words using that template:

```
 !! Missing 'ar-cf' template support for word 'cafir'
 !! Missing 'ar-cf' template support for word 'Coran'
 !! Missing 'ar-cf' template support for word 'casbah'
 !! Missing 'ar-cf' template support for word 'azulejo'
 !! Missing 'ar-cf' template support for word 'Ali'
 !! Missing 'ar-cf' template support for word 'Omar'
 !! Missing 'ar-cf' template support for word 'assorath'
 !! Missing 'ar-cf' template support for word 'alcade'
 !! Missing 'ar-cf' template support for word 'Imran'
 !! Missing 'ar-cf' template support for word 'Zahra'
 !! Missing 'ar-cf' template support for word 'adhan'
 !! Missing 'ar-cf' template support for word 'Ryad'
 !! Missing 'ar-cf' template support for word 'Mourad'
 !! Missing 'ar-cf' template support for word 'cabas'
 !! Missing 'ar-cf' template support for word 'Majlis'
 !! Missing 'ar-cf' template support for word 'djihad'
 !! Missing 'ar-cf' template support for word 'nadir'
 !! Missing 'ar-cf' template support for word 'génie'
 !! Missing 'ar-cf' template support for word 'ihram'
 !! Missing 'ar-cf' template support for word 'sura'
 !! Missing 'ar-cf' template support for word 'schème'
```

**Comment by BoboTiG** [comment]
So, I converted `appliquer()` to Python. And finally, I just saw we also need to fetch https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:Mod%C3%A8les_de_racine_en_arabe_du_Wiktionnaire.

Work is still ongoing :timer_clock:

**Comment by BoboTiG** [comment]
#1414 needs way more work than I expected.

As stated in the documentation:

```
Le modèle :
 1. transcrit le paramètre en arabe et fait un lien sur la page correspondante ;
 2. donne la translittération, avec lien sur la convention de translittération ;
 3. donne la définition courte du terme (modèle de schème passé en paramètre du modèle de racine).
```

For now, the PR only tackles the last point (3).

For (2) and (3), we also need to support https://fr.wiktionary.org/wiki/Mod%C3%A8le:ar-abiser I guess? It seems we cannot rely on the current `arabiser()` fonction: results are not good (maybe it is my implementation that is incorrect too, though).

It will be for later, I'll pause the work for a moment. @lasconic  if you want to move on, you can use the PR as a team effort. In any cases, I'll find some time to make progress the next week, hopefully.

**Comment by lasconic** [comment]
ar-ab https://fr.wiktionary.org/wiki/Loubna

**Comment by lasconic** [comment]
I took a deep look into the issue and #1414 

1/ Lua a string are 1-indexed ... while python script are 0-indexed.
2/ The script is not enough, we need all the senses for the couple racine/scheme and probably the "forme".

I have 3 working correctly now. It's not given by appliquer. 
Appliquer is supposed to give 2 and a call to arabiser with the result of appliquer should give 1..

Quite a bit of work and testing. I already spent some time on it. I will look further this week.

**Comment by lasconic** [comment]
With this PR, all the words from https://github.com/BoboTiG/ebook-reader-dict/issues/643#issuecomment-1287812200 are OK with check-word except for "schème" which uses other non supported templates (ar-racine/nom and ar-sch)

**Comment by lasconic** [comment]
The two big learning points about porting lua to python
* 1-indexed vs 0-indexed strings
* End of slices : sub(scheme, 1, position -1) --> scheme[:position]

**Comment by lasconic** [comment]
> With this PR, all the words from [#643 (comment)](https://github.com/BoboTiG/ebook-reader-dict/issues/643#issuecomment-1287812200) are OK with check-word except for "schème" which uses other non supported templates (ar-racine/nom and ar-sch)

schème is now OK with https://github.com/BoboTiG/ebook-reader-dict/pull/1742 and the support of `ar-racine/nom` and `ar-sch`
