### ISSUE TITLE
[SV] Release translation needed

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#65]
It is currently translated to english: https://github.com/BoboTiG/ebook-reader-dict/releases/tag/sv

The sentences are here: https://github.com/BoboTiG/ebook-reader-dict/blob/78879ec2a7d38bddc79ae7db36af7b020fed2452/scripts/lang/defaults.py#L52-L72

cf @Emileeson :)

**Comment by BoboTiG** [comment]
Also the locale is not fully tested because I have 0% knowledges. So a dictionary is available and it just needs to be tested :)

**Comment by Emileeson** [comment]
I just tested it, seems to works really fine. I'll test it more accurately in the future and let you know if there's anything. 
But right now that's awesome :D

**Comment by BoboTiG** [comment]
Great news! Do you mind translating teé release description?

**Comment by Emileeson** [comment]
Do you mean from english into swedish?
I'm learning swedish actually. I could give it a try but cannot guarantee the result quality

**Comment by BoboTiG** [comment]
Or from french to swedish if you prefer :)

**Comment by Emileeson** [comment]
Should be able to do it soon. Keep you posted then!
