### ISSUE TITLE
[CA] Handle the 'pos' argument of the 'terme' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#659]
- Wiktionary page: https://ca.wiktionary.org/wiki/amazic

Wikicode:
```
{{terme|zgh|ⴰⵎⴰⵣⵉⵖ|pos=gentilici}}
```

Output:
```
<i>ⴰⵎⴰⵣⵉⵖ</i>
```

Expected:
```
<i>ⴰⵎⴰⵣⵉⵖ</i> ‎(<i>amaziɣ, gentilici</i>)
```

---

Model link, if any: https://ca.wiktionary.org/wiki/Plantilla:terme (the arg is not documented ...)

**Comment by lasconic** [comment]
Handling "pos" is simple enough... but the automatic transcription from amazigh would need a dedicated transliteration module. We currently don't have transliteration per language but 
https://ca.wiktionary.org/wiki/M%C3%B2dul:ber-trans
and
https://en.wiktionary.org/wiki/Module:ber-translit

looks different...
