### ISSUE TITLE
Remove colors code

### ISSUE THREAD

**Issue by GittyBob** [BoboTiG/ebook-reader-dict#661]
Hi,

Thanks a lot for this great work !

I noticed this problem: the french dictionnary (at least, it's the only one I tested) includes code of sample colors displayed in the definitions of wiktionary:

e.g:

On the web site page : https://fr.wiktionary.org/wiki/blanc

we can read :

> _(Par extension) D’une couleur appartenant au champ chromatique du blanc, c’est-à-dire légèrement différente de la couleur originelle mais lié à celle-ci.  

This sentence is followed by color rectangles

The color codes : #FFFFFF #FFFFD4 #FDE9E0 #FDE1B8 #F2FFFF #EFEFEF_

are copied in the dictionary.

I think that they should be removed.

Thanks !

**Comment by BoboTiG** [comment]
Hello @GittyBob,

Color codes are present on purpose. Of course for white or black it is obvious but for any other colors like "taupe" or "empire", it is useful to have the RGB codes. The Wiktionary has a better representation of those colors.
I think it makes sense to keep them in the dictionary.

**Comment by lasconic** [comment]
Thank you for your report ! Keep them coming.
I agree with @BoboTiG on this one. We should keep them in the output.

We do need a solution for color code in check-word though.
