### ISSUE TITLE
[FR] Handling similar plurals and proper nouns

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#663]
When selecting the word "combes" on the Kobo, the word printed will be https://fr.wiktionary.org/wiki/Combes and we loose the redirection to its singluar form https://fr.wiktionary.org/wiki/combe.

Maybe finding a way to display both would be ideal.

**Comment by lasconic** [comment]
The only way I see is to store "combes" as a word, with the definition of combes. Looking for "combes" will then display "Combes" and "combes". 
So something similar that what we do with "pure verb form". 

Simplified algo:
1/ Do no ignore "pluriel d" definition
2/ if a word only has one definition and it starts with "pluriel d", check if the same word with different case exists. If it doesn't just keep on and ignore this word. If it does, see 3
3/ Store this word with the definitions and etymology of the word after "pluried d"

Note: when the plural is also a verb form, we already handle it ? See https://github.com/BoboTiG/ebook-reader-dict/issues/208

**Comment by BoboTiG** [comment]
I think more templates could be handled, see https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:Mod%C3%A8les_d%E2%80%99accord_en_fran%C3%A7ais. But for now, 125e22dcbf4fa445fd54b564aa2a192783ee6a41 is a good start.
