### ISSUE TITLE
[FR] check-word is too strict when removing anchors

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#669]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=blanc

```
python -m wikidict fr --check-word "blanc"
```

fails with 3 errors because the page contains HTML such as 
```
<a href="#fr-nom-1">blanc</a>
```
which is completely ignored by check-word here: https://github.com/BoboTiG/ebook-reader-dict/blob/master/wikidict/check_word.py#L62

I don't understand why we are doing this since some anchors do make sense.

**Comment by BoboTiG** [comment]
We did it to filter out such links: https://github.com/BoboTiG/ebook-reader-dict/blob/afacfebb86a93c15c5ee5a9fdaa002b6a5e232fa/tests/test_4_check_word.py#L31
