### ISSUE TITLE
[FR] Support 'R:TLFi' template 

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#679]
- Wiktionary page: https://fr.wiktionary.org/wiki/pedzouille

Wikicode:
```
{{R:TLFi}}
```

Output:
```

```

Expected:
```
« pedzouille », dans <i>TLFi, Le Trésor de la langue française informatisé</i>, 1971–1994 → consulter cet ouvrage
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:R:TLFi

Not sure if we want to keep "→ consulter cet ouvrage"

@BoboTiG WDYT ?

**Comment by BoboTiG** [comment]
> Not sure if we want to keep "→ consulter cet ouvrage"

No, we should not keep it.

**Comment by lasconic** [comment]
Unfortunately, I have to reopen this issue...

{{R:TLFi}} is different from {{R|TLFi}}. We only want to render the first one and not the second one. Currently we cannot make the difference because {{R:TLFi}}  is converted to {{R|TLFi}} early in the process. I'm not sure if the PR is doing more good than harm... so I would propose to revert it for now...

See 
https://fr.wiktionary.org/w/index.php?title=m%C3%A9tis
https://fr.wiktionary.org/w/index.php?title=pedzouille

**Comment by BoboTiG** [comment]
An idea: when cleaning the HTML, we could convert `{{R:XXX}}` to `{{XXX}}`. Then, it would be as simple as defining a template handler for `XXX`. WDYT?

**Comment by lasconic** [comment]
Another one at : https://fr.wiktionary.org/w/index.php?title=barricade

It's a good idea, but if we make a template handler for XXX, we could just let it alone and do a template handler for R:XXX directly ?

**Comment by BoboTiG** [comment]
That makes more sense yes :)
I dit not find where we do the `{{R:XXX}}` -> `{{R|XXX}}` conversion. But if we can just handle `{{R:XXX}}` then it is a clean solution IMO.

**Comment by lasconic** [comment]
Very early here: https://github.com/BoboTiG/ebook-reader-dict/blob/69bc58619b06b6e62c9d8b814a6d057430e6389e/wikidict/utils.py#L507

**Comment by BoboTiG** [comment]
Another approach could be to convert `{{formatnum:-1000000}} ` to `{{formatnum|-1000000}} ` in `cleanup()` instead. We could use a predefined list of pattern we want to convert. That would make the process more robust, WDYT?

**Comment by BoboTiG** [comment]
Very quickly, without the patterns list:
```diff
diff --git a/wikidict/utils.py b/wikidict/utils.py
index 213099b..89e6177 100644
--- a/wikidict/utils.py
+++ b/wikidict/utils.py
@@ -368,6 +368,9 @@ def clean(text: str) -> str:
     text = sub(r"<<([^/>]+)>>", "\\1", text)
     text = sub(r"<<(?:[^/>]+)/([^>]+)>>", "\\1", text)
 
+    # {{formatnum:-1000000}} -W {{formatnum|-1000000}}
+    text = sub(r"{{(formatnum):([^}]+)}}", "{{\\1|\\2}}", text)
+
     return text.strip()
 
 
@@ -504,12 +507,6 @@ def transform(word: str, template: str, locale: str) -> str:
     parts = [p.strip("\u200e") for p in parts]  # Left-to-right mark
     tpl = parts[0]
 
-    # {{formatnum:-1000000}}
-    if ":" in tpl:
-        parts_raw = template.split(":")
-        parts = [p.strip() for p in parts_raw]
-        tpl = parts[0]
-
     # Stop early
     if not tpl or tpl in templates_ignored[locale]:
         return ""
```

**Comment by lasconic** [comment]
I don't get why it's better to do it in cleanup but having a way to choose which one we want to convert is definitely a win. We could first try everything but R:TLFi

See PR #696

**Comment by BoboTiG** [comment]
The later would ease adding patterns to ignore for each locale. The former is working too, and maybe could we move to another solution later.

**Comment by lasconic** [comment]
I'm not sure if we rely on this code for formatnum only ? Do you know ?

**Comment by BoboTiG** [comment]
I am not sure. Let's do it and see later if we need to adapt.
