### ISSUE TITLE
[FR] Improve 'sigle' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#718]
- Wiktionary page: https://fr.wiktionary.org/w/index.php?title=CCI

Wikicode:
```
{{sigle|fr|de=Chambre de commerce et d’industrie}}
```

Output:
```
<i>(Sigle)<i>
```

Expected:
```
Sigle de <i>Chambre de commerce et d’industrie</i>
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:sigle

**Comment by lasconic** [comment]
See also  https://fr.wiktionary.org/w/index.php?title=GPL

**Comment by BoboTiG** [comment]
FTR the doc is lying: `m` and `texte` are never used.
