### ISSUE TITLE
[SV] Support 'härledning-' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#725]
- Wiktionary page: https://sv.wiktionary.org/wiki/Knut
- Model link: https://sv.wiktionary.org/wiki/Mall:h%C3%A4rledning-

**Comment by BoboTiG** [comment]
We first need to add the `lngs.py` file for Swedish. I am lost on the Wiktionary, I ould not find the appropriate page listing all langs. For instance, the template needs to map `grc` to `grekiska`.

@lasconic do you have a magic trick to find such page?

**Comment by lasconic** [comment]
Nothing magic unfortunately. It helps to know the language a bit. In this case I don't, but clicking on the link in the first parameter gives a good start : https://sv.wiktionary.org/wiki/Wiktionary:Stilguide/Spr%C3%A5knamn 

The other way I used, follow the wikicode of the template. In this case, https://sv.wiktionary.org/w/index.php?title=Mall:h%C3%A4rledning-&action=edit shows that grc is hardcoded in the template itself...

```

{{#switch:{{{1}}}|la=latinska|gd=gäliska|grc=grekiska|el=nygrekiska|{{{{{1|}}}}}}}
```

**Comment by BoboTiG** [comment]
The template was removed on September 3<sup>rd</sup>, 2022.
