### ISSUE TITLE
[FR] Support 'registre' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#727]
- Wiktionary page: https://fr.wiktionary.org/wiki/mariage

Wikicode:
```
{{registre|traditionnellement}}
```

Output:
```
<i>(Registre)</i>
```

Expected:
```
<i>(Traditionnellement)</i>
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:registre

**Comment by lasconic** [comment]
See also https://fr.wiktionary.org/wiki/duplifier

**Comment by BoboTiG** [comment]
The doc says:
> Ne devrait pas être utilisé directement dans un article.

Should we fix articles instead of handling the template?

**Comment by lasconic** [comment]
It would be ideal indeed but I believe there is no "Registre de langue et d’emploi" for 'Traditionnellement' or 'Jargon', so how do we fix it on wiktionary ?

**Comment by BoboTiG** [comment]
🤔
Then, let"s do handle the template ^^
