### ISSUE TITLE
Poll: Move etymology below definitions?

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#752]
I just saw that https://github.com/tllilleh/ebook-reader-dict fork and it contains only 1 commit: moving the etymology below definitions.
I was wondering if there are more people interested in applying the change by default?

Personnaly, I do not have a strong opinion, I like the way it is for now.

Please vote with emoticons on that message (👍 and 👎).

**Comment by lasconic** [comment]
Maybe we could have an option to pass WORD_FORMAT as a file on the command line ? Then you don't have to keep up to date, but you still need to build yourself.

**Comment by BoboTiG** [comment]
We will keep the current display finally :)
