### ISSUE TITLE
New locale: Bokmål Norwegian

### ISSUE THREAD

**Issue by Duckbilled** [BoboTiG/ebook-reader-dict#754]
Hello,

I would like a Norwegian locale.

If there is some more information needed, please let me know (sorry if this is too barebones :) ).

**Comment by Duckbilled** [comment]
I am trying to run `python -m pytest tests/tests_$LOCALE.py`, but I get the error `No module named pytest`. How do I establish such module?

**Comment by Duckbilled** [comment]
After running `$ python3 -m pytest /tests/tests_no.py` I receive an error which indicates there is no module named wikidict. How do I establish such module?

**Comment by lasconic** [comment]
What's the current dir when you run this command ? It has to be ebook-reader-dict and wikidict will be found automatically. And the command is probably (note the missing slash)

```
$ python3 -m pytest tests/tests_no.py
```

**Comment by Duckbilled** [comment]
Will get back later this week and edit this post and let you know.

**Comment by Duckbilled** [comment]
I'm in the `ebook-reader-dict`. 

```
______________________ ERROR collecting tests/tests_no.py ______________________
ImportError while importing test module '/ebook-reader-dict-no/tests/tests_no.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/ebook-reader-dict-ca/tests/tests_no.py:3: in <module>
    ???
E   ModuleNotFoundError: No module named 'wikidict.render'
```
It also links to ebook-reader-dict-ca, which I don't really understand (I used Catalonian lang). Might that be something I am missing?

**Comment by Duckbilled** [comment]
Yes, `wikidict`, with a directory called `lang` in which there is the file `__init__.py`, other than that it is empty.

**Comment by lasconic** [comment]
Well here is your problem... it shouldn't be empty.
If you want to add 'no' locale, you need a clean clone of this repo and then add no related files.

**Comment by Duckbilled** [comment]
🤦🏾 thanks for that! And the `lang` file is `the __init__.py` or is that a directory?

**Comment by lasconic** [comment]
Ok. I guess you are following https://github.com/BoboTiG/ebook-reader-dict/wiki/HOWTO-Add-a-New-Local right ?

You need to copy for example the wikidict/lang/ca directory to wikidict/lang/no and then edit the files in there to the right value for `no`.  Change wikidict/lang/__init__.py to add no everywhere.

**Comment by Duckbilled** [comment]
Is this the correct response to 

`$ python3 -m pytest tests/tests_no.py`

```
============================= test session starts ==============================
platform darwin -- Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /usr/local/opt/python@3.9/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/xxx/Desktop/ebook-reader-dict-no, configfile: setup.cfg
plugins: cov-2.11.1
collected 0 items                                                              
Coverage.py warning: No data was collected. (no-data-collected)


---------- coverage: platform darwin, python 3.9.4-final-0 -----------
Name                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------
wikidict/__init__ .py                3      3     0%   10-12
wikidict/__main__.py                 2      2     0%   18-20
wikidict/check_random_words.py      21     21     0%   2-31
wikidict/check_word.py              95     95     0%   2-162
wikidict/constants.py               10     10     0%   6-34
wikidict/convert.py                210    210     0%   2-371
wikidict/download.py                72     72     0%   4-124
wikidict/find_templates.py          42     42     0%   2-65
wikidict/gen_dict.py                15     15     0%   1-21
wikidict/get_word.py                44     44     0%   2-75
wikidict/parse.py                   62     62     0%   2-106
wikidict/render.py                 202    202     0%   2-360
wikidict/stubs.py                    7      7     0%   2-9
wikidict/transliterator.py          19     19     0%   11-788
wikidict/upload.py                  28     28     0%   2-49
wikidict/user_functions.py         112    112     0%   6-479
wikidict/utils.py                  161    161     0%   2-582
--------------------------------------------------------------
TOTAL                             1105   1105     0%
Coverage HTML written to dir htmlcov

============================ no tests ran in 0.33s =============================
```

**Comment by lasconic** [comment]
For a start, yes I guess. The file should be test_no.py and not tests_no.py

**Comment by Duckbilled** [comment]
Should that command be `$ python3 -m pytest tests/test_no.py` in that case? If so the `HOWTO` might need to be updated.

**Comment by BoboTiG** [comment]
@Duckbilled would you like me to have a look at what you did? I can kick off the locale as it is the more complex part of the job :)

**Comment by Duckbilled** [comment]
That would be great :)

**Comment by BoboTiG** [comment]
Could you push whag you did on a branch on your fork? Or send me files via email

**Comment by Duckbilled** [comment]
@BoboTiG I saw you edited the how to, I will have a look at that one otherwise I will send you what I have currently (probably over email, but will try to fork it)
