### ISSUE TITLE
[FR] Rework output of the person() user function

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#756]
- Wiktionary page: https://fr.wiktionary.org/wiki/masochiste

Wikicode:
```
{{nom w pc|Leopold von Sacher-''Masoch''}}
```

Output:
```
user_functions.py:331: UserWarning: Malformed template in the Wikicode of 'masochiste' (parts=['Leopold von Sacher-<i>Masoch</i>'])
  warn(f"Malformed template in the Wikicode of {word!r} (parts={parts})")
Leopold von Sacher-<i>Masoch</i>
```

Expected: no warning

---

`nom w pc` is calling `person()` with only one arguent, resulting in the warning, cf https://github.com/BoboTiG/ebook-reader-dict/blob/b8477d7d2f1ce039142240290549e2a150fd74f6/wikidict/lang/fr/__init__.py#L547

I do not recall why the warning was put, it was introduced with f66c96eb115cf328638558e6e98447114f1d467e.

**Comment by BoboTiG** [comment]
@lasconic WDYT? I guess the warning may be useful sometimes, when the last name is not set.

I just saw (here](https://fr.wiktionary.org/wiki/Mod%C3%A8le:nom_w_pc) that the template is deprecated:
> ATTENTION : il est désormais recommandé d’utiliser des caractères ordinaires pour le nom de famille des auteurs (décision collective de mars 2021). L’usage de ce modèle est en conséquence à éviter. Il a été modifié pour ne plus afficher de petites capitales.

**Comment by BoboTiG** [comment]
I'll fix the template handling, will let the PR opened for review :)

**Comment by lasconic** [comment]
I never liked the small cap for last names :) and I guess the warning is obsolete?

**Comment by BoboTiG** [comment]
Yup :)
