### ISSUE TITLE
[ES] Support 'trad' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#797]
- Wiktionary page: [https://es.wiktionary.org/wiki/p._m.](https://es.wiktionary.org/wiki/p._m.)

Wikicode:
```
{{trad|la|post meridiem}}
```

Output:
```
<i><i>(Trad, La, Post meridiem)</i></i>
```

Expected:
```
<i>post meridem</i>
```

---

Model link, if any: https://es.wiktionary.org/wiki/Plantilla:trad

**Comment by lasconic** [comment]
@BoboTiG Do you agree that we don't need to output the language code ?

**Comment by BoboTiG** [comment]
We need to be consistent. For PT, we ouput the language code (#547).

Maybe was it a mistake, and we could suppress the language code output (and need to adjust `--check-word` accordingly).

**Comment by lasconic** [comment]
OK. Let's keep it then.
