### ISSUE TITLE
[FR] Le mot "hématite" est manquant alors que présent dans wiktionary

### ISSUE THREAD

**Issue by patalex74** [BoboTiG/ebook-reader-dict#83]
Wiktionary page: https://fr.wiktionary.org/wiki/h%C3%A9matite

**Comment by BoboTiG** [comment]
Bonjour,

Quelle est la version du ZIP que tu as téléchargé ?

Le mot est bien présent, prends voir la dernière version disponible.

**Comment by patalex74** [comment]
Bonjour, merci de ta réponse, j’ai téléchargé celui qui est sur la page. : dicthtml-fr.zip <https://github.com/BoboTiG/ebook-reader-dict/releases/download/fr/dicthtml-fr.zip> et lorsque je fais une recherche sur « hématite » j’ai le retour suivant : 
Votre recherche de « hématite » ne correspond à aucun terme dans le dictionnaire. La correspondance la plus proche est « hématie ».

De même pour une recherche sur « laudes » ….

Bien cordialement

**Comment by BoboTiG** [comment]
Hmmm "laudes" est bien présent aussi.

As-tu redémarré la liseuse?

**Comment by patalex74** [comment]
Oui pas de souci la dessus, c’est bien le wiktionary qui est présent lors de l’appel du dictionnaire

**Comment by BoboTiG** [comment]
En fait, le dictionnaire est regénéré tous les jours, du coup il se peut que la version que tu avais téléchargé ne contenait pas encore ces mots.

**Comment by BoboTiG** [comment]
Et le fait de redémarrer la liseuse est nécessaire pour prendre en compte les nouveaux mots.

**Comment by patalex74** [comment]
Peux tu m’envoyer le lien vers le bon fichier ? Merci

**Comment by BoboTiG** [comment]
https://github.com/BoboTiG/ebook-reader-dict/releases/download/fr/dicthtml-fr.zip est le bon lien. Je viens de tester et les mots sont bien présent dans cette version.

Re-télécharge ce fichier, copie/colle dans le bon dossier de la liseuse et redémarre-là. Il n'y a pas de raison que ça ne fonctionne pas.

**Comment by patalex74** [comment]
Merci !!! C’est parfait cela fonctionne correctement avec ces mots !
Donc, il y a une MAJ chaque nuit ? 
Bon après midi et encore merci !

**Comment by BoboTiG** [comment]
Ah, cool !

Oui, c'est exact, les dictionnaires (les fichiers `dicthtml-*.zip`) sont mis à jour toutes les nuits.
