### ISSUE TITLE
[ES] Support 'variantes' template ?

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#832]
- Wiktionary page: 
- https://es.wiktionary.org/w/index.php?title=adarme
- https://es.wiktionary.org/w/index.php?title=adehala
- https://es.wiktionary.org/w/index.php?title=adiestrador

@BoboTiG any preference for the output ?

Wikicode:
```
{{variantes|adestrador|nota=poco frecuente}}
```

Output:
```

```

Expected:
```

```

---

Model link, if any: https://es.wiktionary.org/wiki/Plantilla:variantes

**Comment by lasconic** [comment]
For some more context, we are trying to parse this template only 5 times in the whole es dictionary...

['variantes', 'amaestrador', "('variantes', 'adestrador', 'nota=poco frecuente')"]
['variantes', 'adarme', "('variantes', 'adárame', 'nota=desusado')"]
['variantes', 'adehala', "('variantes', 'adahala', 'nota=desusado')"]
['variantes', 'adiestrador', "('variantes', 'adestrador', 'nota=poco frecuente')"]
['variantes', 'prión', "('variantes', 'prion', 'nota=Grafía correcta luego de la reforma ortográfica de 2010.')"]

**Comment by BoboTiG** [comment]
Option seems a good choice then :)

**Comment by BoboTiG** [comment]
I went with option 1 simplified: no need for a list.
