### ISSUE TITLE
[CA] Support the 'ex-cit' template?

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#843]
- Wiktionary page: https://ca.wiktionary.org/wiki/deseixir-se
- Model link: https://ca.wiktionary.org/wiki/Plantilla:ex-cit

Appears only 1 time in the whole dictionary.

**Comment by BoboTiG** [comment]
WDYT @lasconic?

**Comment by lasconic** [comment]
The article on wiktionary can probably be corrected no ?

**Comment by lasconic** [comment]
Yes, I fixed the article. The "example quote" was not supposed to be a definition but included in the first definition. We could ignore the template, but it would be a missed opportunity to contribute to wiktionary :)

**Comment by BoboTiG** [comment]
Let's close the issue then, it is always a good thing to contribute to the Wiktionary :)
