### ISSUE TITLE
[EN] Bad rendering of 'lb' for 'Indian' argument

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#848]
- Wiktionary page: https://en.wiktionary.org/wiki/doubt

Wikicode:
```
{{lb|en|countable|obsolete|or|Indian}}
```

Output:
```
<i>(countable, obsolete or Indian)</i>
```

Expected:
```
<i>(countable, obsolete or India)</i>
```
(note the missing "n")

**Comment by BoboTiG** [comment]
I guess the issue will airse for other languages names.

**Comment by lasconic** [comment]
Yes, most probably. Indian -> India comes from here: https://en.wiktionary.org/wiki/Module:labels/data/regional#L-1395

**Comment by BoboTiG** [comment]
Ah good catch. It seems we will have to add a new script :champagne: :)

**Comment by lasconic** [comment]
And we have a new script ! ;)

**Comment by BoboTiG** [comment]
Excellent ! :muscle: :)
