### ISSUE TITLE
Adding Russian Dictionary

### ISSUE THREAD

**Issue by os88sa** [BoboTiG/ebook-reader-dict#882]
Hello, is it possible to add a Russian locale?

Wiktionary page: 
https://ru.wiktionary.org/wiki/Викисловарь

**Comment by BoboTiG** [comment]
Well, that one will be tough because I have no idea of what I am reading when looking at the russian Wiktionary.

Could you give a link to a wiktionary word where there are definitions and tell me where they are located on the page?

**Comment by BoboTiG** [comment]
Closing for now.
