### ISSUE TITLE
[NO] List of missing templates

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#896]
- #1871
- #1882
- #1883
- #1884
- #1885
- #1889
- #1890
- #1891
- #1892
- #1893
- #1894

**Comment by BoboTiG** [comment]
cc @Duckbilled if you want to give a try ;)

**Comment by Duckbilled** [comment]
Thanks, I had little time in the last few weeks, will have a look next week or the week after :)

**Comment by Duckbilled** [comment]
How do I find the right `head-sections` and section-level`?

**Comment by frafra** [comment]
I am a Python developer, and I would like to help support Norwegian Bokmål :)
Is there any news since basic support has been added? I can try on my free time to move forward with this issue.

**Comment by lasconic** [comment]
I believe there is not much new. You can try yourself. Run

```
python -m wikidict no
``` 

and you should see a similar output

Something weird you might want to check is that we detect only 5000 words while the stats on no.wiktionary.org https://no.wiktionary.org/wiki/Spesial:Statistikk reports a lot more. Could be that there is not much Norsk words in the Norsk wiktionary ;)

**Comment by BoboTiG** [comment]
With yesterday's changes, the words count went from 2,655 to 4,237 (out of a total 5,758). 🎉

**Comment by BoboTiG** [comment]
I created specific issues for not-so-simple/more-complex templates. I am closing that one then.
