### ISSUE TITLE
Missing foreign words from a given locale (ex: Horse in Fr-Dictionnary)

### ISSUE THREAD

**Issue by ben75020** [BoboTiG/ebook-reader-dict#903]
I'm using the Wiktionary while reading English books to get translations in French. However, the "fr-dict" dictionary available does not contain English words from the French Wiktionary (simple example "horse" would be missing from "fr-dict" despite an article exists in the French Wiktionary : https://fr.wiktionary.org/wiki/horse).

Is there a simple way to adapt the configuration in order to include other source languages from the French Wiktionary ? 

(Currently I use the export from AArd2, but this is less convenient as I need to switch to the other android application to lookup a word).

Thanks for your great work.

**Comment by lasconic** [comment]
I assume you are on a Kobo device ? 
My understanding is that this project is about single language dictionaries. For bilingual dictionaries, did you check http://download.wikdict.com/dictionaries/kobo/ ?

**Comment by ben75020** [comment]
I'm using a boox poke 3, android 10 based. 
The bilingual dictionnary you've pointed to are probably fulfilling my needs. Thanks for this gem. :)

**Comment by BoboTiG** [comment]
And now that we officially ship bilingual dictionaries, you could give a try to the fresh new side project: [Reader Dict](https://www.reader-dict.com).
