### ISSUE TITLE
[FR] Fix handling of 'variante de' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#918]
Wiktionary page: https://fr.wiktionary.org/wiki/dz%C3%AAta

Wikicode:
```
{{variante de|zêta|sens=lettre grecque [[ζ]], [[Ζ]]}}
```

Output:
```
Variante de zêta
```

Expected:
```
<i>Variante de</i> zêta («&nbsp;lettre grecque ζ, Ζ&nbsp;»)
```

**Comment by BoboTiG** [comment]
Also, we are not rendering correctly `variante de` by default, it is missing italic part. What is awaited is:
```
<i>Variante de</i> word
```

**Comment by BoboTiG** [comment]
Related to #722.

**Comment by lasconic** [comment]
Also see https://fr.wiktionary.org/wiki/dysph%C3%A9mistique

**Comment by BoboTiG** [comment]
Yes, fixed in the PR.

**Comment by lasconic** [comment]
Also https://fr.wiktionary.org/wiki/tch%C3%A9

**Comment by BoboTiG** [comment]
Also fixed ;)
I think the handling is now correct and it will clean-up the list a bit.

**Comment by lasconic** [comment]
Cool, anything we can do to make code-quality happy ?

**Comment by BoboTiG** [comment]
I just had a look and the import is correct (`utils.py`, line 11). VSCode is also emitting the warning, but the code looks legit :thinking:

**Comment by lasconic** [comment]
Did we change the version of python recently on github actions ?  Is the cache of github actions corrupted ?

**Comment by BoboTiG** [comment]
Nope, it is the new way of handling types annotations by mypy. It is following that upgrade: 6a23b633bb06af7f9ea9d54c837cd78d627a7eb7.

I just found the fix:
```diff
diff --git a/wikidict/utils.py b/wikidict/utils.py
index ccbd38b..86f32a6 100644
--- a/wikidict/utils.py
+++ b/wikidict/utils.py
@@ -8,7 +8,7 @@
 from warnings import warn
 
 from cachetools import cached
-from cachetools.keys import hashkey
+from cachetools.keys import hashkey  # type: ignore
 import regex
 import requests
```

**Comment by lasconic** [comment]
Sure. I'm ok. 👍

**Comment by lasconic** [comment]
Now when I run check.sh, I got 
```
wikidict/utils.py:11: error: unused 'type: ignore' comment
Found 1 error in 1 file (checked 46 source files)
```

**Comment by BoboTiG** [comment]
Do you have an up-to-date venv?

**Comment by lasconic** [comment]
... nope. Thanks. Fixed.
