### ISSUE TITLE
[FR] Fix handling of 'composé de' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#920]
- Wiktionary page: https://fr.wiktionary.org/wiki/Frangistan

Wikicode:
```
{{composé de|فرنگ|ستان|tr1=farang|sens1=Franc|tr2=[[-stan]]|lang=fa}}
```

Output:
```
dérivé de ستان, <i>farang</i> («&nbsp;Franc&nbsp;») avec le suffixe فرنگ, <i>-stan</i>
```

Expected:
```
composé de ستان, <i>farang</i> («&nbsp;Franc&nbsp;») avec le suffixe فرنگ, <i>-stan</i>
```
The only change is "dérivé" -> "composé".

**Comment by BoboTiG** [comment]
Related to #722.

**Comment by lasconic** [comment]
Hard one. I believe we output dérivé because we "see" the - in _-stan_ while mediawiki doesn't see it, it's hidden by the _[[_

**Comment by BoboTiG** [comment]
I can close the issue then, it is OK to have such difference with the Wiktionary.
