### ISSUE TITLE
[FR] Fix handling of 'cf' template when it contains '{{!}}'

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#928]
- Wiktionary page: https://fr.wiktionary.org/wiki/enfant_de_Marie

Wikicode:
```
{{cf|enfant|de|Vierge{{!}}vierge Marie}}
```

Output:
```
<i>de</i> et <i>Vierge!vierge Marie</i>
```

Expected:
```
<i>de</i> et <i>vierge Marie</i>
```

**Comment by BoboTiG** [comment]
Related to #722.

**Comment by BoboTiG** [comment]
https://fr.wiktionary.org/wiki/faits_et_gestes has the same issue, but it seems the rendering is broken there :)

**Comment by lasconic** [comment]
fixed https://fr.wiktionary.org/wiki/faits_et_gestes on wiktionary
