### ISSUE TITLE
Improve check-random-words

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#935]
Currently --check-random-words will choose randomly words in the whole json file. Between 2 runs, it happens that we have the same word. I suggest to rename check-random-words to check-words and add a --random option. Also add the ability to check all words in the list.

**Comment by BoboTiG** [comment]
👍

**Comment by lasconic** [comment]
OK so what about

--check-words [--random] [--count=N] [--offset=M] [--input=filename]

By default it would check the first 100 first words of the json list. With --random it would check 100 random words in the json list. With --input, it would load a text file with one word per line like bad.txt and check all words in it (or limited by count and offset, and maybe random or not...). --offset would be a number or a word. If it's a number it would start and the M word, if it's a word, it would search it in the list and remove all words before this word.

@BoboTiG WDYT ?

**Comment by BoboTiG** [comment]
That would be a great tool, I like the idea :+1: :)

**Comment by lasconic** [comment]
I coded the described behavior. Next step would be to parallelize check-words somehow.
