### ISSUE TITLE
[FR] Support 'au masculin' template

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#941]
- Wiktionary page: https://fr.wiktionary.org/wiki/tout

Wikicode:
```
{{au masculin|p}}
```

Output:
```
<i>(Au masculin)</i>
```

Expected:
```
<i>(Au masculin pluriel)</i>
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:au_masculin

**Comment by lasconic** [comment]
Voir aussi https://fr.wiktionary.org/wiki/quelqu%E2%80%99un

**Comment by BoboTiG** [comment]
Maybe https://fr.wiktionary.org/wiki/Mod%C3%A8le:au_f%C3%A9minin should be handled at the same time?
