### ISSUE TITLE
[FR] Add support for 'laé' template

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#951]
- Wiktionary page: https://fr.wiktionary.org/wiki/MEP

Wikicode:
```
{{laé|fr|nom|1}}
```

Output:
```
Nothing.
```

Expected:
```
<i>(Nom commun 1)</i>
```

---

Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:lien-ancre-%C3%A9tym

**Comment by BoboTiG** [comment]
Same for the long version `{{lien-ancre-étym}}` (ex: https://fr.wiktionary.org/wiki/tarasque).

**Comment by lasconic** [comment]
Currently we ignore both templates.
