### ISSUE TITLE
Fix cleanup of links [[a|b]] when b contains []

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#968]
- Wiktionary page: https://fr.wiktionary.org/wiki/phalanst%C3%A8re
- https://fr.wiktionary.org/wiki/hachereau

Wikicode:
```
[[-au|-[e]au]]
[[phalange#fr|phalan[ge]]] et [[monastère#fr|[mona]stère]]
```

Output:
```
-au|-[e]au
```

Expected:
```
-[e]au
phalan[ge] et [mona]stère
```

---

Model link, if any:

**Comment by BoboTiG** [comment]
Isn't it related to #691.

**Comment by lasconic** [comment]
I forgot that one ...

**Comment by BoboTiG** [comment]
Maybe the title is not exact and could be rephrased ;)

**Comment by lasconic** [comment]
Let's fix it instead ;)
