### ISSUE TITLE
Parallelize --check-words to speed it up

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#972]
check-words performance is bounded by the network to download the wikicode and the wiktionary page. It would be good if we could dispatch each word to a different thread.

**Comment by lasconic** [comment]
In my first tests, I'm rate limited quite fast by wiktionary. Not sure if it's worth the additional complexity in the code...

**Comment by BoboTiG** [comment]
Indeed. Let's keep it simple then.

**Comment by lasconic** [comment]
But with 10 threads, I can check 10k words in 12,5minutes, while it takes ~10 minutes for 1000 with no multithreading... So a PR is coming, let me know what you think.
