### ISSUE TITLE
[Feature Request] Add to my words feature

### ISSUE THREAD

**Issue by Thovi98** [BoboTiG/ebook-reader-dict#999]
Hello @BoboTiG  !
I’ve just discovered your dictionnary, and I must say I’m very impressed and happy 🤗 It’s so much powerful than the official one. 

I don’t know if it’s a dictionary side issue, but I love the Add to my words functionality, and I can’t use it as it’s supposed to.
I explain : 
When I add the dictionary in the custom dict as explained
- the dictionary is not the default one. So I have to reselect it for each word search.
- I can’t add a word to My Words

I read on MobileRead that a workaround is to rename the dictionary `dicthtml-fr.zip` to `dicthtml-fr-fr.zip`. It effectively helps a lot.
- The dictionary is now named Français-Français (Personnalisé)
- I can add it now to My Words.
- But when I go to the My Words list, I see an empty page like this : 

![screen_002](https://user-images.githubusercontent.com/51749973/126862968-f6bea8d2-7d58-4077-b5ff-69582b4130cf.png)- 

So it misses the definition and the book from where it has been added.

Is this issue a firmware problem or a dictionary side issue ? Do you think you’ll be able to solve this ?

Thanks again for your great work !!

**Comment by BoboTiG** [comment]
Hello @Thovi98,

Thanks :)

I can reproduce the issue. If a moved back the dictionary to `dict/dicthtml-fr.zip`, then the word is displayed correctly. I guess this is a firmware issue: `custom-dict` support was not added by Kobo.

I will open an issue on https://github.com/pgaskin/kobopatch-patches or https://github.com/pgaskin/dictutil, thanks for the catch :+1:

**Comment by BoboTiG** [comment]
What are your Kobo model and firmware version?

**Comment by Thovi98** [comment]
Thanks for your fast reply !!
I’ve just tried and indeed, when I replace the official dictionary in `dict/dicthtml-fr.zip`, it works great !
I will try to understand how to stay with this custom dictionary instead of the official one without Kobo trying to replace it at every sync.

Kobo model : Kobo Libra H2O
Firmware version : 4.26.16704

**Comment by BoboTiG** [comment]
I close the issue as it has nothing to do with the project finally. Let's focus on the upstream issue :)
